### ISSUE TITLE
db_stress verification failed on HDFS 2.7.6

### ISSUE THREAD

**Issue by guangruifu** [facebook/rocksdb#5047] opened 2019-03-07 02:30 UTC
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior

db_stress should be able to pass verification in HDFS environment

### Actual behavior
```
./db_stress --hdfs="hdfs://aep2:4545/rocksdb" --db="hdfs://aep2:4545/rocksdb" --verify_checksum=true
2019/03/06-18:14:25  Initializing db_stress
RocksDB version           : 5.18
Format version            : 2
TransactionDB             : false
Read only mode            : false
Atomic flush              : false
Column families           : 10
Clear CFs one in          : 1000000
Number of threads         : 32
Ops per thread            : 1200000
Time to live(sec)         : unused
Read percentage           : 10%
Prefix percentage         : 20%
Write percentage          : 45%
Delete percentage         : 15%
Delete range percentage   : 0%
No overwrite percentage   : 60%
Iterate percentage        : 10%
DB-write-buffer-size      : 0
Write-buffer-size         : 67108864
Iterations                : 10
Max key                   : 1048576
Ratio #ops/#keys          : 36.621094
Num times DB reopens      : 10
Batches/snapshots         : 0
Do update in place        : 0
Num keys per lock         : 4
Compression               : Snappy
Checksum type             : kCRC32c
Max subcompactions        : 1
Memtablerep               : prefix_hash
Test kill odd             : 0
------------------------------------------------
Choosing random keys with no overwrite
Creating 2621440 locks
2019/03/06-18:14:26  Initializing worker threads
2019/03/06-18:14:26  Starting database operations
2019/03/06-18:14:41  Reopening database for the 1th time
2019/03/06-18:15:01  Reopening database for the 2th time
2019/03/06-18:15:20  Reopening database for the 3th time
2019/03/06-18:15:34  Reopening database for the 4th time
2019/03/06-18:15:45  Reopening database for the 5th time
2019/03/06-18:15:58  Reopening database for the 6th time
2019/03/06-18:16:10  Reopening database for the 7th time
2019/03/06-18:16:24  Reopening database for the 8th time
2019/03/06-18:16:36  Reopening database for the 9th time
2019/03/06-18:16:46  Reopening database for the 10th time
2019/03/06-18:17:02  Reopening database for the 11th time
2019/03/06-18:17:06  Starting verification
Verification failed for column family 0 key 32768: Unexpected value found
Stress Test : 133.087 micros/op 240434 ops/sec
            : Wrote 263.62 MB (1.65 MB/sec) (44% of 38400352 ops)
            : Wrote 17276191 times
            : Deleted 4249002 times
            : Single deleted 1512016 times
            : 3839671 read and 1150478 found the key
            : Prefix scanned 7681615 times
            : Iterator size sum is 671139300
            : Iterated 3841505 times
            : Deleted 0 key-ranges
            : Range deletions covered 0 keys
            : Got errors 0 times
            : 0 CompactFiles() succeed
            : 0 CompactFiles() did not succeed
Verification failed :(
```
### Steps to reproduce the behavior
Build and run db_stress with USE_HDFS enabled

**Comment by riversand963** [comment] 2019-03-27 18:06
Thanks @guangruifu for reporting.
Are you able to reproduce this deterministically?
The db_stress has many configuration options. I can set up a hdfs on my local machine and test. At the same time, have you conducted more experiments to narrow down the possible cause for this? For example, change the ratio of different operations, change the number of column families to 1, etc.?

**Comment by riversand963** [comment] 2019-03-28 00:45
@guangruifu , after some investigation, it turns out to be the result of a bug in db_stress.
In the constructor of `StressTest`, original code incorrectly passed an `Option` object to `DestroyDB` without setting its `env` member to `FLAGS_env` (hdfs env in this case). Consequently, the old db in hdfs is not deleted. During validation, you will see values from previous runs, causing the validation to fail.

**Comment by riversand963** [comment] 2019-03-29 16:27
#5122 is in master now, and I believe this issue should be resolved. Closing this for now, feel free to reopen should anything further comes up.

**Closed by riversand963** 2019-03-29 16:27 UTC
