### ISSUE TITLE
ldb tool : assertion failed for dumping a Rockdb database.

### ISSUE THREAD

**Issue by ytrezq** [facebook/rocksdb#10589] opened 2022-08-27 20:33 UTC
I created a 1Tib database using https://github.com/openethereum/openethereum powered by Rocksdb `5.14.3`. The database is perfectly readable through the intended software.

However when I try to read it using the latest version of Rocksdb or the version`5.14.3` :

    sh-5.1# ldb --db=/mnt/openethereum/xdai/db/3c648cbdc4c9333d/archive/db dump
    ldb: /builddir/build/BUILD/storage/rocksdb/rocksdb/tools/ldb_cmd.cc:1636: virtual void rocksdb::DBDumperCommand::DoCommand(): Assertion `!path_.empty()' failed.
    Abandon (core dumped)
    sh-5.1#
I can try to pass `--try_load_options` but then it considers the database to be empty whatever the `—column_family=` argument given :

    sh-5.1# ldb --db=/mnt/openethereum/xdai/db/3c648cbdc4c9333d/archive/db dump --try_load_options
    Keys in range: 0

    sh-5.1#

**Comment by ajkr** [comment] 2022-08-27 23:49
Duplicate of #8081

**Closed by ajkr** 2022-08-27 23:49 UTC

**Comment by ytrezq** [comment] 2022-08-27 23:59
@ajkr : no, your’re wrong as this is the same programs but a different problem. Even if upgrading is Ok, more recent `ldb` should be open the database. But none version of the tools can read it whereas this is possible in #8081.

**Please reopen !**
