### ISSUE TITLE
Windows 7 support

### ISSUE THREAD

**Issue by allspace** [facebook/rocksdb#869] opened 2015-12-06 13:37 UTC
The Windows porting uses certain API which is only available on Windows 8 or later.

GetSystemTimePreciseAsFileTime is one of such APIs.

I am not sure if there are other such APIs too...

Can we eliminate using of such kind of APIs so the rockdb.dll can be used on Windows 7 too?

**Comment by allspace** [comment] 2015-12-06 14:04
seems no other API block Windows 7 support.

As long as replace GetSystemTimePreciseAsFileTime to GetSystemTimeAsFileTime, test app can work on Windows 7 well. 

But I am not sure if such replace is valid. I did not get time to check the context of the usage.

**Comment by yuslepukhin** [comment] 2015-12-07 18:14
@allspace See discussion here https://github.com/facebook/rocksdb/issues/726

**Comment by yuslepukhin** [comment] 2015-12-07 18:18
@allspace You can propose a patch that would have an `#ifdef` for a Windows 7 build driven by a CMake switch.That would mean a deliberate choice with known trade offs.

**Comment by adamretter** [comment] 2017-07-11 16:11
Closing as duplicate of #726

**Closed by adamretter** 2017-07-11 16:11 UTC
Labels: windows
