### ISSUE TITLE
WAL cannot be flushed after transaction Prepared and Rollback

### ISSUE THREAD

**Issue by baoxuezhao** [facebook/rocksdb#4597] opened 2018-10-28 14:02 UTC
Hello,

We are using the TransactionDB as well as the [Two Phase Commit](https://github.com/facebook/rocksdb/wiki/Two-Phase-Commit-Implementation) to implement distributed transactions. Sometimes the prepared transactions cannot be committed right away due to worker failure and later (maybe after worker restart) we restore all prepared transactions and call Rollback or Commit on each of them.
We notice that when 'committed transactions' and 'not-committed transactions' are interleaved, the wal remains unflushed and fragmented, even after the 'not-committed transactions' are re-fetched and rollback.
This case can be reproduced with the following code snippet.

    Options options;
    TransactionDBOptions txn_db_options;
    options.create_if_missing = true;
    TransactionDB* txn_db;
    Status s = TransactionDB::Open(options, txn_db_options, kDBPath, &txn_db);
    assert(s.ok());
  
    WriteOptions write_options;
    TransactionOptions txn_options;

    rocksdb::FlushOptions flush_options;
    for (int idx = 0; idx < 10000000; ++idx) {
      Transaction* txn1 = txn_db->BeginTransaction(write_options, txn_options);
      txn1->SetName(std::to_string(idx));
       
      if (idx % 2 == 0) {
          s = txn1->Put(std::to_string(idx), std::to_string(idx) + "_val");
          assert(s.ok());
          s = txn1->Prepare();
          assert(s.ok());
          s = txn1->Commit();
          assert(s.ok());
          delete txn1;
      } else {
          s = txn1->Put(std::to_string(idx), std::to_string(idx) + "_val");
          assert(s.ok());
          s = txn1->Prepare();
          assert(s.ok());
          // no rollback or commit here
          delete txn1;
      }
    }
    std::vector<rocksdb::Transaction*> recovered_txns;
    txn_db->GetAllPreparedTransactions(&recovered_txns);
    for (auto txn : recovered_txns) {
        auto s = txn->Rollback();
        assert(s.ok());
    }
    s = txn_db->Flush(flush_options);
    assert(s.ok());
    delete txn_db;

After execution of the above code, the log and sst files in the db directory will like this:
-rw-r--r--  1 work work 167399836 Oct 28 21:46 000003.log
-rw-r--r--  1 work work 169585280 Oct 28 21:47 000009.log
-rw-r--r--  1 work work  11683471 Oct 28 21:46 000010.sst
-rw-r--r--  1 work work 169591168 Oct 28 21:47 000011.log
-rw-r--r--  1 work work  11604509 Oct 28 21:47 000012.sst
-rw-r--r--  1 work work 129547058 Oct 28 21:47 000013.log
-rw-r--r--  1 work work  11602768 Oct 28 21:47 000014.sst
-rw-r--r--  1 work work         0 Oct 28 21:47 000015.log

The log files remains undeleted even after db reopened. And we cannot come with a solution to flush and delete the obsolete log files.
Is this an expected behaviour or a bug?

Thanks
Baoxue

**Comment by miasantreble** [comment] 2018-10-29 00:17
cc @maysamyabandeh

**Comment by wolfkdy** [comment] 2018-10-29 04:19
This issue interested me, I did some investigation into the code. And know where the problem is.
Let's discuss base on the code above.
PessimisticTransaction::~PessimisticTransaction didn't write ROLLBACK tag into WAL if current transaction is not committed nor rollbacked.  It just removed the txn by txn_db_impl_->UnregisterTransaction(this);  So that wal-log-writer dare not purge prepare-tag without paired ROLLBACK_TAG or COMMIT_TAG.

So in fact, the code below will wont rollback anything because recovered_txns.size() is 0.
```
std::vector<rocksdb::Transaction*> recovered_txns;
txn_db->GetAllPreparedTransactions(&recovered_txns);
```

However,  this bug or feature can be work around in at least two ways.
1) manually rollback a txn before delete it.
2) before calling GetAllPreparedTransactions, delete txn_db and reinit a new one. In this way, txn_db will first go to recovery mode and collect all preparedTxns.
Just add a few lines so that your code works.
```
    delete txn_db;
    s = TransactionDB::Open(options, txn_db_options, "./txndb", &txn_db);
    assert(s.ok());
    std::vector<rocksdb::Transaction*> recovered_txns;
    txn_db->GetAllPreparedTransactions(&recovered_txns);
    std::cout << recovered_txns.size() << std::endl;
```

But I think rocksdb itself should write necessary tags into WAL in txn's destructor. Or it can not be considered as an elegant-implemented RAII.

**Comment by maysamyabandeh** [comment] 2018-10-29 18:47
1. GetAllPreparedTransactions is to be called after a db restart to recover from a crash. This is already documented: https://github.com/facebook/rocksdb/blob/7fb39f1ae19bf6c88544d485fc7b6940ebad8981/utilities/transactions/pessimistic_transaction_db.h#L110
2. Deleting a txn does not roll it back. At this stage, this is a feature and the behavior is not to be changed.

**Closed** 2018-10-30 21:37 UTC

**Comment by baoxuezhao** [comment] 2018-11-08 05:29
I did another test based on the above comments.
1. start an db instance from an empty directory, insert kv with interleaved Committed and UnCommitted transactions, and then exit the program.

```
void open_new() {
    Options options;
    TransactionDBOptions txn_db_options;
    options.create_if_missing = true;
    TransactionDB* txn_db;
    Status s = TransactionDB::Open(options, txn_db_options, kDBPath, &txn_db);
    assert(s.ok());
    WriteOptions write_options;
    TransactionOptions txn_options;
    rocksdb::FlushOptions flush_options;
    for (int idx = 0; idx < 100000; ++idx) {
      Transaction* txn1 = txn_db->BeginTransaction(write_options, txn_options);
      txn1->SetName(std::to_string(idx));
      if (idx % 2 == 0) {
          s = txn1->Put(std::to_string(idx), std::to_string(idx) + "_val");
          assert(s.ok());
          s = txn1->Prepare();
          assert(s.ok());
          s = txn1->Commit();
          assert(s.ok());
          delete txn1;
      } else {
          s = txn1->Put(std::to_string(idx), std::to_string(idx) + "_val");
          assert(s.ok());
          s = txn1->Prepare();
          assert(s.ok());
          // no rollback or commit here
          delete txn1;
      }
    }
    //delete txn_db;
}
```
To simulate the program crash, the txn_db instance is not deleted at the end of the program.

2. Next I reopen the the database with the same path as above, and call ```GetAllPreparedTransactions```.  
```
void reopen() {
    Options options;
    TransactionDBOptions txn_db_options;
    TransactionDB* txn_db;
    rocksdb::Status s;
    rocksdb::FlushOptions flush_options;
    s = TransactionDB::Open(options, txn_db_options, kDBPath, &txn_db);
    assert(s.ok());
    std::vector<rocksdb::Transaction*> recovered_txns;
    txn_db->GetAllPreparedTransactions(&recovered_txns);
    std::cout << recovered_txns.size() << std::endl;
    for (auto txn : recovered_txns) {
        auto s = txn->Rollback();
        assert(s.ok());
    }
    s = txn_db->Flush(flush_options);
    assert(s.ok());
    delete txn_db;
}
```
The program takes a long time to recover the state, and write some new WAL log. But the WAL file generated in step 1 is still not flushed.
Is there any thing wrong for the above code? @maysamyabandeh 
Thanks

**Comment by maysamyabandeh** [comment] 2018-11-08 18:08
The tests are good starting point but I recommend taking it to the next level and dig in the code via gdb and good-old printf to see what is going on. To see how to test GetAllPreparedTransactions you can also get inspired by existing tests in PersistentTwoPhaseTransactionTest.
PS: Since this no longer qualifies as a bug I recommend reaching out to the rocksdb community https://www.facebook.com/groups/rocksdb.dev where users help each other.
