### ISSUE TITLE
BlobDB leaks file handles on close

### ISSUE THREAD

**Issue by yuslepukhin** [facebook/rocksdb#3501] opened 2018-02-14 18:50 UTC
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
No open handles to blob file is expected and all files are closed after BlobDB is destroyed
### Actual behavior

Set a breakpoint in the Destroy() after the database is destroyed. This is the only thread (main) that is currently running. And then run handle search in the ProcessExplorer.  This will prevent the cleanup both of the files and the containing folder.

We still have 3 file handles open and two of them to the same file. See also the stack and the test failure on windows.

![image](https://user-images.githubusercontent.com/11303988/36221807-2478ef54-1174-11e8-8f0e-7453c86ab23c.png)

![image](https://user-images.githubusercontent.com/11303988/36221884-63621bc8-1174-11e8-8dc3-a88a999aac6f.png)

![image](https://user-images.githubusercontent.com/11303988/36221860-52b367a0-1174-11e8-998d-e0831764fc30.png)

### Steps to reproduce the behavior
Run debug\blob_db_test_je.exe --gtest_filter=BlobDBTest.ReadWhileGC on Windows. Cleanup fails to the open handles. Windows does not allow deleting a file here but it serves well to find a handle leak.

![image](https://user-images.githubusercontent.com/11303988/36221772-02751194-1174-11e8-95aa-c50a99fc628a.png)

**Comment by yuslepukhin** [comment] 2018-02-14 19:04
The file is not closed at this time and thus can not be deleted.

![image](https://user-images.githubusercontent.com/11303988/36222398-007e2ebe-1176-11e8-809c-41d5664a050f.png)

I think the test is actually holding the second handle to blob #2 file but the other two handles are leaked. So the test needs some adjustments as well.

![image](https://user-images.githubusercontent.com/11303988/36222620-bbc5c33a-1176-11e8-9623-a1e9e0893bd0.png)

**Comment by yiwu-arbug** [comment] 2018-02-16 18:52
will check.

**Comment by yiwu-arbug** [comment] 2018-02-20 20:48
The issue is with the test itself. It holds shared_ptr of the file and keep the file open. Will fix.

**Comment by siying** [comment] 2018-03-14 18:40
@yiwu-arbug is it fixed?

**Comment by yiwu-arbug** [comment] 2018-07-12 23:30
@siying not yet.

**Comment by DatongLi** [comment] 2019-01-18 04:07
Is the blob_db ready to use in industry?

**Comment by ltamasi** [comment] 2021-03-25 17:22
Closing since the offending test case got removed in #6278 .

**Closed by ltamasi** 2021-03-25 17:22 UTC
