### ISSUE TITLE
column family support open/close

### ISSUE THREAD

**Issue by ChinaXing** [facebook/rocksdb#6091] opened 2019-11-26 03:45 UTC
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
each column family hold memtable, when we have many column family, we want to idle close them to release some memory, and lazy open when we want to write to them
### Actual behavior
column family must be open at db::open, and can't close on-fly

**Comment by riversand963** [comment] 2019-12-04 00:11
Thanks @ChinaXing for posting. Since this is a feature request for which the issue is not intended, could you move this post to https://www.facebook.com/groups/rocksdb.dev? Thanks.
I will be closing this issue.

**Closed by riversand963** 2019-12-04 00:11 UTC
