### ISSUE TITLE
5.8.0 has a regression error on Windows compared to 5.7.3

### ISSUE THREAD

**Issue by guozhangwang** [facebook/rocksdb#3072] opened 2017-10-26 00:10 UTC
We found an issue running Kafka Streams with rocksDB 5.8.0 on Windows, while 5.7.3 does not have this issue. The summary as well as the proc-dump can be found on the JIRA itself:

https://issues.apache.org/jira/browse/KAFKA-6100

**Comment by guozhangwang** [comment] 2017-10-26 00:11
Seems I cannot tag the labels or release numbers on it, so I'll just ping @siying @sagar0 here.

**Comment by sagar0** [comment] 2017-10-26 00:20
@guozhangwang -- Would you be kind enough to create a reproducible test case for us so that we could isolate it to RocksDB code? Is that on Windows 10 32- or 64-bit? As per https://github.com/facebook/rocksdb/wiki/JNI-Debugging, you should see an error report file generated. It would be great if you could provide that file.

Tagging @adamretter here, who mostly helps us with java (and windows) builds, to see if we can track this down further.

**Comment by sagar0** [comment] 2017-10-27 04:56
Seems like Kafka downgraded RocksDB from 5.8.0 to 5.7.3 due to this issue: https://github.com/apache/kafka/pull/4136 .

**Comment by adamretter** [comment] 2017-10-27 21:08
@sagar0 @guozhangwang I will see if I can use the "MDMP crash report data" file from the Kafka ticket to understand what happened... However the quickest way to resolve this would be to have a small reproducible test case, @guozhangwang can you provide that?

**Comment by adamretter** [comment] 2017-10-30 12:27
I can't seem to get the PDB files from when I build RocksDB to load and work with the provided MDMP report. I am certainly no expert with Visual Studio, so I may be doing something wrong. Perhaps @yuslepukhin has some thoughts?

Otherwise, I think we will need a reproducible test case from @guozhangwang?

**Comment by guozhangwang** [comment] 2017-10-30 15:31
@adamretter Thanks for looking into this. I will try to provide a minimal reproducible test case. But I cannot say for sure when I will get back to you..

**Comment by siying** [comment] 2018-07-12 22:07
@guozhangwang are you still fighting it?

**Comment by guozhangwang** [comment] 2018-07-14 21:22
@siying I've just upgraded to the most recent version (5.14.2) and will check if we still saw the same issue on that version.

**Comment by adamretter** [comment] 2018-12-12 16:13
I am closing this ticket as there has been no updated from @guozhangwang 
Please re-open if you still have the problem with the latest release of RocksJava.

**Closed by adamretter** 2018-12-12 16:13 UTC
Labels: bug, java-api, windows
