### ISSUE TITLE
More than one RocksDB process can access a single database.  fcntl lock released on close.

### ISSUE THREAD

**Issue by thatsafunnyname** [facebook/rocksdb#1780] opened 2017-01-17 23:52 UTC
Hello and thanks for RocksDB,

When a process attempts to open a RocksDB database it already has open, it opens the LOCK file and then closes it, this releases the fcntl lock the first RocksDB instance thought it had, and means that another process can also open the same RocksDB database.

Test code:

```
#include "db/db_test_util.h"
#include "port/stack_trace.h"

namespace { long test_num = -1; }

TEST(RocksDBLocked,ExpectToOpenAndLock) {
  rocksdb::DB* db;
  rocksdb::Options options;
  options.create_if_missing = true;
  rocksdb::Status status = rocksdb::DB::Open(options, "/tmp/testdb", &db);
  if( 0 == test_num ){
    ASSERT_TRUE( status.ok() );
  }
  if ( 2 == test_num ) {
    ASSERT_TRUE( ! status.ok() );
  }
}

TEST(RocksDBLocked,Sleep4s){ usleep( 4 * 1000000 ); }

TEST(RocksDBLocked,ExpectToFailAsLocked) {
  rocksdb::DB* db;
  rocksdb::Options options;
  options.create_if_missing = true;
  rocksdb::Status status = rocksdb::DB::Open(options, "/tmp/testdb", &db);
  ASSERT_TRUE(!status.ok());
}

int main(int argc, char** argv) {
  if( argc > 1 ){ test_num = strtol(argv[1], NULL, 0); }
  printf("test_num = %ld\n", test_num);
  ::testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}
```

Run 2 processes, with 2s staggered start, passing 0 and then 2 as argv[1]:

```
> echo -en "0\n2" | xargs -t -I {} -P 2 bash -c "sleep {} ; ./db_lock_test {} "
bash -c sleep 0 ; ./db_lock_test 0
bash -c sleep 2 ; ./db_lock_test 2
test_num = 0
[==========] Running 3 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 3 tests from RocksDBLocked
[ RUN      ] RocksDBLocked.ExpectToOpenAndLock
[       OK ] RocksDBLocked.ExpectToOpenAndLock (3 ms)
[ RUN      ] RocksDBLocked.Sleep4s
test_num = 2
[==========] Running 3 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 3 tests from RocksDBLocked
[ RUN      ] RocksDBLocked.ExpectToOpenAndLock
[       OK ] RocksDBLocked.ExpectToOpenAndLock (0 ms)
[ RUN      ] RocksDBLocked.Sleep4s
[       OK ] RocksDBLocked.Sleep4s (4000 ms)
[ RUN      ] RocksDBLocked.ExpectToFailAsLocked
[       OK ] RocksDBLocked.ExpectToFailAsLocked (0 ms)
[----------] 3 tests from RocksDBLocked (4003 ms total)

[----------] Global test environment tear-down
[==========] 3 tests from 1 test case ran. (4003 ms total)
[  PASSED  ] 3 tests.
[       OK ] RocksDBLocked.Sleep4s (4001 ms)
[ RUN      ] RocksDBLocked.ExpectToFailAsLocked
db/db_lock_test.cc:26: Failure
Value of: !status.ok()
  Actual: false
Expected: true
[  FAILED  ] RocksDBLocked.ExpectToFailAsLocked (3 ms)
[----------] 3 tests from RocksDBLocked (4004 ms total)

[----------] Global test environment tear-down
[==========] 3 tests from 1 test case ran. (4004 ms total)
[  PASSED  ] 2 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] RocksDBLocked.ExpectToFailAsLocked

 1 FAILED TEST
```

The first process sets the fcntl lock first,
then second process attempts to set the fcntl lock but fcntl correctly returns -1 as it is locked by the first,
then first process opens the file in LockFile ( https://github.com/facebook/rocksdb/blob/master/util/env_posix.cc#L554 ) , but the filename is present in the set of locked files ( https://github.com/facebook/rocksdb/blob/master/util/env_posix.cc#L89 ) and -1 is returned from LockOrUnlock, so the file is closed ( https://github.com/facebook/rocksdb/blob/master/util/env_posix.cc#L560 ) , when the file is closed the posix advisory lock it had is released and this allows the second process to also
open the RocksDB database when we would expect it to be prevented from doing so (because of the lock).

From the man page for fcntl:

       The record locks described above are associated with the process
       (unlike the open file description locks described below).  This has
       some unfortunate consequences:

       *  If a process closes any file descriptor referring to a file, then
          all of the process's locks on that file are released, regardless
          of the file descriptor(s) on which the locks were obtained.  This
          is bad: it means that a process can lose its locks on a file such
          as /etc/passwd or /etc/mtab when for some reason a library
          function decides to open, read, and close the same file.

An strace with timestamps, run at the same time as the bash below it which is capturing the locks for the LOCK file:

```
> echo -en "0\n2" | xargs -t -I {} -P 2 bash -c "sleep {} ; strace -ttt -y -f -e trace=open,close,fcntl ./db_lock_test {} " 2>&1 | grep LOCK
1484694794.734141 open("/tmp/testdb/LOCK", O_RDWR|O_CREAT, 0644) = 5
1484694794.734161 fcntl(5</tmp/testdb/LOCK>, F_SETLK, {type=F_WRLCK, whence=SEEK_SET, start=0, len=0}) = 0
1484694794.734185 fcntl(5</tmp/testdb/LOCK>, F_GETFD) = 0
1484694794.734202 fcntl(5</tmp/testdb/LOCK>, F_SETFD, FD_CLOEXEC) = 0
 
1484694796.734743 open("/tmp/testdb/LOCK", O_RDWR|O_CREAT, 0644) = 5
1484694796.734763 fcntl(5</tmp/testdb/LOCK>, F_SETLK, {type=F_WRLCK, whence=SEEK_SET, start=0, len=0}) = -1 EAGAIN (Resource temporarily unavailable)
1484694796.734809 close(5</tmp/testdb/LOCK>) = 0
 
1484694798.740424 open("/tmp/testdb/LOCK", O_RDWR|O_CREAT, 0644) = 10
1484694798.740453 close(10</tmp/testdb/LOCK>) = 0
 
1484694800.736141 open("/tmp/testdb/LOCK", O_RDWR|O_CREAT, 0644) = 5
1484694800.736160 fcntl(5</tmp/testdb/LOCK>, F_SETLK, {type=F_WRLCK, whence=SEEK_SET, start=0, len=0}) = 0
1484694800.736184 fcntl(5</tmp/testdb/LOCK>, F_GETFD) = 0
1484694800.736201 fcntl(5</tmp/testdb/LOCK>, F_SETFD, FD_CLOEXEC) = 0
 ```

```
> for i in {1..60}; do sleep 0.1;date +%s.%N;grep `ls -i /tmp/testdb/LOCK | awk '{print $1}'` /proc/locks ; done
1484694794.601676035
1484694794.707443348
1484694794.812417016
976: POSIX  ADVISORY  WRITE 194540 fd:19:25167883 0 EOF
1484694794.917349009
976: POSIX  ADVISORY  WRITE 194540 fd:19:25167883 0 EOF
1484694795.022629478
976: POSIX  ADVISORY  WRITE 194540 fd:19:25167883 0 EOF
1484694795.127793504
976: POSIX  ADVISORY  WRITE 194540 fd:19:25167883 0 EOF
1484694795.232797370
976: POSIX  ADVISORY  WRITE 194540 fd:19:25167883 0 EOF
1484694795.337953964
976: POSIX  ADVISORY  WRITE 194540 fd:19:25167883 0 EOF
1484694795.443171801
976: POSIX  ADVISORY  WRITE 194540 fd:19:25167883 0 EOF
1484694795.548403582
976: POSIX  ADVISORY  WRITE 194540 fd:19:25167883 0 EOF
1484694795.653550237
976: POSIX  ADVISORY  WRITE 194540 fd:19:25167883 0 EOF
1484694795.759104030
976: POSIX  ADVISORY  WRITE 194540 fd:19:25167883 0 EOF
1484694795.864437396
976: POSIX  ADVISORY  WRITE 194540 fd:19:25167883 0 EOF
1484694795.969722451
976: POSIX  ADVISORY  WRITE 194540 fd:19:25167883 0 EOF
1484694796.075128729
976: POSIX  ADVISORY  WRITE 194540 fd:19:25167883 0 EOF
1484694796.181272834
976: POSIX  ADVISORY  WRITE 194540 fd:19:25167883 0 EOF
1484694796.287072797
976: POSIX  ADVISORY  WRITE 194540 fd:19:25167883 0 EOF
1484694796.392213267
976: POSIX  ADVISORY  WRITE 194540 fd:19:25167883 0 EOF
1484694796.497987835
976: POSIX  ADVISORY  WRITE 194540 fd:19:25167883 0 EOF
1484694796.603113756
976: POSIX  ADVISORY  WRITE 194540 fd:19:25167883 0 EOF
1484694796.709120783
976: POSIX  ADVISORY  WRITE 194540 fd:19:25167883 0 EOF
1484694796.814712184
976: POSIX  ADVISORY  WRITE 194540 fd:19:25167883 0 EOF
1484694796.920128990
976: POSIX  ADVISORY  WRITE 194540 fd:19:25167883 0 EOF
1484694797.025313364
976: POSIX  ADVISORY  WRITE 194540 fd:19:25167883 0 EOF
1484694797.130242746
976: POSIX  ADVISORY  WRITE 194540 fd:19:25167883 0 EOF
1484694797.235746114
976: POSIX  ADVISORY  WRITE 194540 fd:19:25167883 0 EOF
1484694797.341186226
976: POSIX  ADVISORY  WRITE 194540 fd:19:25167883 0 EOF
1484694797.446314883
976: POSIX  ADVISORY  WRITE 194540 fd:19:25167883 0 EOF
1484694797.551756430
976: POSIX  ADVISORY  WRITE 194540 fd:19:25167883 0 EOF
1484694797.657506503
976: POSIX  ADVISORY  WRITE 194540 fd:19:25167883 0 EOF
1484694797.762840443
976: POSIX  ADVISORY  WRITE 194540 fd:19:25167883 0 EOF
1484694797.868171087
976: POSIX  ADVISORY  WRITE 194540 fd:19:25167883 0 EOF
1484694797.973480076
976: POSIX  ADVISORY  WRITE 194540 fd:19:25167883 0 EOF
1484694798.078596669
976: POSIX  ADVISORY  WRITE 194540 fd:19:25167883 0 EOF
1484694798.183786058
976: POSIX  ADVISORY  WRITE 194540 fd:19:25167883 0 EOF
1484694798.289064968
976: POSIX  ADVISORY  WRITE 194540 fd:19:25167883 0 EOF
1484694798.394004472
976: POSIX  ADVISORY  WRITE 194540 fd:19:25167883 0 EOF
1484694798.499266611
976: POSIX  ADVISORY  WRITE 194540 fd:19:25167883 0 EOF
1484694798.604694566
976: POSIX  ADVISORY  WRITE 194540 fd:19:25167883 0 EOF
1484694798.709896097
976: POSIX  ADVISORY  WRITE 194540 fd:19:25167883 0 EOF
1484694798.815175839
1484694798.920411649
1484694799.025445454
```

I think it should be possible to avoid this by checking if the file to be locked is already in lockedFiles earlier, and avoiding the open and *close* if it is already present.

Thanks.

I am testing on kernel 3.10.0-327.22.2.el7.x86_64 with glibc-2.17-106.el7_2.4, /tmp is xfs.

Xref:
https://github.com/facebook/rocksdb/commit/e56b2c5a31eee7131dd36792a072bf5d40c05e67#diff-5b717965879a622d11268aaf03fb19c8 - "Prevent concurrent multiple opens of leveldb database."

**Comment by thatsafunnyname** [comment] 2017-01-18 10:28
Here is a diff against util/filelock_test.cc that checks the fcntl lock is still held.
It is likely to be not very portable code, it works on linux kernel 3.10.0-229, and should probably have an `#ifdef __linux__` around it.
 
```
> diff -du util/filelock_test.cc.orig util/filelock_test.cc
--- util/filelock_test.cc.orig  2017-01-17 09:12:59.883916621 -0500
+++ util/filelock_test.cc       2017-01-18 05:16:29.292537492 -0500
@@ -6,6 +6,8 @@
 #include "rocksdb/status.h"
 #include "rocksdb/env.h"

+#include <fstream>
+#include <regex>
 #include <vector>
 #include "util/coding.h"
 #include "util/testharness.h"
@@ -33,6 +35,33 @@
   Status UnlockFile(FileLock* db_lock) {
     return env_->UnlockFile(db_lock);
   }
+
+  bool IsFileLocked(){
+    std::regex regex;
+    {
+      struct stat var;
+      if( stat(file_.c_str(),&var) < 0 ) {
+       return false;
+      }
+      ino_t inode = var.st_ino;
+
+      std::ostringstream oss;
+      oss << ".*POSIX +ADVISORY + WRITE +" << getpid() << ".*:" << inode << " +0 +EOF";
+      regex =  std::regex( oss.str() );
+    }
+
+    std::ifstream ifs("/proc/locks", std::ios::in);
+    ifs.exceptions(std::ios::badbit);
+    while (ifs.good() && !ifs.eof()) {
+      std::string line;
+      if (!getline(ifs, line, '\n')) { break; }
+      if ( std::regex_match (line, regex) ) {
+       return true;
+      }
+    }
+    return false;
+  }
+
 };
 LockTest* LockTest::current_;

@@ -43,12 +72,21 @@
   // acquire a lock on a file
   ASSERT_OK(LockFile(&lock1));

+  // check the file is locked
+  ASSERT_TRUE( IsFileLocked() );
+
   // re-acquire the lock on the same file. This should fail.
   ASSERT_TRUE(LockFile(&lock2).IsIOError());

+  // check the file is locked
+  ASSERT_TRUE( IsFileLocked() );
+
   // release the lock
   ASSERT_OK(UnlockFile(lock1));

+  // check the file is not locked
+  ASSERT_TRUE( ! IsFileLocked() );
+
 }

 }  // namespace rocksdb
```

Output from test run showing the lock is not held after the failed attempt to re-acquire the lock on the same file:

```
> ./filelock_test
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from LockTest
[ RUN      ] LockTest.LockBySameThread
util/filelock_test.cc:82: Failure
Value of: IsFileLocked()
  Actual: false
Expected: true
[  FAILED  ] LockTest.LockBySameThread (26 ms)
[----------] 1 test from LockTest (26 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (26 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] LockTest.LockBySameThread

 1 FAILED TEST
```

**Comment by stevelittle** [comment] 2017-01-18 15:02
This problem is due to the way POSIX file locks work.

The GNU docs describe the intended behaviour clearly: https://www.gnu.org/software/libc/manual/html_node/File-Locks.html

"Locks are associated with processes. A process can only have one kind of lock set for each byte of a given file. When any file descriptor for that file is closed by the process, all of the locks that process holds on that file are released, even if the locks were made using other descriptors that remain open. "

Inside env_posix.cc, in LockFile, we first try to open a new file descriptor to the lock file, then check our internal data structure (to find any existing locks within the same thread, see comments at the top of LockOrUnlock)

If the attempt to lock fails (because our process already has a lock) we close our new file descriptor, which closes *all* our locks on that file (as per the docs above: "When *any* file descriptor for that file is closed by the process, *all* of the locks that process holds on that file are released [...]")

I believe the correct fix for this would be to move the checking of the lockedFiles datastructure so that it is performed before we even attempt to open the file.

**Comment by thatsafunnyname** [comment] 2017-01-18 21:31
With this diff
 
```
> diff -du util/env_posix.cc.orig util/env_posix.cc
--- util/env_posix.cc.orig      2017-01-18 15:48:36.275231953 -0500
+++ util/env_posix.cc   2017-01-18 16:06:33.614806851 -0500
@@ -481,6 +481,17 @@
   virtual Status LockFile(const std::string& fname, FileLock** lock) override {
     *lock = nullptr;
     Status result;
+
+    mutex_lockedFiles.Lock();
+    if( lockedFiles.end() != lockedFiles.find(fname) ){
+      mutex_lockedFiles.Unlock();
+      // file is already locked
+      errno = ENOLCK;
+      result = IOError("lock " + fname, errno);
+      return result;
+    }
+    mutex_lockedFiles.Unlock();
+
     int fd;
     {
       IOSTATS_TIMER_GUARD(open_nanos);
```
 
The modified util/filelock_test.cc in https://github.com/facebook/rocksdb/issues/1780#issuecomment-273439675 passes, along with the tests run by "make check", these tests fail in my environment:
 
    ./env_test &>t/log-env_test
    ./rate_limiter_test &>t/log-rate_limiter_test

but they also fail when run (under the same user and on the same filesystem) without the diff above.

I am using RocksDB version 4.11.2

**Comment by thatsafunnyname** [comment] 2017-01-19 09:57
Also tested on https://github.com/thatsafunnyname/rocksdb which I forked from facebook/rocksdb yesterday.  See  https://github.com/thatsafunnyname/rocksdb/commit/92672d3eade1a6422aae6f19800dc17640b1022b

**Comment by thatsafunnyname** [comment] 2017-01-19 14:24
For anyone interested in how the behavior became standardized by the POSIX committee, https://www.samba.org/samba/news/articles/low_point/tale_two_stds_os2.html - **_"First Implementation Past the Post"_** has an explanation for how _"any successful close() call on any file descriptor referencing a file with locks will drop all the locks on that file, even if they were obtained on another, still open, file descriptor."_ came to be the POSIX standard.

**Comment by thatsafunnyname** [comment] 2017-01-19 16:27
https://github.com/thatsafunnyname/rocksdb/blob/50f22b48d7ba40de92f87359abd58cd17e720c41/util/filelock_test.cc for an attempt at a more portable way to check the fcntl lock, using the exit status from a forked process.

**Comment by stevelittle** [comment] 2017-02-02 13:04
Apologies for the delay. I had to wait for approval from my employer to sign the CLA.

I've created a pull request encorporating my fix and @thatsafunnyname 's latest unit test:

https://github.com/facebook/rocksdb/pull/1831

**Comment by thatsafunnyname** [comment] 2017-02-07 18:47
Looking for some feedback on this issue and https://github.com/facebook/rocksdb/pull/1831 , thank you.

**Comment by gfosco** [comment] 2018-01-10 22:57
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.

**Comment by thatsafunnyname** [comment] 2018-01-11 10:49
Still looking for some feedback on this issue and #1831 , thank you.

**Comment by ajkr** [comment] 2018-01-11 19:03
Will take a look, thanks.

**Comment by thatsafunnyname** [comment] 2018-05-17 13:29
Would it be appropriate to remove the "abandoned-or-aged-out" label?
Thanks.

**Closed** 2018-06-14 00:32 UTC
