### ISSUE TITLE
Deploy RocksDB JNI 7.3.1 to maven

### ISSUE THREAD

**Issue by cavallium** [facebook/rocksdb#10150] opened 2022-06-12 10:05 UTC
RocksDB JNI 7.3.1 has not been deployed to maven central

**Comment by adamretter** [comment] 2022-06-12 16:57
I was make aware of the release tag yesterday. I. sure you can understand that it is the weekend. I will start working on this tomorrow

**Comment by cavallium** [comment] 2022-06-12 17:28
Yes, sorry, I just opened the issue

**Comment by ltamasi** [comment] 2022-06-13 19:28
@cavallium A bit of clarification: building and publishing RocksJava packages is a manual process. So if you see a new RocksDB release on GitHub but don't see it on Maven, it doesn't mean that something went wrong; in fact, the release getting tagged on GitHub is a prerequisite for the building the official RocksJava packages.

**Comment by akankshamahajan15** [comment] 2022-06-14 00:02
I will close this task since its not a bug.

**Closed by akankshamahajan15** 2022-06-14 00:02 UTC

**Comment by adamretter** [comment] 2022-06-14 11:49
This has now been released to Maven Central. It should appear in the next 2 hours (their sync window).
