### ISSUE TITLE
Assertion failed: (is_last_reference)

### ISSUE THREAD

**Issue by enothereska** [facebook/rocksdb#2533] opened 2017-07-04 08:10 UTC
Hello,

Using 5.4.5, I keep getting the following error when using the Java JNI:
```
Assertion failed: (is_last_reference), function ~ColumnFamilyData, file db/column_family.cc, line 451.
```

We're opening and closing a store several times in a row. This does not happen with previous versions (at least I've tested with 5.3.6 and 5.0.1). 

Any hints as to what could be the problem?
Thanks
Eno

**Comment by guozhangwang** [comment] 2017-07-06 05:27
@siying @adamretter Is this a blocker for JNI users for 5.4.5? If yes we will skip this release and use 5.3.6 for now. Please advice.

**Comment by adamretter** [comment] 2017-07-08 21:25
@enothereska This is not a known issue. Can you provide us with the minimal code to reproduce please?

**Comment by adamretter** [comment] 2017-07-08 21:26
@enothereska Please also first make sure that you are releasing column families in the correct order as described here: https://github.com/facebook/rocksdb/wiki/RocksJava-Basics#opening-a-database-with-column-families

**Comment by guozhangwang** [comment] 2017-07-10 00:22
We do not create rocksDB with column families.

**Comment by scottfines** [comment] 2017-07-20 19:36
I can reproduce this in 5.4.5 (on Mac OS X) without creating column families. Here is my smallest reproducing case:

```
Charset charset = Charset.forName("UTF-8");
RocksDB.loadLibrary();
final String dataPath = $WORKING_PATH
for(int i=0;i<100;i++) {
	try (DBOptions dbOpts = new DBOptions().setCreateIfMissing(true);
	     Options opts = new Options().setCreateIfMissing(true)) {
		List<byte[]> cfs = RocksDB.listColumnFamilies(opts, dataPath);
		List<ColumnFamilyDescriptor> descriptors = new ArrayList<>(cfs.size()+1);
		descriptors.add(new ColumnFamilyDescriptor("default".getBytes(charset),new ColumnFamilyOptions()));
		cfs.forEach(theBytes -> descriptors.add(new ColumnFamilyDescriptor(theBytes, new ColumnFamilyOptions())));

		List<ColumnFamilyHandle> handles = new ArrayList<>(descriptors.size());
		final RocksDB aOpen = RocksDB.open(dbOpts, dataPath,descriptors,handles);
		System.err.printf("Shutting down(iteration %d)%n",i);
		aOpen.close();
	}
}
```

technically, this produces the following line
```
Assertion failed: (refs_.load(std::memory_order_relaxed) == 0), function ~ColumnFamilyData, file db/column_family.cc, line 419.
```

Perhaps noteworthy, this version does NOT fail:
```
RocksDB.loadLibrary();
final String dataPath = tempFolder.getRoot().getAbsolutePath();
for(int i=0;i<100;i++) {
	try (Options opts = new Options().setCreateIfMissing(true)) {
		final RocksDB aOpen = RocksDB.open(opts, dataPath);
		System.err.printf("Shutting down(iteration %d)%n", i);
		aOpen.close();
	}
}
```

There aren't TOO many changes here, so it shouldn't be very hard to track down. Let me know if you need more, but here's my env. information:

OS: Mac OS X v. 10.12.5 (Sierra)
Java: HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
RocksDB Version: 5.4.5

These little things are quick JUnit tests I put together to verify, so I'd be happy to adjust the tests as useful in order to provide more information.

**Comment by scottfines** [comment] 2017-07-20 20:15
OK, even smaller reproducing case:

```
Charset charset = Charset.forName("UTF-8");
RocksDB.loadLibrary();
final String dataPath = tempFolder.getRoot().getAbsolutePath();
for(int i=0;i<100;i++) {

	try (DBOptions dbOpts = new DBOptions().setCreateIfMissing(true)){
		List<ColumnFamilyDescriptor> descriptors = new ArrayList<>(1);
		descriptors.add(new ColumnFamilyDescriptor("default".getBytes(charset), new ColumnFamilyOptions()));
		List<ColumnFamilyHandle> handles = new ArrayList<>(descriptors.size());
		final RocksDB aOpen = RocksDB.open(dbOpts, dataPath, descriptors, handles);

		System.err.printf("Shutting down(iteration %d)%n", i);
		aOpen.close();
	}
}
```

**Comment by scottfines** [comment] 2017-07-27 19:46
Looks like this is still failing in 5.6.1, but the error message looks marginally different:

```
Assertion failed: (refs_.load(std::memory_order_relaxed) == 0), function ~ColumnFamilyData, file db/column_family.cc, line 425.
```

**Comment by guozhangwang** [comment] 2017-07-27 20:08
Yup, tested 5.5.1 and 5.4.5 and they are also there.

**Comment by guozhangwang** [comment] 2017-07-28 18:28
The interesting thing is, we do not use call specifically any column family functions in our JNI (maybe they get triggered internally somehow). Also the error we saw is slightly different:

```
Assertion failed: (is_last_reference), function ~ColumnFamilyData, file db/column_family.cc, line 458.
```

This issue is currently blocking us, or I believe more generally any JNI users to upgrade to any versions higher than 5.3.6. cc @adamretter @siying

**Comment by siying** [comment] 2017-07-28 23:15
@guozhangwang several questions:
1. did you destroy all the iterators before closing the DB?
2. why is it blocking you? Aren't most of your users using release mode?
Let me take a look at the code too.

**Comment by guozhangwang** [comment] 2017-07-28 23:26
1. Yes.
2. My statement was confusing before: we want to upgrade to newer versions than 5.3.6 in the next release with the new features but can't because of it. So technically it is not "blocking" us now but will be great if in the next release of Kafka we can use the newer versioned rocksdb.

**Comment by siying** [comment] 2017-07-28 23:30
@scottfines for your question, don't you need to call close() to all column family handles in `handles` before closing the DB?

**Comment by siying** [comment] 2017-07-28 23:31
@guozhangwang I want to sure I understand correctly: you never create a column family other than the default one, right?

**Comment by guozhangwang** [comment] 2017-07-28 23:38
Yes. In fact here is all we did with the JNI interface for creating a db (about 20 LOC in total): https://github.com/apache/kafka/blob/c50c941af1395d010160790f0127f06106cc69c8/streams/src/main/java/org/apache/kafka/streams/state/internals/RocksDBStore.java#L121

**Comment by siying** [comment] 2017-07-28 23:43
@guozhangwang any idea you got a full call stack? For example, if you have a core dump you can gdb to it and get it.

**Comment by guozhangwang** [comment] 2017-08-27 00:39
@siying Unfortunately I cannot easily get a core dump as the above issue only happens during unit tests in jenkins builds.

**Comment by guozhangwang** [comment] 2017-10-05 22:47
We have finally got time to dig into this issue and found that the bug is actually ours, RocksDB 5.3.6+ version just add more restriction that exposed the issue.

Closing it for now.

**Closed** 2017-10-11 16:50 UTC
Labels: java-api

**Comment by Coneboy-k** [comment] 2018-01-31 09:12
At Version 5.9.2 also  print 
`Assertion failed: (is_last_reference), function ~ColumnFamilyData, file db/column_family.cc, line 457.`
 
Java info
```
Java version: 1.8.0_73, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home/jre
Default locale: zh_CN, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.6", arch: "x86_64", family: "mac"
```

**Comment by iFA88** [comment] 2020-03-17 15:19
I have the same issue with `rocksdb-6.6.4` when I delete all keys from a CF.
