### ISSUE TITLE
Feature Request: Allowing write to memtable fail

### ISSUE THREAD

**Issue by rockeet** [facebook/rocksdb#4056] opened 2018-06-26 09:24 UTC
### Expected behavior
When write to a memtable, it may failed because reached memory limit, in this failed case, rocksdb should create a new memtable and write to the new memtable.

### Actual behavior
Now rocksdb memtable does not allow write fail, but checks the memtable memory usage and to dicide wheather need to create a new memtable. This mechenism has many defects:

#### 1. Waste memory
For default `SkipList` memtable, maybe the memtable is marked imutable just after it allocated a new arena and inserted few entries: if we set `write_buffer_size` to `1GB`, area size should be `128M`, the last `128M` arena may be wasted.

#### 2. Makes hard effort on third party memtable implementation
We implementead a `PatriciaTrie` based memtable, aimed to faster speed and lower memory usage, we preallocate a large block equals to `write_buffer_size`(e.g. `1GB`), to minimize memory usage, we using 32 bit offset instead of using 64 bit pointer for `PatriciaTrie` nodes, and we implemented copy on write to avoid using mutex lock in multi thread, by this approach, enlarge the memory block is impossible(e.g. doubling realloc the memory block, realloc may invalidate all pointers).

Now our solution is to create a vector of `PatriciaTrie` in one memtable, if the **last** `PatriciaTrie` is full, we add new PatriciaTrie to the vector, new KeyValues are inserted into  new PatriciaTrie, and implement its iterator by `MergingIterator`..... but this is very ugly and greatly kill performance.

**Comment by riversand963** [comment] 2018-06-27 17:02
RocksDB has memory limit for each column family. RocksDB also checks the number of existing memtables (mutable and immutable) of each column family. Upon reaching the limit, write stalls will occur. See [write stall conditions](https://github.com/facebook/rocksdb/blob/master/db/column_family.cc#L716).
If a memtable reaches its limit, I'm not sure if it's a good idea to create a new one since it violates the contract between the application and RocksDB.
We are investigating how to reduce the negative impact of write stalls when RocksDB nears its memory limit.

**Comment by rockeet** [comment] 2018-06-28 03:44
Thank you for your comment!

Let me explain more:

1. user API: memtable changes will never impact rocksdb user API.

2. Write stalls: We don’t concern write stalls, write stalls will always happen on switching memtable, regardless how to decide whether memtable is full.

3. memtable insertion fail: memtable insertion fail will never impact user API. It just impact rocksdb implementation: If memtable full is indicated by insertion fail, both the memory usage and performance will be improved.

**Comment by mdcallag** [comment] 2018-06-28 15:44
PatriciaTrie is interesting. Is this academic research? Something you plan to contribute?

**Comment by riversand963** [comment] 2018-06-28 18:02
Thanks @rockeet , I think you probably misunderstood what I meant by "contract". Sorry about the confusion. By "contract between application and RocksDB", I did not mean the user API. I meant user has specified a certain amount of memory that can be used by RocksDB, and RocksDB currently abides by this contract.
My understanding of your proposal is as follows. You want a memtable write failure caused by reaching memory limit to notify RocksDB to create new memtables. At this point, will you flush the previous immutable memtables? If not, this will violate the memory limit agreed upon by the application and RocksDB previously.
Whether we should dynamically adjust the memory limit seems another issue.

**Comment by rockeet** [comment] 2018-06-28 23:29
Our real requirement is: If write to a memtable fail, rocksdb should not write to this memtable again, and it should retry write this key value into a new memtable.

all other things are implementation details, such as:
1. if rocksdb mem usage is under limit, a new memtable will be created at once.
2. if it reaches the total mem limit at this time(before creating a new memtable), it should wait until there are sufficient memory(maybe memory was freed by a memtable flush, or some DB cache was evicted, and so on ...)

**Comment by rockeet** [comment] 2018-06-28 23:34
@mdcallag Yes, we will contibute our memtable once it is stable. Now this issue is a blocker for us.

**Comment by riversand963** [comment] 2018-06-29 21:54
@rockeet , Thanks for clarification of "reaching memory limit".
Have you take a look at `WriteCallback` passed to `WriteImpl`? Is it possible to implement your feature here? This callback will be called before writing to the memtables, maybe you can check whether the current memtable is full.

**Comment by riversand963** [comment] 2018-07-06 16:42
HI @rockeet , I'd like to touch base with you on this topic. Will `WriteCallback` be able to provide a solution? Thanks

**Comment by rockeet** [comment] 2018-07-07 06:14
We are investigating your proposal, it is very complex, we need time understand the writing process

**Comment by rockeet** [comment] 2018-07-27 08:00
@riversand963 Very sad, after a long time fail and retry, we give up, and continue using our workaround.

Thanks for your help.

**Comment by riversand963** [comment] 2018-08-09 17:18
@rockeet Thanks for keeping up updated. I'll be closing this issue for now. Feel free to reopen it once you have made any progress on this.

**Closed by riversand963** 2018-08-09 17:18 UTC
