### ISSUE TITLE
FlushJobInfo contains wrong smallest and largest sequence number

### ISSUE THREAD

**Issue by fuatbasik** [facebook/rocksdb#11568] opened 2023-06-27 16:03 UTC
### Expected behavior
When OnFlushBegin is called, FlushJobInfo should contain smallest and largest sequence numbers as  described here: https://javadoc.io/static/org.rocksdb/rocksdbjni/8.0.0/org/rocksdb/FlushJobInfo.html

### Actual behavior
Smallest sequence number equals to constant value of LargestSequenceNumber and largest sequence number is always 0, when delivered as a part of OnFlushBegin 

```
Testing started at 16:19 ...
/db/listener_test.cc:902: Failure
Expected: (flush_job_info.smallest_seqno) <= (latest_seq_number_), actual: 72057594037927935 vs 1
/db/listener_test.cc:902: Failure
Expected: (flush_job_info.smallest_seqno) <= (latest_seq_number_), actual: 72057594037927935 vs 3
/db/listener_test.cc:902: Failure
Expected: (flush_job_info.smallest_seqno) <= (latest_seq_number_), actual: 72057594037927935 vs 5
/db/listener_test.cc:902: Failure
Expected: (flush_job_info.smallest_seqno) <= (latest_seq_number_), actual: 72057594037927935 vs 7
/db/listener_test.cc:902: Failure
Expected: (flush_job_info.smallest_seqno) <= (latest_seq_number_), actual: 72057594037927935 vs 9
/db/listener_test.cc:902: Failure
Expected: (flush_job_info.smallest_seqno) <= (latest_seq_number_), actual: 72057594037927935 vs 11
/db/listener_test.cc:902: Failure
Expected: (flush_job_info.smallest_seqno) <= (latest_seq_number_), actual: 72057594037927935 vs 13
/db/listener_test.cc:902: Failure
Expected: (flush_job_info.smallest_seqno) <= (latest_seq_number_), actual: 72057594037927935 vs 15
/db/listener_test.cc:902: Failure
Expected: (flush_job_info.smallest_seqno) <= (latest_seq_number_), actual: 72057594037927935 vs 17
/db/listener_test.cc:902: Failure
Expected: (flush_job_info.smallest_seqno) <= (latest_seq_number_), actual: 72057594037927935 vs 19
```

### Steps to reproduce the behavior

A simple way to reproduce this behaviour is to override OnFlushBegin function on `MemTableSealedListener` of listener_test.cc

example: 

```
 public:
  MemTableSealedListener() {}
  void OnMemTableSealed(const MemTableInfo& info) override {
    latest_seq_number_ = info.first_seqno;
  }

  void OnFlushBegin(DB* /*db*/,
                        const FlushJobInfo& flush_job_info) override {
    ASSERT_LE(flush_job_info.smallest_seqno, latest_seq_number_);
  }

  void OnFlushCompleted(DB* /*db*/,
                        const FlushJobInfo& flush_job_info) override {
    ASSERT_LE(flush_job_info.smallest_seqno, latest_seq_number_);
  }
};

TEST_F(EventListenerTest, MemTableSealedListenerTest) {
  auto listener = std::make_shared<MemTableSealedListener>();
  Options options;
  options.env = CurrentOptions().env;
  options.create_if_missing = true;
  options.listeners.push_back(listener);
  DestroyAndReopen(options);

  for (unsigned int i = 0; i < 10; i++) {
    std::string tag = std::to_string(i);
    ASSERT_OK(Put("foo" + tag, "aaa"));
    ASSERT_OK(Put("bar" + tag, "bbb"));

    ASSERT_OK(Flush());
  }
}
```
This is because NotifyOnFlushBegin is called after PickMemtable() function of the FlushJob, and it constructs the FlushJobInfo from FileMetadata. However, these fields on FileMetadata are set only after BuildTable() of the FlushJob is called. 
A potential solution might be to set these fields at the end of PickMemtable(). Please see flush_job.cc (lines 202-204)
```
// path 0 for level 0 file.
  meta_.fd = FileDescriptor(versions_->NewFileNumber(), 0, 0);
  meta_.epoch_number = cfd_->NewEpochNumber();
```

As a follow up question: should I expect OnFlushBegin and OnFlushEnd should have the same smallest and largest sequence numbers when they are called as a part of the same flush job?

**Comment by fuatbasik** [comment] 2023-06-29 13:21
I actually found that it is not a random value. It is the max sequence number: 
```
static const SequenceNumber kMaxSequenceNumber = ((0x1ull << 56) - 1);
```

**Comment by cbi42** [comment] 2023-06-30 18:02
Hi - thanks for reporting. I think this is expected. Since `smallest_seqno` and `largest_seqno` are for the flush output file, they are not known at the beginning of a flush.

**Comment by fuatbasik** [comment] 2023-07-04 10:26
Hi Changyu,
Thanks a lot for your response. It does make sense that those wouldn’t be known until the flush does some work. Should we update the documentation to ensure this is reflected there?

- https://javadoc.io/doc/org.rocksdb/rocksdbjni/latest/org/rocksdb/EventListener.html#onFlushBegin-org.rocksdb.RocksDB-org.rocksdb.FlushJobInfo-
- https://javadoc.io/static/org.rocksdb/rocksdbjni/8.3.2/org/rocksdb/FlushJobInfo.html

Is there any other documentation to update?

**Comment by cbi42** [comment] 2023-07-07 18:12
> Hi Changyu, Thanks a lot for your response. It does make sense that those wouldn’t be known until the flush does some work. Should we update the documentation to ensure this is reflected there?
> 
> * https://javadoc.io/doc/org.rocksdb/rocksdbjni/latest/org/rocksdb/EventListener.html#onFlushBegin-org.rocksdb.RocksDB-org.rocksdb.FlushJobInfo-
> * https://javadoc.io/static/org.rocksdb/rocksdbjni/8.3.2/org/rocksdb/FlushJobInfo.html
> 
> Is there any other documentation to update?

Not sure how JAVA doc is updated, but for C++ comment we can add some clarification here: https://github.com/facebook/rocksdb/blob/df082c8d1ddf5a90b195941064b56e853f104ff0/include/rocksdb/listener.h#L348-L351.

**Comment by hx235** [comment] 2023-12-14 23:09
Since it's expected behavior that we don't know the seqno on flush begin, I'm going to close this PR. @cbi42 Thanks for working on this!

**Closed by hx235** 2023-12-14 23:09 UTC
Labels: waiting
