### ISSUE TITLE
RocksDB failed to build (Release/x64) on Windows due to the warning C4189: 'dummy_last_ref': local variable is initialized but not referenced 

### ISSUE THREAD

**Issue by shanshan0309** [facebook/rocksdb#3407] opened 2018-01-25 08:02 UTC
I tried to build RocksDB with VS2017 Update 2 on Windows. It failed to build due to warning C4189: 'dummy_last_ref': local variable is initialized but not referenced. This issue is caused by mater revision [d46e832](https://github.com/facebook/rocksdb/commit/d46e832e9478c18c5002ee2225e9ada0403fa1a4). Could you please help take a look at this? Thanks!

### Expected behavior
build successfully
### Actual behavior
"D:\RocksDB\build_x64\rocksdb.sln" (Rebuild target) (1) ->
       "D:\RocksDB\build_x64\cache_bench.vcxproj.metaproj" (Rebuild target) (4) ->
       "D:\RocksDB\build_x64\rocksdb.vcxproj.metaproj" (Rebuild target) (6) ->
       "D:\RocksDB\build_x64\rocksdb.vcxproj" (Rebuild target) (26) ->
       (ClCompile target) -> 
         d:\rocksdb\src\db\column_family.cc(1067): warning C4189: 'dummy_last_ref': local variable is initialized but not referenced [D:\RocksDB\build_x64\rocksdb.vcxproj]
         d:\rocksdb\src\db\column_family.cc(1063): warning C4189: 'last_ref': local variable is initialized but not referenced [D:\RocksDB\build_x64\rocksdb.vcxproj]

       "D:\RocksDB\build_x64\rocksdb.sln" (Rebuild target) (1) ->
       "D:\RocksDB\build_x64\rocksdb-shared.vcxproj.metaproj" (Rebuild target) (17) ->
       "D:\RocksDB\build_x64\rocksdb-shared.vcxproj" (Rebuild target) (25) ->
         d:\rocksdb\src\db\column_family.cc(1067): warning C4189: 'dummy_last_ref': local variable is initialized but not referenced [D:\RocksDB\build_x64\rocksdb-shared.vcxproj]
         d:\rocksdb\src\db\column_family.cc(1063): warning C4189: 'last_ref': local variable is initialized but not referenced [D:\RocksDB\build_x64\rocksdb-shared.vcxproj]

       "D:\RocksDB\build_x64\rocksdb.sln" (Rebuild target) (1) ->
       "D:\RocksDB\build_x64\cache_bench.vcxproj.metaproj" (Rebuild target) (4) ->
       "D:\RocksDB\build_x64\rocksdb.vcxproj.metaproj" (Rebuild target) (6) ->
       "D:\RocksDB\build_x64\rocksdb.vcxproj" (Rebuild target) (26) ->
       (ClCompile target) -> 
         d:\rocksdb\src\db\column_family.cc(1067): error C2220: warning treated as error - no 'object' file generated [D:\RocksDB\build_x64\rocksdb.vcxproj]

       "D:\RocksDB\build_x64\rocksdb.sln" (Rebuild target) (1) ->
       "D:\RocksDB\build_x64\rocksdb-shared.vcxproj.metaproj" (Rebuild target) (17) ->
       "D:\RocksDB\build_x64\rocksdb-shared.vcxproj" (Rebuild target) (25) ->
         d:\rocksdb\src\db\column_family.cc(1067): error C2220: warning treated as error - no 'object' file generated [D:\RocksDB\build_x64\rocksdb-shared.vcxproj]

### Steps to reproduce the behavior
1.Open VS2017 x64 Native tools command tool
2.git clone https://github.com/facebook/rocksdb D:\RocksDB\src
3.cd D:\RocksDB
4.mkdir build_x64 && pushd build_x64
5.cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_SYSTEM_VERSION=10.0.15063.0 ..\src
6.msbuild build_x64\rocksdb.sln /p:Configuration=Release;Platform=x64 /t:Rebuild /m /p:BuildInParallel=true

**Comment by maysamyabandeh** [comment] 2018-01-25 16:42
Is VS 15 a supported platform? We test against 14: 
> - cmake -G "Visual Studio 14 Win64" -DOPTDBG=1 -DWITH_XPRESS=1 -DPORTABLE=1 ..

https://github.com/facebook/rocksdb/blob/master/appveyor.yml

**Comment by shanshan0309** [comment] 2018-01-26 01:44
@maysamyabandeh, thanks for looking into this issue. I tried to build RocksDB on VS 2017 with the master previous revision before d46e832. It works well. However, when build RocksDB with the master revision d46e832, it failed due to the warnning C4189.

**Comment by siying** [comment] 2018-01-26 01:52
I am not aware of anyone successfully building with Visual studio 2017 (maybe @yuslepukhin ever gave it a try but I never managed to do it). I am using VS2017 now but I'm still following CMakeList.txt (https://github.com/facebook/rocksdb/blob/master/CMakeLists.txt#L17) to configure it using VS2015 and open it in VS2017 as compatible mode.
You are more than welcome to contribute the code and make RocksDB build on VS2017.

**Comment by siying** [comment] 2018-01-26 01:55
Oh wait, if the problem is https://github.com/facebook/rocksdb/commit/d46e832e9478c18c5002ee2225e9ada0403fa1a4, then it should work if you add `#include "port/port.h"` in db/column_family.cc. Can you give it a try and see whether it works?

**Comment by shanshan0309** [comment] 2018-01-26 02:56
@siying, thanks for your suggestion. But when I added  #include "port/port.h" in db/column_family.cc, it still failed due to the warning C4189.

**Comment by adamretter** [comment] 2018-01-26 10:35
@maysamyabandeh Yes, VS 2015 is the supported platform. That is what I use for producing the RocksJava builds.

**Comment by maysamyabandeh** [comment] 2018-01-26 15:14
Thanks @adamretter. Then how come we test against VS 14. Are they fully compatible? i.e., if it works on 14 it works on 15 too?

**Comment by siying** [comment] 2018-01-26 18:11
@shanshan0309 does it fail on the same line?

**Comment by siying** [comment] 2018-01-26 18:13
@maysamyabandeh VS2015 is VS14, and VS2017 is VS15.

I'm not sure whether they are fully backward compatible. At least in this case, it has more strict default warnings than previous version. Maybe they can be turned off though.

**Comment by gfosco** [comment] 2018-01-26 18:58
Confirming that VS 2017 has worked recently and now fails:

```
column_family.cc(1067): error C2220: warning treated as error - no 'object' file generate
d [rocksdb.vcxproj]
column_family.cc(1067): warning C4189: 'dummy_last_ref': local variable is initialized bu
t not referenced [rocksdb.vcxproj]
column_family.cc(1063): warning C4189: 'last_ref': local variable is initialized but not
referenced [rocksdb.vcxproj]
```

Will look at fixing this asap.

**Comment by maysamyabandeh** [comment] 2018-01-26 19:02
@gfosco if we are going to be compatible with VS 2017, should update our tests to compile against it?

**Comment by adamretter** [comment] 2018-01-26 19:04
@maysamyabandeh I can't comment on how compatible they are, I am by no means a Windows expert. All I know is that VS 2015 works well and we have been using it for RocksJava for some time now.

**Comment by gfosco** [comment] 2018-01-26 19:29
I suspect newer users would default to VS2017 (as I did).. Lets at least consider updating to 2017 or adding 2017 to testing.

Do I have this right: assert() is not used when NDEBUG=1, and since the assert is the only reference to dummy_last_ref, it hits C4189?

**Comment by siying** [comment] 2018-01-26 19:32
@gfosco my understanding is (maybe wrong), VS doesn't support syntax `__attribute__()`, so in Windows we defined it away:

https://github.com/facebook/rocksdb/blob/master/port/win/port_win.h#L63-L64

But this is not included in `column_family.cc`.

**Comment by siying** [comment] 2018-01-26 19:39
@gfosco perhaps I was wrong. The warning message was for the issue that we tried to avoid with ` __attribute__((__unused__))`. Now I'm confused. Are we getting warning everywhere, or just column_family.cc?

**Comment by gfosco** [comment] 2018-01-26 21:55
@siying looks like only in column_family.cc, 1063 & 1067.

**Comment by gfosco** [comment] 2018-01-26 22:43
Skipping the initialization and putting the Unref inside the assert fixes it, but I assume there's a reason why it's done that way..

```c++
//bool last_ref __attribute__((__unused__)) = cfd->Unref();
assert(cfd->Unref());
```

**Comment by siying** [comment] 2018-01-26 22:48
@gfosco but we can't do that. In release build, `cfd->Unref()` will be optimized out.

**Comment by shanshan0309** [comment] 2018-01-29 06:01
@siying, it fails on the same line(1063&1067 in column_family.cc).

**Comment by shanshan0309** [comment] 2018-01-31 01:26
Hi, Any update for this?

**Comment by gfosco** [comment] 2018-01-31 01:30
#3425 is still in review.  Did you apply this change?

**Comment by shanshan0309** [comment] 2018-01-31 01:47
@gfosco. Yes, I applied your change(#3425) and it works well. If your review need to some time, I'll applied a patch which you provided to work around this issue. 
Thank you very much!

**Comment by gfosco** [comment] 2018-02-01 01:09
#3425 landed so this should be cleared up.

**Closed by gfosco** 2018-02-01 01:09 UTC

**Comment by shanshan0309** [comment] 2018-02-01 06:14
@gfosco, Thank you so much for fixing this issue. I've verified your fix works well.
