### ISSUE TITLE
[FeatureRequest] BlobDB support DBWithTTL

### ISSUE THREAD

**Issue by leon-db** [facebook/rocksdb#8933] opened 2021-09-18 07:00 UTC
Currently, the TTL use compaction filter to delete old invalid data except blobdb.  When the TTL can use it on blobdb?

```c++
  virtual Decision FilterV2(int level, const Slice& key, ValueType value_type,
                            const Slice& existing_value, std::string* new_value,
                            std::string* skip_until) const {
      switch (value_type) {
          case ValueType::kValue: {
              bool value_changed = false;
              bool rv = Filter(level, key, existing_value, new_value, &value_changed);
              if (rv) {
                 return Decision::kRemove;
              }
              return value_changed ? Decision::kChangeValue : Decision::kKeep;
          }
          case ValueType::kMergeOperand: {
              bool rv = FilterMergeOperand(level, key, existing_value);
              return rv ? Decision::kRemove : Decision::kKeep;
          }
          // DBWithTTL override it's own Filter to invalid stale date values 
          case ValueType::kBlobIndex: {
             return Decision::kKeep;
          }
      }
  }
```

And the DBWithTTL just work for normal values. More details show in the code snip above.

**Comment by ltamasi** [comment] 2021-09-20 16:12
@leon-db Could you clarify what the issue is? The legacy BlobDB has its own TTL support; as for the integrated implementation, I would expect TtlDB to work out of the box since BlobDB reads the blob values and passes them to the compaction filter with a value type of `kValue` (i.e. as a "regular" value). In other words, `TtlCompactionFilter` would never see a blob index.

**Comment by leon-db** [comment] 2021-09-21 03:45
I think all logical details you mentioned in function `CompactionIterator::InvokeFilterIfNeeded`, right? @Itamasi 
Thanks.

**Comment by ltamasi** [comment] 2021-09-21 16:45
@leon-db As a quick test, I hacked `ttl_test` so it sets `enable_blob_files` and `enable_blob_files_garbage_collection` to `true` and it completed successfully. Closing this for now, please feel free to reopen/comment if you run into issues.

**Closed by ltamasi** 2021-09-21 16:45 UTC
Labels: feature-request
