### ISSUE TITLE
Compilation fails with "undefined reference to `rocksdb::db_stress_tool"

### ISSUE THREAD

**Issue by anatol** [facebook/rocksdb#6345] opened 2020-01-29 20:16 UTC
I am trying to build version 6.6.3 at ArchLinux using following instructions

```
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib \
    -DWITH_BZ2=ON -DWITH_LZ4=ON -DWITH_SNAPPY=ON -DWITH_ZLIB=ON -DWITH_ZSTD=ON \
    -DUSE_RTTI=ON -DWITH_JEMALLOC=ON -DWITH_TESTS=OFF -DFAIL_ON_WARNINGS=OFF -DPORTABLE=ON \
    -S . -B build
cmake --build build
```

And it fails to link dues to following error:

```
Scanning dependencies of target db_stress
Scanning dependencies of target hash_table_bench
Scanning dependencies of target ldb
Scanning dependencies of target write_stress
[ 81%] Building CXX object tools/CMakeFiles/db_stress.dir/db_stress.cc.o
[ 82%] Building CXX object CMakeFiles/hash_table_bench.dir/utilities/persistent_cache/hash_table_bench.cc.o
[ 82%] Building CXX object tools/CMakeFiles/write_stress.dir/write_stress.cc.o
[ 82%] Building CXX object tools/CMakeFiles/ldb.dir/ldb.cc.o
Scanning dependencies of target table_reader_bench
[ 82%] Building CXX object CMakeFiles/table_reader_bench.dir/table/table_reader_bench.cc.o
[ 83%] Linking CXX executable db_stress
/usr/bin/ld: CMakeFiles/db_stress.dir/db_stress.cc.o: in function `main':
db_stress.cc:(.text.startup+0x2): undefined reference to `rocksdb::db_stress_tool(int, char**)'
collect2: error: ld returned 1 exit status
make[2]: *** [tools/CMakeFiles/db_stress.dir/build.make:92: tools/db_stress] Error 1
make[1]: *** [CMakeFiles/Makefile2:545: tools/CMakeFiles/db_stress.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 84%] Building CXX object CMakeFiles/rocksdb.dir/utilities/blob_db/blob_compaction_filter.cc.o
[ 84%] Linking CXX executable ldb
[ 84%] Built target ldb
[ 84%] Building CXX object CMakeFiles/rocksdb.dir/utilities/blob_db/blob_db.cc.o
[ 84%] Linking CXX executable hash_table_bench
[ 84%] Building CXX object CMakeFiles/rocksdb.dir/utilities/blob_db/blob_db_impl.cc.o
[ 84%] Built target hash_table_bench
[ 84%] Building CXX object CMakeFiles/rocksdb.dir/utilities/blob_db/blob_db_impl_filesnapshot.cc.o
[ 84%] Building CXX object CMakeFiles/rocksdb.dir/utilities/blob_db/blob_dump_tool.cc.o
[ 85%] Linking CXX executable write_stress
```

It seems `db_stress.cc` misses the link dependency.

**Comment by anatol** [comment] 2020-02-08 00:57
I am able to reproduce the problem at `v6.6.4` tag but not on `master`.

`db_stress_tool` function is defined in `tools/db_stress_tool.cc` but `tools/CMakeLists.txt` does not reference `tools/db_stress_tool.cc`:

```cmake
set(TOOLS
  sst_dump.cc
  db_sanity_test.cc
  db_stress.cc
  write_stress.cc
  ldb.cc
  db_repl_stress.cc
  dump/rocksdb_dump.cc
  dump/rocksdb_undump.cc)
foreach(src ${TOOLS})
  get_filename_component(exename ${src} NAME_WE)
  add_executable(${exename}${ARTIFACT_SUFFIX}
    ${src})
  target_link_libraries(${exename}${ARTIFACT_SUFFIX} ${LIBS})
  list(APPEND tool_deps ${exename})
endforeach()
add_custom_target(tools
  DEPENDS ${tool_deps})
add_custom_target(ldb_tests
  COMMAND python ${CMAKE_CURRENT_SOURCE_DIR}/ldb_tests.py
  DEPENDS ldb)
```

Hence the link error.

**Comment by tomgreenwood1** [comment] 2020-04-14 08:19
Is there a fix for this? I am hitting this error when trying to compile rocksdb as per these instructions

```apt-get install build-essential libsnappy-dev zlib1g-dev libbz2-dev libgflags-dev liblz4-dev
git clone https://github.com/facebook/rocksdb.git
cd rocksdb
mkdir build && cd build
cmake ..
make
cd ..
export CPLUS_INCLUDE_PATH=${CPLUS_INCLUDE_PATH}${CPLUS_INCLUDE_PATH:+:}`pwd`/include/
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}${LD_LIBRARY_PATH:+:}`pwd`/build/
export LIBRARY_PATH=${LIBRARY_PATH}${LIBRARY_PATH:+:}`pwd`/build/```

on ubuntu

**Comment by bariscicek** [comment] 2020-05-02 23:20
@tomgreenwood1 you can just remove `add_subdirectory(db_stress_tool)` line from CMakeLists.txt at L1232.

**Comment by tomgreenwood1** [comment] 2020-05-06 15:17
thanks @bariscicek I will try that.

**Comment by akankshamahajan15** [comment] 2021-03-26 02:20
Assuming the issue is fixed by removing ```add_subdirectory(db_stress_tool)```, closing the issue for now. Kindly reopen the ticket, in case issue exists.

**Closed by akankshamahajan15** 2021-03-26 02:20 UTC
