### ISSUE TITLE
Unable to build with llvm/clang 11

### ISSUE THREAD

**Issue by adamretter** [facebook/rocksdb#7736] opened 2020-12-02 17:43 UTC
From the `HEAD` of the `master` branch on Ubuntu 16.04 (Xenial) for both x86_64 and ppc64le with `clang version 11.0.0 (https://github.com/llvm/llvm-project.git 176249bd6732a8044d457092ed932768724a6f06)`:

Running the command:
```
PATH=/opt/llvm-11/bin:$PATH CC=/opt/llvm-11/bin/clang CXX=/opt/llvm-11/bin/clang++ AR=/opt/llvm-11/bin/llvm-ar AS=/opt/llvm-11/bin/llvm-as LDFLAGS="-fuse-ld=lld" LIBRARY_PATH="/usr/local/lib" ASSERT_STATUS_CHECKED=1 DEBUG_LEVEL=2 make -j8 db_write_test
```

Or the command:
```
CC=/opt/llvm-11/bin/clang CXX=/opt/llvm-11/bin/clang++ LIBRARY_PATH="/usr/local/lib" ASSERT_STATUS_CHECKED=1 DEBUG_LEVEL=2 make -j8 db_write_test
```

Ultimately results in the error:

```
...
CCLD     db_write_test
ld.lld: error: undefined symbol: operator delete(void*, std::align_val_t)
>>> referenced by lru_cache.h:197 (./cache/lru_cache.h:197)
>>>               lru_cache.o:(rocksdb::LRUCacheShard::~LRUCacheShard()) in archive ./librocksdb_debug.a
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:1559: recipe for target 'db_write_test' failed
make: *** [db_write_test] Error 1
```

Compiling with `gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609` instead works just fine.

**Comment by adamretter** [comment] 2020-12-04 18:53
Looking at https://en.cppreference.com/w/cpp/memory/new/operator_delete it appears that:
```
void operator delete  ( void* ptr, std::align_val_t al ) noexcept;
```

May be a C++17 language feature. However, AFAIK, RocksDB is C++14

**Comment by jay-zhuang** [comment] 2020-12-11 00:21
Try `ROCKSDB_DISABLE_ALIGNED_NEW=1`
https://github.com/facebook/rocksdb/blob/6cacb0d3a146604a432a06847234b78db096e198/.circleci/config.yml#L209

**Comment by mrambacher** [comment] 2021-04-13 00:54
@adamretter  Do you still this issue?  I could not reproduce it on my Ubuntu box using make or cmake.  I did not build cmake-11, but used the installer.

**Comment by jay-zhuang** [comment] 2021-04-14 03:46
Closing it for now, please feel free to reopen.

**Closed by jay-zhuang** 2021-04-14 03:46 UTC
