### ISSUE TITLE
SIGSEV error during iterator from java jni

### ISSUE THREAD

**Issue by uniqueZt** [facebook/rocksdb#9306] opened 2021-12-17 08:52 UTC
version 6.15.2 、6.25.3  

we run our server about every 4 days，this happens once

Stack: [0x00007fd7883af000,0x00007fd7884b0000],  sp=0x00007fd7884ade78,  free space=1019k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libc.so.6+0x16ac20]  __memcmp_sse4_1+0xcc0
C  [librocksdbjni9263870174473033234.so+0x587ff2]  rocksdb::BlockBasedTableIterator::CheckDataBlockWithinUpperBound()+0x92
C  [librocksdbjni9263870174473033234.so+0x588277]  rocksdb::BlockBasedTableIterator::InitDataBlock()+0x267
C  [librocksdbjni9263870174473033234.so+0x588d28]  rocksdb::BlockBasedTableIterator::FindBlockForward()+0x348
C  [librocksdbjni9263870174473033234.so+0x589155]  rocksdb::BlockBasedTableIterator::Next()+0xf5
C  [librocksdbjni9263870174473033234.so+0x5891d6]  rocksdb::BlockBasedTableIterator::NextAndGetResult(rocksdb::IterateResult*)+0x16
C  [librocksdbjni9263870174473033234.so+0x474371]
C  [librocksdbjni9263870174473033234.so+0x5e1a38]  rocksdb::MergingIterator::Next()+0x38
C  [librocksdbjni9263870174473033234.so+0x5ddb13]  rocksdb::MergingIterator::NextAndGetResult(rocksdb::IterateResult*)+0x13
C  [librocksdbjni9263870174473033234.so+0x3cbb74]  rocksdb::DBIter::Next()+0x284
J 11268  org.rocksdb.RocksIterator.next0(J)V (0 bytes) @ 0x00007fedcc4e80f3 [0x00007fedcc4e8040+0x00000000000000b3]

**Comment by jay-zhuang** [comment] 2021-12-18 01:05
@uniqueZt can you provide more information on how to reproduce the problem?

**Comment by uniqueZt** [comment] 2021-12-20 03:02
@jay-zhuang  sorry，its happen have not regularity，i use it by code below.


`byte[] startKey = RocksUtils.toByteArray(id, 0);
    byte[] endKey = RocksUtils.toByteArray(id, Long.MAX_VALUE);

    final ReadOptions readOptions = new ReadOptions().setIterateUpperBound(new Slice(endKey));
    try {
      mRocksStoreLock.readLock().lock();
      try (RocksIterator iter = db().newIterator(mBlockLocationsColumn.get(), readOptions)) {
        iter.seek(startKey);
        List<BlockLocation> locations = new ArrayList<>();
        for (; iter.isValid(); iter.next()) {
          try {
            locations.add(BlockLocation.parseFrom(iter.value()));
          } catch (Exception e) {
            throw new RuntimeException(e);
          }
        }
        return locations;
      }
    }finally {
      mRocksStoreLock.readLock().unlock();
    }
`

**Comment by uniqueZt** [comment] 2021-12-20 03:09
i use two rocksdb to store different data，i don‘t know whether they  are interacted on each other.

**Comment by uniqueZt** [comment] 2021-12-28 07:37
have we any progress here?

**Comment by riversand963** [comment] 2021-12-30 04:37
Is this a duplicate of https://groups.google.com/g/rocksdb/c/PwapmWwyBbc?

**Comment by uniqueZt** [comment] 2021-12-30 09:48
@riversand963  yeah，we encounter the same problem on production environment，but always have no progress.

**Comment by uniqueZt** [comment] 2021-12-30 10:00
i find a scene：i close the rocksdb in a thread during iterator running .the iterator can running continue without any exception . but when i reopen the rocksdb in another thread, iterator must trigger the sigsev error.

**Comment by riversand963** [comment] 2021-12-31 01:20
@uniqueZt according to https://github.com/facebook/rocksdb/blob/main/include/rocksdb/db.h#L718:L723.
```
// Caller should delete the iterator when it is no longer needed.
// The returned iterator should be deleted before this db is deleted.
```

How do you close the db? I am not familiar with RocksJava, but in db/db_impl/db_impl.cc
```
DBImpl::~DBImpl() {
  InstrumentedMutexLock closing_lock_guard(&closing_mutex_);
  if (!closed_) {
    closed_ = true;
    closing_status_ = CloseHelper();
    closing_status_.PermitUncheckedError();
  }
}

Status DBImpl::Close() {
  InstrumentedMutexLock closing_lock_guard(&closing_mutex_);
  if (closed_) {
    return closing_status_;
  }
  {
    InstrumentedMutexLock l(&mutex_);
    // If there is unreleased snapshot, fail the close call
    if (!snapshots_.empty()) {
      return Status::Aborted("Cannot close DB with unreleased snapshot.");
    }
  }
  closing_status_ = CloseImpl();
  closed_ = true;
  return closing_status_;
}
```

The above comment seems to mean that you need to free the iterator before calling `Close()`.

**Closed** 2022-04-22 04:08 UTC
Labels: java-api, waiting, up-for-grabs
