### ISSUE TITLE
Compile error in release version

### ISSUE THREAD

**Issue by willkozheng** [facebook/rocksdb#5866] opened 2019-09-30 01:36 UTC
cmake  -DCMAKE_BUILD_TYPE=release .
gcc version 9.2.0 (GCC) 

 make VERBOSE=1

[ 30%] Building CXX object CMakeFiles/testutillib.dir/db/db_test_util.cc.o
/opt/gcc/bin/g++  -DGFLAGS=1 -DHAVE_PCLMUL -DHAVE_SSE42 -DLZ4 -DOS_LINUX -DROCKSDB_FALLOCATE_PRESENT -DROCKSDB_LIB_IO_POSIX -DROCKSDB_MALLOC_USABLE_SIZE -DROCKSDB_NO_DYNAMIC_EXTENSION -DROCKSDB_PLATFORM_POSIX -DROCKSDB_PTHREAD_ADAPTIVE_MUTEX -DROCKSDB_RANGESYNC_PRESENT -DROCKSDB_SCHED_GETCPU_PRESENT -DROCKSDB_SUPPORT_THREAD_LOCAL -DSNAPPY -DZLIB -DZSTD -Igflags/include -Irocksdb -Irocksdb/include -Irocksdb/third-party/folly -isystem rocksdb/third-party/gtest-1.8.1/fused-src  -W -Wextra -Wall -Wsign-compare -Wshadow -Wno-unused-parameter -Wno-unused-variable -Woverloaded-virtual -Wnon-virtual-dtor -Wno-missing-field-initializers -Wno-strict-aliasing -std=c++11 -fno-omit-frame-pointer -momit-leaf-frame-pointer -march=native -Werror -fno-builtin-memcmp -O3 -DNDEBUG -fno-rtti   -o CMakeFiles/testutillib.dir/db/db_test_util.cc.o -c rocksdb/db/db_test_util.cc
rocksdb/db/db_test_util.cc: In destructor ‘virtual rocksdb::DBTestBase::~DBTestBase()’:
rocksdb/db/db_test_util.cc:95:12: error: ‘rocksdb::SyncPoint’ has not been declared
   95 |   rocksdb::SyncPoint::GetInstance()->DisableProcessing();
      |            ^~~~~~~~~
rocksdb/db/db_test_util.cc:96:12: error: ‘rocksdb::SyncPoint’ has not been declared
   96 |   rocksdb::SyncPoint::GetInstance()->LoadDependency({});
      |            ^~~~~~~~~
rocksdb/db/db_test_util.cc:97:12: error: ‘rocksdb::SyncPoint’ has not been declared
   97 |   rocksdb::SyncPoint::GetInstance()->ClearAllCallBacks();
      |            ^~~~~~~~~
rocksdb/db/db_test_util.cc: In member function ‘rocksdb::Options rocksdb::DBTestBase::GetOptions(int, const rocksdb::Options&, const rocksdb::anon::OptionsOverride&) const’:
rocksdb/db/db_test_util.cc:345:12: error: ‘rocksdb::SyncPoint’ has not been declared
  345 |   rocksdb::SyncPoint::GetInstance()->ClearCallBack(
      |            ^~~~~~~~~
rocksdb/db/db_test_util.cc:347:12: error: ‘rocksdb::SyncPoint’ has not been declared
  347 |   rocksdb::SyncPoint::GetInstance()->ClearCallBack("NewWritableFile:O_DIRECT");
      |            ^~~~~~~~~
rocksdb/db/db_test_util.cc:405:18: error: ‘rocksdb::SyncPoint’ has not been declared
  405 |         rocksdb::SyncPoint::GetInstance()->SetCallBack(
      |                  ^~~~~~~~~
rocksdb/db/db_test_util.cc:410:18: error: ‘rocksdb::SyncPoint’ has not been declared
  410 |         rocksdb::SyncPoint::GetInstance()->SetCallBack(
      |                  ^~~~~~~~~
rocksdb/db/db_test_util.cc:415:18: error: ‘rocksdb::SyncPoint’ has not been declared
  415 |         rocksdb::SyncPoint::GetInstance()->EnableProcessing();
      |                  ^~~~~~~~~
rocksdb/db/db_test_util.cc: In member function ‘void rocksdb::DBTestBase::MoveFilesToLevel(int, int)’:
rocksdb/db/db_test_util.cc:1125:17: error: ‘class rocksdb::DBImpl’ has no member named ‘TEST_CompactRange’; did you mean ‘CompactRange’?
 1125 |       dbfull()->TEST_CompactRange(l, nullptr, nullptr, handles_[cf]);
      |                 ^~~~~~~~~~~~~~~~~
      |                 CompactRange
rocksdb/db/db_test_util.cc:1127:17: error: ‘class rocksdb::DBImpl’ has no member named ‘TEST_CompactRange’; did you mean ‘CompactRange’?
 1127 |       dbfull()->TEST_CompactRange(l, nullptr, nullptr);
      |                 ^~~~~~~~~~~~~~~~~
      |                 CompactRange
rocksdb/db/db_test_util.cc: In member function ‘void rocksdb::DBTestBase::DumpFileCounts(const char*)’:
rocksdb/db/db_test_util.cc:1136:21: error: ‘class rocksdb::DBImpl’ has no member named ‘TEST_MaxNextLevelOverlappingBytes’
 1136 |           dbfull()->TEST_MaxNextLevelOverlappingBytes());
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rocksdb/db/db_test_util.cc: In member function ‘void rocksdb::DBTestBase::GenerateNewFile(int, rocksdb::Random*, int*, bool)’:
rocksdb/db/db_test_util.cc:1178:15: error: ‘class rocksdb::DBImpl’ has no member named ‘TEST_WaitForFlushMemTable’; did you mean ‘WaitForFlushMemTable’?
 1178 |     dbfull()->TEST_WaitForFlushMemTable();
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~
      |               WaitForFlushMemTable
rocksdb/db/db_test_util.cc:1179:15: error: ‘class rocksdb::DBImpl’ has no member named ‘TEST_WaitForCompact’
 1179 |     dbfull()->TEST_WaitForCompact();
      |               ^~~~~~~~~~~~~~~~~~~
rocksdb/db/db_test_util.cc: In member function ‘void rocksdb::DBTestBase::GenerateNewFile(rocksdb::Random*, int*, bool)’:
rocksdb/db/db_test_util.cc:1190:15: error: ‘class rocksdb::DBImpl’ has no member named ‘TEST_WaitForFlushMemTable’; did you mean ‘WaitForFlushMemTable’?
 1190 |     dbfull()->TEST_WaitForFlushMemTable();
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~
      |               WaitForFlushMemTable
rocksdb/db/db_test_util.cc:1191:15: error: ‘class rocksdb::DBImpl’ has no member named ‘TEST_WaitForCompact’
 1191 |     dbfull()->TEST_WaitForCompact();
      |               ^~~~~~~~~~~~~~~~~~~
rocksdb/db/db_test_util.cc: In member function ‘void rocksdb::DBTestBase::GenerateNewRandomFile(rocksdb::Random*, bool)’:
rocksdb/db/db_test_util.cc:1203:15: error: ‘class rocksdb::DBImpl’ has no member named ‘TEST_WaitForFlushMemTable’; did you mean ‘WaitForFlushMemTable’?
 1203 |     dbfull()->TEST_WaitForFlushMemTable();
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~
      |               WaitForFlushMemTable
rocksdb/db/db_test_util.cc:1204:15: error: ‘class rocksdb::DBImpl’ has no member named ‘TEST_WaitForCompact’
 1204 |     dbfull()->TEST_WaitForCompact();
      |               ^~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/testutillib.dir/db/db_test_util.cc.o] Error 1
make[2]: Leaving directory `rocksdb'
make[1]: *** [CMakeFiles/testutillib.dir/all] Error 2
make[1]: Leaving directory `rocksdb'
make: *** [all] Error 2

**Comment by siying** [comment] 2019-10-01 18:36
This usually means that you had a previous DEBUG build and you started a release build before doing a cleaning. Please try to run "make clean" before running make.

**Comment by siying** [comment] 2019-10-01 18:38
I don't think RocksDB's tests are buildable in release build. Can you try to exclude tests from your build?

**Comment by wouterbeek** [comment] 2019-10-12 11:15
This may be a duplicate of #2445 .

Configuring the build with `cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_TESTS=OFF` fixes the issue.

Arguably option `WITH_TESTS` should be `OFF` by default in release mode.

**Comment by tchaikov** [comment] 2019-10-14 06:09
@siying this issue should be addressed by #5916

**Comment by akankshamahajan15** [comment] 2021-03-26 02:31
Closing this issue as it's a duplicate of above mentioned issue.

**Closed by akankshamahajan15** 2021-03-26 02:31 UTC
