### ISSUE TITLE
Performance issue with get() after concatenating merge()

### ISSUE THREAD

**Issue by StephanEwen** [facebook/rocksdb#1988] opened 2017-03-14 12:46 UTC
We are experiencing a performance problem associated with `get()` after `merge()`, where merge is appending (`StringAppendOperator`).

In our use case, we have potentially many values merged to the same key. When merging a significant amount of values (multiple thousand) to the same key, the `get()` performance drops a lot:

Merging (appending) 50k values of 72 bytes to one key:
  - `merge()` time: about 50 ms
  - `get()` time: about 20 seconds

The test was written against the Java API bridge, but because the `get()` is a single call into the native code, I assume this is not related to the Java bridge. 
The total size of the result value is 3.6 MB, which seems not crazy large. My first guess is that there are many independent allocations and memcopy operations made, which makes the performance drop.

Below is the example code. We also pass a result array, so would in theory be a sufficiently large result buffer already (assuming the Java Bridge reserves an equally large result buffer in the JNI code).

The environment was a simple laptop, with RocksDB created on a tmpfs in memory.

**Setup**
  - Linux x64 (Ubuntu 14.04 LTS)
  - RocksDB version *4.11.2*.
  - RocksDB versions *4.13.5* and *5.1.2* actually encounter errors during this test.

```java
final Options options = new Options()
		.setCreateIfMissing(true)
		.setMergeOperator(new StringAppendOperator())
		.setCompactionStyle(CompactionStyle.LEVEL)
		.setLevelCompactionDynamicLevelBytes(true)
		.setIncreaseParallelism(4)
		.setUseFsync(false)
		.setMaxOpenFiles(-1)
		.setAllowOsBuffer(true)
		.setDisableDataSync(true);

final WriteOptions write_options = new WriteOptions()
		.setSync(false)
		.setDisableWAL(true);

final RocksDB rocksDB = RocksDB.open(options, rocksDir.getAbsolutePath());
final String key = "key";
final String value = "abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ7890654321";

final byte[] keyBytes = key.getBytes(StandardCharsets.UTF_8);
final byte[] valueBytes = value.getBytes(StandardCharsets.UTF_8);
final int num = 50000;

System.out.println("begin insert");

final long beginInsert = System.nanoTime();
for (int i = 0; i < num; i++) {
	rocksDB.merge(write_options, keyBytes, valueBytes);
}
final long endInsert = System.nanoTime();
System.out.println("end insert - duration: " + ((endInsert - beginInsert) / 1_000_000) + " ms");

final byte[] resultHolder = new byte[num * (valueBytes.length + 2)];

final long beginGet = System.nanoTime();
int pos = rocksDB.get(keyBytes, resultHolder);
final long endGet = System.nanoTime();

System.out.println("end get - duration: " + ((endGet - beginGet) / 1_000_000) + " ms");
```
Result:
```
begin insert
end insert - duration: 62 ms
end get - duration: 20137 ms
```

**Comment by StephanEwen** [comment] 2017-03-15 13:17
If someone could confirm that this is a valid issue, we would be up for contributing a patch for this.

**Comment by StephanEwen** [comment] 2017-03-15 17:55
It is also affecting merges. Calling `compactRange()` before `get()` means that the compaction takes about 20s and then the `get()` call is very fast.

**Comment by siying** [comment] 2017-03-16 02:25
I'm surprised that you can use StringAppendOperator in RocksJava. It is not user facing merge operator in C++ library. If we implement partial merge in StringAppendOperator, this can be much faster. If some keys are merged too many times even before flush, an option max_successive_merges can balance the merge and read-modify-write case, to avoid the worst-case read performance.

**Comment by StephanEwen** [comment] 2017-03-16 12:27
If I see it correctly, the `StringAppendOperator` is the only merge operator that is by default part of the RocksDB Java API.

Do I understand you correctly that you suggest we could fix that by implementing a new merge operator that makes use of `PartialMergeMulti`? I saw that there is now also a function `FullMergeV2`, which seems to have a similar signature as `PartialMergeMulti`. Which one would you recommend to implement?

**Comment by StephanEwen** [comment] 2017-03-20 15:01
Bump.
Would be great if someone could give us a few pointers for this:
  - Between implementing `FullMergeV2` and `PartialMergeMulti`, which should be implemented (both?).
  - There is already the `StringAppendTESTOperator` which implements the `FullMergeV2` and `PartialMergeMulti` for string appends, but it explicitly states that this should only be used in tests (not in production). What are the downsides of that implementation?

**Comment by siying** [comment] 2017-03-20 15:53
@StephanEwen  both of FullMergeV2 and PartialMergeMulti should be implemented if the worst case read performance is a concern.

**Comment by koldat** [comment] 2017-04-13 15:59
@StephanEwen did you try to use max_successive_merges as @siying recommended? I was facing similar issue when I had counter value that was changed a lot of times. I see it as works as designed, just change configuration.

**Comment by adamretter** [comment] 2017-04-13 18:39
The `StringAppendOperator` in Java is just a simple wrapper around the C++ `StringAppendOperator` which is created by calling `rocksdb::MergeOperators::CreateFromStringId("stringappend")`, which ultimately calls `return std::make_shared<StringAppendOperator>(',')`.

The C++ hierarchy looks like: `StringAppendOperator` <- `AssociateMergeOperator` <- `MergeOperator`.

If you want a more performant version of `StringAppendOperator`, you could change the existing implementation (or create a new one) which implements `MergeOperator::FullMergeV2` and `MergeOperator::PartialMergeMulti` instead. The ability to work with multiple merge operands can you the facility to implement the same logic with less allocations and less loops.

**Comment by StephanEwen** [comment] 2017-04-19 14:08
We have started using internally a modified version of RocksDB where we use an implementation for appending like that of the `StringAppendTESTOperator`. Seems to work very well.

We could contribute that back, but in essence it is really just making the `StringAppendTESTOperator` something that sound less "unofficial" and exposing it in the Java API.

We built that on RocksDB 4.11.2, because the newer releases could not execute the `merge()` function in the Java API (SIG_ABORT). We have not tried it with the latest master, though.

**Comment by adamretter** [comment] 2017-04-20 13:07
What seems to be the problem with `merge()` after RocksDB 4.11.2. We have a test suite for merge operators: `java/src/test/java/org/rocksdb/MergeTest.java` which seems to call `merge` and succeed without `SIG_ABORT`

**Comment by StefanRRichter** [comment] 2017-04-20 13:10
@adamretter, for example executing the code that @StephanEwen provided in the opening post of this issues does not work for me with RocksDB > 4.11.2.

**Comment by min-mwei** [comment] 2017-05-09 22:02
Hi, guys. I think I found the crash issue by some luck. I did validate it on Mac and Linux by using the original test used in this thread.

**Comment by StephanEwen** [comment] 2017-05-10 09:03
Awesome. I think with the latest master running again, we can contribute back the patch.
We are currently in the mid of our own release, but would happily do it once we are done (2 weeks or so).

**Closed** 2017-05-11 13:22 UTC
Labels: java-api

**Comment by GalRogozinski** [comment] 2018-11-04 13:01
Hey @StephanEwen,
Did you contribute back?
In RocksJava I still only see the old `StringAppendOperator`...
