### ISSUE TITLE
How to use ldb with all columns famillies?

### ISSUE THREAD

**Issue by ytrezq** [facebook/rocksdb#8005] opened 2021-02-26 16:24 UTC
How to use ldb to dump the database with all columns famillies it contains and not just the default column?

This is a follow up of #300.

**Comment by anand1976** [comment] 2021-03-01 23:48
Have you tried the ```---column_family``` option? There's also a command ```list_column_families``` to list the ones in the DB.

**Comment by ytrezq** [comment] 2021-03-02 05:41
@anand1976 this only allows to use 1 column fammily at a time. This can t be used for dumping the whole database.

**Comment by riversand963** [comment] 2021-12-30 05:57
Can the ask be satisfied by a script? First, list all existing column families. Second, for each of the column families, dump the data.

I prefer not introducing more unnecessary complexity to ldb itself, and offload some more functionality to other layers.

Finally, I am closing this one because we use issues mainly for bug report.

**Closed by riversand963** 2021-12-30 05:57 UTC
Labels: enhancement, up-for-grabs

**Comment by ytrezq** [comment] 2021-12-30 07:56
@riversand963 I tried this and it drop the data linked to multiplie columns. Please reopen!

**Comment by riversand963** [comment] 2021-12-30 17:15
On main branch, commit a931bacf5.
```
$make db_stress
$./db_stress -column_families=3 -ops_per_thread=100
$cd /tmp/rocksdbtest-148062/dbstress
$ldb --db=. list_column_families
$ldb --db=. --column_family=default --hex dump > default.dump
$ldb --db=. --column_family=1 --hex dump > 1.dump
$ldb --db=. --column_family=2 --hex dump > 2.dump
$ls -lh *.dump
```
Output of the last command
```
-rw-r--r-- 1 yanqin users 34K Dec 30 09:08 1.dump
-rw-r--r-- 1 yanqin users 35K Dec 30 09:08 2.dump
-rw-r--r-- 1 yanqin users 35K Dec 30 09:08 default.dump
```

Repeat
```
$ldb --db=. --column_family=default --hex dump > default.dump
$ldb --db=. --column_family=1 --hex dump > 1.dump
$ldb --db=. --column_family=2 --hex dump > 2.dump
$ls -lh *.dump
```
Output of the last `ls`
```
-rw-r--r-- 1 yanqin users 34K Dec 30 09:14 1.dump
-rw-r--r-- 1 yanqin users 35K Dec 30 09:14 2.dump
-rw-r--r-- 1 yanqin users 35K Dec 30 09:14 default.dump
```
Result shows that no data is dropped. Can you elaborate on "it drop the data linked to multiplie columns"? Please share evidence of data being dropped with the following info.
1. version and/or commit hash
2. commands to reproduce

**Comment by ytrezq** [comment] 2021-12-30 21:45
@riversand963 then maybe the issue is while putting the dumps back into the a database format. In my case, it happenned on a 6Tib large database so that the dumps were too large to be loaded. Anyway the rebuilt database was shrunk by almost 40% of it s entries.

> On main branch, commit [a931bac](https://github.com/facebook/rocksdb/commit/a931bacf5d1ac118235e818f217c7cc936e84660).
> 
> ```
> $make db_stress
> $./db_stress -column_families=3 -ops_per_thread=100
> $cd /tmp/rocksdbtest-148062/dbstress
> $ldb --db=. list_column_families
> $ldb --db=. --column_family=default --hex dump > default.dump
> $ldb --db=. --column_family=1 --hex dump > 1.dump
> $ldb --db=. --column_family=2 --hex dump > 2.dump
> $ls -lh *.dump
> ```
> 
> Output of the last command
> 
> ```
> -rw-r--r-- 1 yanqin users 34K Dec 30 09:08 1.dump
> -rw-r--r-- 1 yanqin users 35K Dec 30 09:08 2.dump
> -rw-r--r-- 1 yanqin users 35K Dec 30 09:08 default.dump
> ```
> 
> Repeat
> 
> ```
> $ldb --db=. --column_family=default --hex dump > default.dump
> $ldb --db=. --column_family=1 --hex dump > 1.dump
> $ldb --db=. --column_family=2 --hex dump > 2.dump
> $ls -lh *.dump
> ```
> 
> Output of the last `ls`
> 
> ```
> -rw-r--r-- 1 yanqin users 34K Dec 30 09:14 1.dump
> -rw-r--r-- 1 yanqin users 35K Dec 30 09:14 2.dump
> -rw-r--r-- 1 yanqin users 35K Dec 30 09:14 default.dump
> ```
> 
> Result shows that no data is dropped. Can you elaborate on "it drop the data linked to multiplie columns"? Please share evidence of data being dropped with the following info.
> 
> 1. version and/or commit hash
> 2. commands to reproduce step-by-step

**Comment by riversand963** [comment] 2021-12-30 23:21
Tried again.
```
cd /tmp/rocksdbtest-148062 && mkdir dbstress_load && cd dbstress_load
cat ../dbstress/default.dump | ldb --db=. --column_family=default --hex load --disable_wal --create_if_missing
ldb --db=. create_column_family --db=. 1
ldb --db=. create_column_family --db=. 2
cat ../dbstress/1.dump | ldb --db=. --column_family=1 --hex load --disable_wal --create_if_missing
cat ../dbstress/2.dump | ldb --db=. --column_family=2 --hex load --disable_wal --create_if_missing
```
Then dump from the new db.
```
ldb --db=. --hex --column_family=default dump
ldb --db=. --hex --column_family=1 dump
ldb --db=. --hex --column_family=2 dump
```
I don't find data loss.

> 6Tib large database

I will not reproduce with such large data. Actually I doubt whether anybody here will actually debug this issue with such large data set about which little is known. It is the original issue opener's responsibility to reduce the problem to a tractable size for others to continue investigation.

Did the dump from such large data set actually succeed? Same question for the loading.

> Anyway the rebuilt database was shrunk by almost 40% of it s entries.

Did you actually observe keys are missing in the new db but can be found in the original db? Reduction in size is expected. I don't know the command you used to dump the db. My best guess is that you used `ldb dump` which dumps the most recent version for each key in sorted order. By loading these back to another db, size reduction is expected, especially if the original db contains multiple versions and tombstones for keys.

Also, how many times did this happen? If this happened multiple times, maybe it's possible to repro with smaller data size.

**Comment by ytrezq** [comment] 2021-12-31 01:21
@riversand963 the issue can be reproduced with any up to date openethereum full archival node.

Yes , both dump and restoring suceeded minus a single key in column 3 which was corrupt in database and fixed by hand in the dump.
But when restored, openethereum complainned about a lot of entries missing in the recovered database which indeed cousin t be found in the new database using ldb and could be found in the old one.

**Comment by riversand963** [comment] 2021-12-31 01:42
@ytrezq Not considering the data size, can you share the commands you used? If so, I can reopen the issue.

**Comment by riversand963** [comment] 2022-01-04 18:06
This seems a duplicate of https://github.com/facebook/rocksdb/issues/8052.
In neither of these two issues, there have been sufficient information including but not limited to RocksDB version.

As pointed out https://github.com/facebook/rocksdb/issues/8052#issuecomment-804427657, older versions of ldb may seemingly succeed, but the errors have been ignored.
