### ISSUE TITLE
SIGSEGV when deleting db files before closing

### ISSUE THREAD

**Issue by jontejj** [facebook/rocksdb#4445] opened 2018-10-03 06:37 UTC
### Expected behavior
An exception that indicates missing files of some sort?
### Actual behavior
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fac6f1dd391, pid=12934, tid=0x00007fac74916700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_171-b11) (build 1.8.0_171-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.171-b11 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [librocksdbjni2925015662150287824.so+0x375391]  rocksdb::DBImpl::DeleteObsoleteFileImpl(int, std::string const&, std::string const&, rocksdb::FileType, unsigned long)+0x51
#
# Core dump written....
```
### Steps to reproduce the behavior
```
    @Test
    public void testAccessingADbAfterRestart() throws Exception {
        Path path = Paths.get(name.getMethodName());
        RocksStore<String, Integer> first = createDb(path);
        first.put("hello", 42);
        first.close();
        RocksStore<String, Integer> second = createDb(path);
        assertThat(second.get("hello")).isEqualTo(42);
        //second.close(); without this line the test crashes about half of the times
        FileUtils.deleteSubTree(path);
    }
```

Note that RocksStore is actually using a ColumnFamilyHandle to write/read values. TransactionDB is use d with default options.

**Comment by yiwu-arbug** [comment] 2018-10-10 23:15
@jontejj Is this duplicate of #4461 ?

**Comment by jontejj** [comment] 2018-10-11 04:54
The segfault seemed to occur in several different locations. So I reported it for each occurrence. So I still think it's useful? But maybe just marking it as a duplicate and being careful when solving the other one to also think about this code path.

**Comment by adamretter** [comment] 2018-10-11 06:13
@jontejj without the full stack trace it is impossible for us to even guess what is happening. However I suspect a similar issue to that which I suggested in - https://github.com/facebook/rocksdb/issues/4461

**Closed** 2021-04-26 11:19 UTC
Labels: java-api
