### ISSUE TITLE
Native memory leak through JNI after upgrading to 7.0.4

### ISSUE THREAD

**Issue by jojochuang** [facebook/rocksdb#9962] opened 2022-05-06 21:40 UTC
Hello, we are the developers for Apache Ozone (https://ozone.apache.org/), which is a distributed object store. Our namespace manager, the Ozone Manager relies on RocksDB internally for keeping track the key name space. We recently updated RocksDB from 6.20.3 to 7.0.4 (https://github.com/apache/ozone/pull/3199) to address the memory corruption https://github.com/facebook/rocksdb/issues/8617

However, following the update, the memory utilization quickly grew and the process crashed in 2 hours after injecting some workloads.

### Expected behavior
Application memory utilization should stay roughly the same over time.

### Actual behavior
Running a workload for our application (Apache Ozone), memory utilization gradually grows over time and in about 2 hours it grew over 100GB, exceeding physical memory capacity, starting to swap and eventually crashed.

Here's a screenshot from the monitoring system (Cloudera Manager)
<img width="1487" alt="om rocksdb crash" src="https://user-images.githubusercontent.com/2691807/167219028-7d310dde-e6ab-48a8-ae21-ca83e62dad30.png">

We also tried with the latest release RocksDB 7.2.2. No luck. So assuming this issue is still unreported, unfixed. Thus the Issue.

### Steps to reproduce the behavior
Given the number of moving parts (it's a distributed storage system, after all), it's not easy to scale-down the environment to give a crisp reproduction steps.

But we're looking for advice to finding out (instrumentation?) the culprit of the memory leak. I'll follow up with more findings.

**Comment by riversand963** [comment] 2022-05-06 21:45
Can you provide a heap profile and show where the memory goes to?

**Comment by jojochuang** [comment] 2022-05-06 21:48
Interestingly, the Java heap dump was quite small, around 1-2GB in size. So something is going on within the native memory space.
We're trying to get core dump, but it's more than 100GB in size.

**Comment by jojochuang** [comment] 2022-05-07 03:23
Managed to create heap profile using jemalloc
https://drive.google.com/file/d/1nrXYXm5GVW-t0-pA_neN3C626JOxh1OG/view?usp=sharing

as well as the pdf report.
[om_rocksdb_leak.pdf](https://github.com/facebook/rocksdb/files/8644362/om_rocksdb_leak.pdf)

[root@ve0306 tmp]# jeprof --show_bytes /usr/java/jdk1.8.0_232-cloudera/bin/java jeprof.18198.311.i311.heap
Using local file /usr/java/jdk1.8.0_232-cloudera/bin/java.
Using local file jeprof.18198.311.i311.heap.
top
Welcome to jeprof!  For help, type 'help'.
(jeprof) Total: 108075023898 B
89818694600  83.1%  83.1% 89818694600  83.1% rocksdb::UncompressBlockContentsForCompressionType
7627094473   7.1%  90.2% 7639415617   7.1% rocksdb::Arena::AllocateNewBlock
3824396883   3.5%  93.7% 3824396883   3.5% rocksdb::NewArenaWrappedDbIterator
2307192457   2.1%  95.8% 4527130413   4.2% rocksdb::BlockBasedTable::NewIterator
2219937955   2.1%  97.9% 2219937955   2.1% rocksdb::Block::NewIndexIterator
533002818   0.5%  98.4% 600134270   0.6% rocksdb::LRUCacheShard::Insert@2d4220
452467528   0.4%  98.8% 90270883239  83.5% rocksdb::BlockBasedTable::PrefixExtractorChanged
285658188   0.3%  99.1% 285658188   0.3% std::_Rb_tree::_M_insert_unique
235811316   0.2%  99.3% 235811316   0.2% Java_org_rocksdb_ReadOptions_newReadOptions__
172905072   0.2%  99.4% 172905072   0.2% rocksdb::Cleanable::RegisterCleanup

**Comment by jojochuang** [comment] 2022-05-07 03:56
This is the heap profile with RocksDB 6.20.3
https://drive.google.com/file/d/1lgUdGjlReoB47HyTfxbr2X7sw69vYpgT/view?usp=sharing

and pdf report
[om_rocksdb_noleak.pdf](https://github.com/facebook/rocksdb/files/8644415/om_rocksdb_noleak.pdf)

[root@ve0305 tmp]# jeprof --show_bytes /usr/java/jdk1.8.0_232-cloudera/bin/java jeprof.153724.9.i9.heap
Using local file /usr/java/jdk1.8.0_232-cloudera/bin/java.
Using local file jeprof.153724.9.i9.heap.
Welcome to jeprof!  For help, type 'help'.
(jeprof) top
Total: 384593129 B
205324881  53.4%  53.4% 205324881  53.4% prof_backtrace_impl
72176489  18.8%  72.2% 156479612  40.7% rocksdb::BlockFetcher::ReadBlockContents
63331602  16.5%  88.6% 63331602  16.5% rocksdb::UncompressBlockContentsForCompressionType
20971520   5.5%  94.1% 20971520   5.5% rocksdb::FilePrefetchBuffer::Prefetch
 7092358   1.8%  95.9%  7092358   1.8% rocksdb::Arena::AllocateNewBlock
 3670016   1.0%  96.9%  3670016   1.0% rocksdb::port::cacheline_aligned_alloc
 3301831   0.9%  97.7%  3301831   0.9% std::string::_Rep::_S_create
 1572873   0.4%  98.1%  1572873   0.4% init
 1544734   0.4%  98.5%  1676319   0.4% readCEN
 1310780   0.3%  98.9%  1310780   0.3% rocksdb::WritableFileWriter::Append

**Comment by jojochuang** [comment] 2022-05-07 04:22
This is reproducible with the first RocksDB 7 (7.0.3) but not with the last RocksDB 6 (6.29.5). Something’s changed in between.

There are more than a hundred commits in between the releases. Hard to tell what change caused it.

**Comment by andrew-ld** [comment] 2022-05-07 15:50
ping @cavallium, we are also having memory problems with the latest rocksdb release.

**Comment by cavallium** [comment] 2022-05-07 16:30
> ping @cavallium, we are also having the same memory problems on another product that uses rocksdb.

The top leaks that I found with heaptrack are:

- 18.6GB (26.8%) leaked in rocksdb::UncompressBlockContentsForCompressionType(rocksdb::UncompressionInfo const&, char const*, unsigned long, rocksdb::BlockContents*, unsigned int, rocksdb::ImmutableOptions const&, rocksdb::MemoryAllocator*) in librocksdbjni13233355335049142912.so and below.
- 12.4GB (17.9%) leaked in rocksdb::BlockFetcher::ReadBlockContents() in librocksdbjni13233355335049142912.so and below.
- 5.0GB (7.2%) leaked in rocksdb::BlockFetcher::ReadBlockContents() in librocksdbjni13233355335049142912.so and below.
- 4.0GB (5.69%) leaked in rocksdb::UncompressBlockContentsForCompressionType(rocksdb::UncompressionInfo const&, char const*, unsigned long, rocksdb::BlockContents*, unsigned int, rocksdb::ImmutableOptions const&, rocksdb::MemoryAllocator*) in librocksdbjni13233355335049142912.so and below.
- 2.4GB (3.52%) leaked in rocksdb::UncompressBlockContentsForCompressionType(rocksdb::UncompressionInfo const&, char const*, unsigned long, rocksdb::BlockContents*, unsigned int, rocksdb::ImmutableOptions const&, rocksdb::MemoryAllocator*) in librocksdbjni13233355335049142912.so and below.

I'm using rocksdbjni 7.1.2

**Comment by cavallium** [comment] 2022-05-08 18:42
This bug is quite severe, this should be fixed as soon as possible. I can't keep the database open for more than 6 hours with 256GB of ram and 100GB of swap

**Comment by riversand963** [comment] 2022-05-08 23:57
Thanks all for reporting and investigating!

@jojochuang I cannot use `jeprof` to open the heap profile because some dependencies are missing on my machine, thus I am looking at the pdf you provided.
Do the arrows represent caller-callee relations? If so, I guess some of the them do not make sense. For example, I don't think `BlockBasedTable::PrefixExtractorChanged()` calls `BlockFetcher::ReadBlockContents()`.
This could be missing debug symbols.

I first suspected your 7.0 version did not include https://github.com/facebook/rocksdb/commit/91687d70eaadefec7adc4070376d3cdc702a672d. This commit fixes a bug which can cause reading more blocks. But you mentioned you were using 7.0.3 which actually included this commit and @cavallium were using 7.1, so it's unlikely.

@cavallium let us know how you would like to share your profiling results.

In the meantime, it may also be helpful to enable statistics (https://github.com/facebook/rocksdb/wiki/Statistics) and we can check whether the counters related to block cache look reasonable.

**Comment by cavallium** [comment] 2022-05-09 13:24
> Thanks all for reporting and investigating!
> 
> @jojochuang I cannot use `jeprof` to open the heap profile because some dependencies are missing on my machine, thus I am looking at the pdf you provided. Do the arrows represent caller-callee relations? If so, I guess some of the them do not make sense. For example, I don't think `BlockBasedTable::PrefixExtractorChanged()` calls `BlockFetcher::ReadBlockContents()`. This could be missing debug symbols.
> 
> I first suspected your 7.0 version did not include [91687d7](https://github.com/facebook/rocksdb/commit/91687d70eaadefec7adc4070376d3cdc702a672d). This commit fixes a bug which can cause reading more blocks. But you mentioned you were using 7.0.3 which actually included this commit and @cavallium were using 7.1, so it's unlikely.
> 
> @cavallium let us know how you would like to share your profiling results.
> 
> In the meantime, it may also be helpful to enable statistics (https://github.com/facebook/rocksdb/wiki/Statistics) and we can check whether the counters related to block cache look reasonable.

I anonymized the report, you can open it using heaptrack: https://local.cavallium.it/mirrors/heaptrack.java.anonymized.gz
I've also collected some statistics, tell me which stats keys I should send

**Comment by riversand963** [comment] 2022-05-09 17:27
The filter and index block counters are all zero. Something is not right.
Can you check the git sha of RocksDB?

**Comment by cavallium** [comment] 2022-05-09 17:59
> The filter and index block counters are all zero. Something is not right. Can you check the git sha of RocksDB?

I am using the latest version that rocksdb published on maven central. I have not compiled it myself

**Comment by riversand963** [comment] 2022-05-09 18:38
You can check the first a few lines of the generated LOG file in the RocksDB directory.

**Comment by cavallium** [comment] 2022-05-09 22:09
> You can check the first a few lines of the generated LOG file in the RocksDB directory.
```java
2022/05/10-00:05:53.607922 139853604816448 RocksDB version: 7.1.2
2022/05/10-00:05:53.608035 139853604816448 Compile date 2022-04-20 18:00:14
2022/05/10-00:05:53.608037 139853604816448 DB SUMMARY
2022/05/10-00:05:53.608039 139853604816448 DB Session ID:  71866LPDHPQY27MN5YAB
2022/05/10-00:05:53.608083 139853604816448 CURRENT file:  CURRENT
2022/05/10-00:05:53.608085 139853604816448 IDENTITY file:  IDENTITY
2022/05/10-00:05:53.608088 139853604816448 MANIFEST file:  MANIFEST-001029 size: 6330 Byte
```

**Comment by pdillinger** [comment] 2022-05-09 23:18
> The filter and index block counters are all zero. Something is not right. Can you check the git sha of RocksDB?

That's expected with cache_index_and_filter_blocks=false && partition_filters=false

**Comment by riversand963** [comment] 2022-05-09 23:36
> I've also collected some statistics, tell me which stats keys I should send

@cavallium could you share all the output from `statistics`?

**Comment by pdillinger** [comment] 2022-05-10 00:06
Do we know if different LZ4 versions are used between these two versions?

**Comment by jojochuang** [comment] 2022-05-10 00:07
So, I just realized the memory leak started after this commit: #9523 https://github.com/facebook/rocksdb/commit/99d86252b 

and it makes sense because objects could linger around for extended period of time after this change.

**Comment by riversand963** [comment] 2022-05-10 00:10
Thanks @jojochuang a lot for the investigation!
cc @alanpaxton, could you take a look at this?

**Comment by riversand963** [comment] 2022-05-10 00:38
So I think after #9523, it is required that users call `close` on RocksJava objects or use `try-with-resource`, since original `dispose()` will not be used for reasons explained in that PR.

**Comment by jojochuang** [comment] 2022-05-10 00:40
Supposedly this suggests somewhere in our application code we failed to release rocksdb objects properly. However, I am having hard time figuring out where it is. The leak is not in Java heap so jmap doesn't show; jemalloc doesn't show Java symbols so while I see a lot of memory leak, can't trace back to the Java code that caused it. The Java static analyzer we use doesn't tell where the leak could be.

**Comment by jojochuang** [comment] 2022-05-10 04:24
@riversand963 while i understand the purpose of the #9523, it makes the migration from RocksDB 6 to 7 very hard because this is all hidden underneath.

I was finally able to find the source of the leak in my code, after add back finalize() and additional debug log to show the stack trace when the object is created. https://github.com/jojochuang/rocksdb/commits/debug_memory_leak

It would be great if a migration helper feature can be developed to help users identify memory leakage and to help them upgrade. Something based on my small experiment will do.

**Comment by cavallium** [comment] 2022-05-10 07:57
> @cavallium could you share all the output from `statistics`?

```bash
main BACKUP_READ_BYTES | 0
main BACKUP_WRITE_BYTES | 0
main BLOB_DB_BLOB_FILE_BYTES_READ | 0
main BLOB_DB_BLOB_FILE_BYTES_WRITTEN | 0
main BLOB_DB_BLOB_FILE_SYNCED | 0
main BLOB_DB_BLOB_INDEX_EVICTED_COUNT | 0
main BLOB_DB_BLOB_INDEX_EVICTED_SIZE | 0
main BLOB_DB_BLOB_INDEX_EXPIRED_COUNT | 0
main BLOB_DB_BLOB_INDEX_EXPIRED_SIZE | 0
main BLOB_DB_BYTES_READ | 0
main BLOB_DB_BYTES_WRITTEN | 0
main BLOB_DB_FIFO_BYTES_EVICTED | 0
main BLOB_DB_FIFO_NUM_FILES_EVICTED | 0
main BLOB_DB_FIFO_NUM_KEYS_EVICTED | 0
main BLOB_DB_GC_BYTES_EXPIRED | 0
main BLOB_DB_GC_BYTES_OVERWRITTEN | 0
main BLOB_DB_GC_BYTES_RELOCATED | 0
main BLOB_DB_GC_FAILURES | 0
main BLOB_DB_GC_NUM_FILES | 0
main BLOB_DB_GC_NUM_KEYS_EXPIRED | 0
main BLOB_DB_GC_NUM_KEYS_OVERWRITTEN | 0
main BLOB_DB_GC_NUM_KEYS_RELOCATED | 0
main BLOB_DB_GC_NUM_NEW_FILES | 0
main BLOB_DB_NUM_GET | 0
main BLOB_DB_NUM_KEYS_READ | 0
main BLOB_DB_NUM_KEYS_WRITTEN | 0
main BLOB_DB_NUM_MULTIGET | 0
main BLOB_DB_NUM_NEXT | 0
main BLOB_DB_NUM_PREV | 0
main BLOB_DB_NUM_PUT | 0
main BLOB_DB_NUM_SEEK | 0
main BLOB_DB_NUM_WRITE | 0
main BLOB_DB_WRITE_BLOB | 0
main BLOB_DB_WRITE_BLOB_TTL | 0
main BLOB_DB_WRITE_INLINED | 0
main BLOB_DB_WRITE_INLINED_TTL | 0
main BLOCK_CACHE_ADD | 2.72 Mil
main BLOCK_CACHE_ADD_FAILURES | 0
main BLOCK_CACHE_BYTES_READ | 425 Bil
main BLOCK_CACHE_BYTES_WRITE | 44.6 Bil
main BLOCK_CACHE_COMPRESSED_ADD | 16.4 Mil
main BLOCK_CACHE_COMPRESSED_ADD_FAILURES | 0
main BLOCK_CACHE_COMPRESSED_HIT | 1.77 Mil
main BLOCK_CACHE_COMPRESSED_MISS | 17.6 Mil
main BLOCK_CACHE_DATA_ADD | 2.72 Mil
main BLOCK_CACHE_DATA_BYTES_INSERT | 44.6 Bil
main BLOCK_CACHE_DATA_HIT | 25.9 Mil
main BLOCK_CACHE_DATA_MISS | 19.3 Mil
main BLOCK_CACHE_FILTER_ADD | 0
main BLOCK_CACHE_FILTER_BYTES_EVICT | 0
main BLOCK_CACHE_FILTER_BYTES_INSERT | 0
main BLOCK_CACHE_FILTER_HIT | 0
main BLOCK_CACHE_FILTER_MISS | 0
main BLOCK_CACHE_HIT | 25.9 Mil
main BLOCK_CACHE_INDEX_ADD | 0
main BLOCK_CACHE_INDEX_BYTES_EVICT | 0
main BLOCK_CACHE_INDEX_BYTES_INSERT | 0
main BLOCK_CACHE_INDEX_HIT | 0
main BLOCK_CACHE_INDEX_MISS | 0
main BLOCK_CACHE_MISS | 19.3 Mil
main BLOOM_FILTER_FULL_POSITIVE | 28.3 Mil
main BLOOM_FILTER_FULL_TRUE_POSITIVE | 21.7 Mil
main BLOOM_FILTER_PREFIX_CHECKED | 0
main BLOOM_FILTER_PREFIX_USEFUL | 0
main BLOOM_FILTER_USEFUL | 49.4 Mil
main BYTES_READ | 1.83 Bil
main BYTES_WRITTEN | 23.1 Bil
main COLD_FILE_READ_BYTES | 0
main COLD_FILE_READ_COUNT | 0
main COMPACTION_CANCELLED | 0
main COMPACTION_KEY_DROP_NEWER_ENTRY | 9.37 Mil
main COMPACTION_KEY_DROP_OBSOLETE | 0
main COMPACTION_KEY_DROP_RANGE_DEL | 0
main COMPACTION_KEY_DROP_USER | 0
main COMPACTION_OPTIMIZED_DEL_DROP_OBSOLETE | 0
main COMPACTION_RANGE_DEL_DROP_OBSOLETE | 0
main COMPACT_READ_BYTES | 122 Bil
main COMPACT_READ_BYTES_MARKED | 0
main COMPACT_READ_BYTES_PERIODIC | 0
main COMPACT_READ_BYTES_TTL | 0
main COMPACT_WRITE_BYTES | 125 Bil
main COMPACT_WRITE_BYTES_MARKED | 0
main COMPACT_WRITE_BYTES_PERIODIC | 0
main COMPACT_WRITE_BYTES_TTL | 0
main DB_MUTEX_WAIT_MICROS | 0
main ERROR_HANDLER_AUTORESUME_COUNT | 0
main ERROR_HANDLER_AUTORESUME_RETRY_TOTAL_COUNT | 0
main ERROR_HANDLER_AUTORESUME_SUCCESS_COUNT | 0
main ERROR_HANDLER_BG_ERROR_COUNT | 0
main ERROR_HANDLER_BG_IO_ERROR_COUNT | 0
main ERROR_HANDLER_BG_RETRYABLE_IO_ERROR_COUNT | 0
main FILES_DELETED_IMMEDIATELY | 353
main FILES_MARKED_TRASH | 0
main FILTER_OPERATION_TOTAL_TIME | 0
main FLUSH_WRITE_BYTES | 11.4 Bil
main GET_HIT_L0 | 255 K
main GET_HIT_L1 | 0
main GET_HIT_L2_AND_UP | 21.4 Mil
main GET_UPDATES_SINCE_CALLS | 0
main HOT_FILE_READ_BYTES | 0
main HOT_FILE_READ_COUNT | 0
main ITER_BYTES_READ | 20.1 Mil
main LAST_LEVEL_READ_BYTES | 55.0 Bil
main LAST_LEVEL_READ_COUNT | 6.88 Mil
main MEMTABLE_GARBAGE_BYTES_AT_FLUSH | 8.94 Bil
main MEMTABLE_HIT | 6.00 Mil
main MEMTABLE_MISS | 27.6 Mil
main MEMTABLE_PAYLOAD_BYTES_AT_FLUSH | 20.5 Bil
main MERGE_OPERATION_TOTAL_TIME | 0
main NON_LAST_LEVEL_READ_BYTES | 104 Bil
main NON_LAST_LEVEL_READ_COUNT | 10.4 Mil
main NO_FILE_CLOSES | 0
main NO_FILE_ERRORS | 0
main NO_FILE_OPENS | 2.45 K
main NO_ITERATORS | 0
main NO_ITERATOR_CREATED | 68.0 K
main NO_ITERATOR_DELETED | 68.0 K
main NUMBER_BLOCK_COMPRESSED | 14.1 Mil
main NUMBER_BLOCK_DECOMPRESSED | 15.8 Mil
main NUMBER_BLOCK_NOT_COMPRESSED | 157
main NUMBER_DB_NEXT | 11.0 K
main NUMBER_DB_NEXT_FOUND | 10.7 K
main NUMBER_DB_PREV | 10.9 K
main NUMBER_DB_PREV_FOUND | 10.7 K
main NUMBER_DB_SEEK | 67.9 K
main NUMBER_DB_SEEK_FOUND | 26.6 K
main NUMBER_DIRECT_LOAD_TABLE_PROPERTIES | 0
main NUMBER_FILTERED_DELETES | 0
main NUMBER_ITER_SKIP | 2.96 K
main NUMBER_KEYS_READ | 33.6 Mil
main NUMBER_KEYS_UPDATED | 0
main NUMBER_KEYS_WRITTEN | 61.6 Mil
main NUMBER_MERGE_FAILURES | 0
main NUMBER_MULTIGET_BYTES_READ | 0
main NUMBER_MULTIGET_CALLS | 0
main NUMBER_MULTIGET_KEYS_FOUND | 0
main NUMBER_MULTIGET_KEYS_READ | 0
main NUMBER_OF_RESEEKS_IN_ITERATION | 32
main NUMBER_RATE_LIMITER_DRAINS | 0
main NUMBER_SUPERVERSION_ACQUIRES | 10.6 K
main NUMBER_SUPERVERSION_CLEANUPS | 20
main NUMBER_SUPERVERSION_RELEASES | 188
main PERSISTENT_CACHE_HIT | 4
main PERSISTENT_CACHE_MISS | 15.0 K
main RATE_LIMIT_DELAY_MILLIS | 0
main READ_AMP_ESTIMATE_USEFUL_BYTES | 0
main READ_AMP_TOTAL_READ_BYTES | 0
main REMOTE_COMPACT_READ_BYTES | 0
main REMOTE_COMPACT_WRITE_BYTES | 0
main ROW_CACHE_HIT | 0
main ROW_CACHE_MISS | 0
main SECONDARY_CACHE_HITS | 0
main SIM_BLOCK_CACHE_HIT | 0
main SIM_BLOCK_CACHE_MISS | 0
main STALL_L0_NUM_FILES_MICROS | 0
main STALL_L0_SLOWDOWN_MICROS | 0
main STALL_MEMTABLE_COMPACTION_MICROS | 0
main STALL_MICROS | 0
main TXN_DUPLICATE_KEY_OVERHEAD | 0
main TXN_GET_TRY_AGAIN | 0
main TXN_OLD_COMMIT_MAP_MUTEX_OVERHEAD | 0
main TXN_PREPARE_MUTEX_OVERHEAD | 0
main TXN_SNAPSHOT_MUTEX_OVERHEAD | 0
main VERIFY_CHECKSUM_READ_BYTES | 0
main WAL_FILE_BYTES | 23.1 Bil
main WAL_FILE_SYNCED | 2
main WARM_FILE_READ_BYTES | 0
main WARM_FILE_READ_COUNT | 0
main WRITE_DONE_BY_OTHER | 886 K
main WRITE_DONE_BY_SELF | 60.7 Mil
main WRITE_TIMEDOUT | 0
main WRITE_WITH_WAL | 61.6 Mil
```

**Comment by cavallium** [comment] 2022-05-10 08:05
> So I think after #9523, it is required that users call `close` on RocksJava objects or use `try-with-resource`, since original `dispose()/finalize()` will not be called automatically by JVM for reasons explained in that PR.

Thanks, I have always used try with resources with rocksdb objects, but probably some object somewhere in my code has not been closed

**Comment by alanpaxton** [comment] 2022-05-10 08:15
Thanks @riversand963 @jojochuang for figuring out what is happening. There's never a good time to make that sort of change. I'll have a chat with @adamretter and see if we can pick up your leak checker in some form.

**Comment by adamretter** [comment] 2022-05-10 08:28
@jojochuang The reliance on `finalize` in RocksDB has been deprecated for a couple of years at least now. Not relying on finalize has also been documented for some time here - https://github.com/facebook/rocksdb/wiki/RocksJava-Basics#memory-management

We decided to finally remove the use of `finalize` as one of the major features when updating from RocksDB 6 to 7, we also moved to Java 8 from Java 7 and moved to C++17 from C++11. This should have been mentioned in the release notes, but I see that was missing, I have now added it here - https://github.com/facebook/rocksdb/releases/tag/v7.0.1

**Comment by cavallium** [comment] 2022-05-10 10:03
> @alanpaxton Has been working on an experimental reference counting approach to see if we could find an alternative 3rd option which gives the best of both approaches. The difficulty is implementing such an approach that does not impact the performance of every operation. This is ongoing, and won't be finished for some time yet.
> 

Regarding reference counting, I suggest you to take a look at how netty buffers approached this problem when they started developing netty 5: https://github.com/netty/netty/pull/11347 (they removed ref-counting in favor of try-with-resources)

**Comment by jojochuang** [comment] 2022-05-10 19:24
Re: Netty
I am looking forward to something similar to Netty's leak detection mechanism, where it can be enabled/disabled via a runtime parameter https://netty.io/wiki/reference-counted-objects.html#leak-detection-levels
IMO it would be useful for developers.

**Comment by cavallium** [comment] 2022-05-10 22:23
I found that some internal RocksDB java code is causing leaks, note that the readOptions are not wrapped with try/finally:
```java
  public List<ByteBufferGetStatus> multiGetByteBuffers(
      final List<ByteBuffer> keys, final List<ByteBuffer> values) throws RocksDBException {
    final ReadOptions readOptions = new ReadOptions();
    final List<ColumnFamilyHandle> columnFamilyHandleList = new ArrayList<>(1);
    columnFamilyHandleList.add(getDefaultColumnFamily());
    return multiGetByteBuffers(readOptions, columnFamilyHandleList, keys, values);
  }

```

@jojochuang are you really sure that you don't have memory leaks anymore?

**Comment by cavallium** [comment] 2022-05-12 07:17
The problem is still present in 7.2.2

**Comment by jojochuang** [comment] 2022-05-12 15:34
I found lots of memory leaks, both in my application code as well as in RocksDB.

IMO TransactionLogIterator should implement close() and close its writeBatch object too.

ColumnFamilyOptions is tricky, because it does not implement close and many of its subfield needs to be closed one by one.  I mean it's doable but annoying.

**Comment by riversand963** [comment] 2022-05-12 19:47
It seems to me that RocksJava needs to detect leaks of native objects in our codebase caused by not using `try-with-resource` or not calling `close()`.
@adamretter, is there any tool or other means that can be used to find out and fix these improper usage? Seems a blocker for people to upgrade to RocksDB 7.0+ Java bindings.

**Comment by siying** [comment] 2022-05-16 22:16
> I found that some internal RocksDB java code is probably causing leaks, note that ReadOptions is not wrapped with try/finally:
> 
> ```java
>   public List<ByteBufferGetStatus> multiGetByteBuffers(
>       final List<ByteBuffer> keys, final List<ByteBuffer> values) throws RocksDBException {
>     final ReadOptions readOptions = new ReadOptions();
>     final List<ColumnFamilyHandle> columnFamilyHandleList = new ArrayList<>(1);
>     columnFamilyHandleList.add(getDefaultColumnFamily());
>     return multiGetByteBuffers(readOptions, columnFamilyHandleList, keys, values);
>   }
> ```
> 
> @jojochuang are you really sure that you don't have memory leaks anymore?

@adamretter can you comment on whether RocksDB Java internally cancause of memory leaks?

**Comment by andrew-ld** [comment] 2022-05-17 19:53
@jojochuang have you been able to solve all the memory leaks on apache ozone?, we even closing everything still have memory leaks.

**Comment by jojochuang** [comment] 2022-05-17 22:25
I have a big project and I'm only able to catch the biggest offenders so far :)

it would be best to apply the patch in my fork https://github.com/jojochuang/rocksdb/commits/debug_memory_leak and run your application. It prints stacktrace where leak come from.

**Comment by alanpaxton** [comment] 2023-10-18 09:00
Now that https://github.com/facebook/rocksdb/pull/11221 addressing RocksDBJava leaks has been merged, I think we can close this @pdillinger  - there's a conversation to be had on how to handle things going forward, e.g. using Panama/FFI around the C interface and letting the current JNI interface go maintenance only, but I don't think this ticket is the place.

**Comment by adamretter** [comment] 2023-10-18 10:09
I think @alanpaxton is correct, so I am closing this one.

**Closed by adamretter** 2023-10-18 10:09 UTC
Labels: java

**Comment by areyohrahul** [comment] 2023-10-22 08:04
@jojochuang Were you able to eliminate all the memory leaks. I'm also using RockDBJni (8.5.4) but I cannot seem to figure out what more could be missing here?

For me, it seems to be occurring in the read path only.

Any suggestions, please?

**Comment by areyohrahul** [comment] 2023-10-22 08:42
@alanpaxton should I fork this (https://github.com/facebook/rocksdb/pull/11221) PR or is it gonna be pushed to maven? I guess I missed the last few comments. This fixes the current memory issues?
