### ISSUE TITLE
Include librocksdbjni-win64.dll in rocksdbjni-5.2.1.jar in Maven

### ISSUE THREAD

**Issue by andrewstellman** [facebook/rocksdb#2216] opened 2017-04-26 19:05 UTC
Version 5.1.2 of rocksdbjni included librocksdbjni-win64.dll, but it is not included in rocksdbjni-5.2.1.jar in the  Maven package. Reproduced by downloading from http://repo1.maven.org/maven2/org/rocksdb/rocksdbjni/ :

```
% unzip -v rocksdbjni-5.2.1.jar  | grep -i dll
% unzip -v rocksdbjni-5.1.2.jar  | grep -i dll
 3725312  Defl:N  1404547  62% 02-11-2017 13:41 c719ed38  librocksdbjni-win64.dll
```

This same issue was reported and repaired with a previous version (#1177).

**Comment by adamretter** [comment] 2017-04-26 19:16
I am closing this as a duplicate of: https://github.com/facebook/rocksdb/issues/2215

**Closed by adamretter** 2017-04-26 19:16 UTC
Labels: java-api
