### ISSUE TITLE
Java release for 9.0

### ISSUE THREAD

**Issue by jowlyzhang** [facebook/rocksdb#12435] opened 2024-03-14 17:11 UTC
@adamretter Could you please do the Java/other platform testing for 9.0? Thanks!

**Comment by adamretter** [comment] 2024-03-15 12:58
@jowlyzhang Working on it now...

**Comment by adamretter** [comment] 2024-03-15 20:08
@jowlyzhang This PR that was merged to `main` and `8.11.fb` seems to be missing from `9.0.fb`. At the moment that means that Windows builds of RocksJava are not working for `9.0.fb`, can you merge it please - https://github.com/facebook/rocksdb/pull/12371

**Comment by adamretter** [comment] 2024-03-19 15:12
@jowlyzhang I can confirm that 9.0.fb is now working correctly

**Closed** 2024-03-25 14:29 UTC
