### ISSUE TITLE
SIGSEGV when transaction leave open but db is closed

### ISSUE THREAD

**Issue by mad** [facebook/rocksdb#6913] opened 2020-06-02 11:42 UTC
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior

error about leaked resource

### Actual behavior

jvm crashed

### Steps to reproduce the behavior

```
public class RockDbCrash3 {
    public static void main(String[] args) throws RocksDBException {
        final TransactionDB db = TransactionDB.open(new Options().setCreateIfMissing(true), new TransactionDBOptions(), "/tmp/test");
        Transaction transaction = db.beginTransaction(new WriteOptions());
        db.close();
        transaction = null;
        System.gc();
    }
}
```

**Comment by adamretter** [comment] 2020-06-02 11:50
@mad Help us out here!

Can you tell us the version of RocksDB, and attach the hs_err file please?

**Comment by mad** [comment] 2020-06-02 11:54
6.8.1

```
# JRE version: OpenJDK Runtime Environment (14.0+36) (build 14+36-1461)
# Java VM: OpenJDK 64-Bit Server VM (14+36-1461, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)

Stack: [0x00007fc770a12000,0x00007fc770b13000],  sp=0x00007fc770b11660,  free space=1021k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [librocksdbjni11215797669481267316.so+0x566d31]  rocksdb::PessimisticTransactionDB::UnLock(rocksdb::PessimisticTransaction*, std::unordered_map<unsigned int, std::unordered_map<std::string, rocksdb::TransactionKeyMapInfo, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, rocksdb::TransactionKeyMapInfo> > >, std::hash<unsigned int>, std::equal_to<unsigned int>, std::allocator<std::pair<unsigned int const, std::unordered_map<std::string, rocksdb::TransactionKeyMapInfo, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, rocksdb::TransactionKeyMapInfo> > > > > > const*)+0x31
C  [librocksdbjni11215797669481267316.so+0x563cd0]  rocksdb::PessimisticTransaction::~PessimisticTransaction()+0x30
C  [librocksdbjni11215797669481267316.so+0x565fbf]  rocksdb::WriteCommittedTxn::~WriteCommittedTxn()+0x1f
j  org.rocksdb.Transaction.disposeInternal(J)V+0
j  org.rocksdb.RocksObject.disposeInternal()V+5
j  org.rocksdb.AbstractImmutableNativeReference.close()V+13
j  org.rocksdb.AbstractNativeReference.dispose()V+1
j  org.rocksdb.AbstractNativeReference.finalize()V+8
j  java.lang.System$2.invokeFinalize(Ljava/lang/Object;)V+1 java.base@14
j  java.lang.ref.Finalizer.runFinalizer(Ljdk/internal/access/JavaLangAccess;)V+101 java.base@14
j  java.lang.ref.Finalizer$FinalizerThread.run()V+46 java.base@14
```

**Comment by adamretter** [comment] 2020-06-02 12:07
@mad Interesting stack, looks like the GC/finalize is messing with you and you are experiencing a similar problem to - https://github.com/facebook/rocksdb/issues/4461

If you rewrite your example to follow the memory-management guidelines for use on Java (https://github.com/facebook/rocksdb/wiki/RocksJava-Basics#memory-management) does the problem go away?

**Comment by mad** [comment] 2020-06-02 12:18
Yes it is same issue. If I close explicitly the problem solved

**Comment by adamretter** [comment] 2020-06-02 12:58
@mad okay cool, thanks.

**Comment by adamretter** [comment] 2020-06-02 12:58
Duplicate of https://github.com/facebook/rocksdb/issues/4461

**Closed by adamretter** 2020-06-02 12:58 UTC
Labels: java-api
