### ISSUE TITLE
Problem with PosixEnv destructor

### ISSUE THREAD

**Issue by RoeyMaor** [facebook/rocksdb#9894] opened 2022-04-22 18:13 UTC
The PosixEnv destructor was designed with the assumption that it runs in the main thread.
There are situations where it won't execute in the main thread, resulting in a deadlock or other undefined behavior.

When a signal is received, Linux chooses the thread on which the signal handler will run from all of the threads of the process which are in a waiting state (like the threadpool background threads).

This results in a situation where the signal handler and PosixEnv destructor is executed in a background thread in the threadpool instead of the main thread.

**Comment by pdillinger** [comment] 2022-04-26 21:07
AFAIK there is no bug here. If a signal causes termination, no destructors are run. If a signal does not cause termination, no destructors are run. Closing until you can provide some reproducer.

If you exit the program with a DB open, you can easily run into trouble in the PosixEnv destructor. That's because we don't attempt to support that case (starting static destruction with a DB open). That would be a more ambitious project that AFAIK has nothing to do with signals.

**Closed by pdillinger** 2022-04-26 21:07 UTC
Labels: bug
