### ISSUE TITLE
Obsolete WAL files don't always get deleted

### ISSUE THREAD

**Issue by yunjing** [facebook/rocksdb#2523] opened 2017-06-30 01:26 UTC
DB version is v5.4.6. I noticed that whenever the DB process restarts, it scans all WAL files, but not all WAL files got deleted after the recovery process finishes. Over the course of a month, it accumulated lots of obsolete WAL files, and the DB restart time gets longer and longer due to extended recovery time, most of is wasted on scanning obsolete files.

I tried to decrease delete_obsolete_files_period_micros, but it did not help. Is there a safe way to automatically delete those obsolete WAL files?

**Comment by iKenApple** [comment] 2017-11-01 01:54
Have you set those two parameters WAL_ttl_seconds and WAL_size_limit_MB? By default, WAL files will be deleted as soon as possible. You can find explanation in option.h.

**Comment by yiwu-arbug** [comment] 2018-01-22 19:36
@yunjing Does @iKenApple's comment address your issue? I'm closing the issue for now. If the issue is not resolved please reopen.

**Closed by yiwu-arbug** 2018-01-22 19:36 UTC
