### ISSUE TITLE
Java: Support Apple Silicon/M1 machines

### ISSUE THREAD

**Issue by jurmous** [facebook/rocksdb#7720] opened 2020-11-28 15:23 UTC
When I run an application on an Apple Silicon based JVM depending on the RocksDB JVM library it fails with UnsatisfiedLinkError.

### Expected behavior
Maven dependency includes Mac Arm64 compilation

### Actual behavior
Maven dependency does not include Mac Arm64 compilation

### Steps to reproduce the behavior
Run RocksDB inside a Apple Silicon JVM application. UnsatisfiedLinkError is thrown.

Depends on #7710

Note: RocksDB for Java works normally running in Rosetta mode, but as soon as environment is started in non Rosetta mode the program fails.

**Comment by adamretter** [comment] 2020-11-28 23:10
@jurmous I am waiting for https://github.com/facebook/rocksdb/pull/7714 to get merged before I add the update for RocksJava. If you want to test #7714 and give us some feedback that would be great...

**Comment by jurmous** [comment] 2020-11-29 16:23
I posted my feedback in #7714.

**Comment by jurmous** [comment] 2020-12-10 20:28
@adamretter Thanks for all the work on the Apple Silicon compilation issues! Do you have any update on the RocksJava Apple Silicon support? Or do you need help?

**Comment by adamretter** [comment] 2020-12-10 20:35
@jurmous I can likely send a PR tomorrow if that works for you?

**Comment by adamretter** [comment] 2020-12-11 15:57
@jurmous okay so there is no problem with building RocksDB and RocksJava from source and running it on Apple Silicon now.

I will shortly send a PR to differentiate between Mac binaries for x64 and aarch64. We can then package both into the next release of RocksJava that is published on Maven central.

**Comment by jurmous** [comment] 2020-12-11 16:52
@adamretter Thanks for checking it out!

Cool that there is no problem building the libraries!

Yes both directions would be valid. Universal makes some things easier I guess and the Mac binary is not that large compared to linux64.

**Comment by jurmous** [comment] 2021-01-13 17:36
@adamretter Were you already able to give some thought on the best approach? And were you able to create a PR? Thanks! 😊

**Comment by adamretter** [comment] 2021-01-13 17:53
@jurmous Sorry for the delay, I do have some preliminary work here. I had to pause whilst other priorities took over, but I hope to get back to it ASAP.

**Comment by jurmous** [comment] 2021-01-14 15:36
Ok, I understand. Good luck with the other priorities! Let me know if I can help when you are able to get back to it!

**Comment by Yrp** [comment] 2021-01-29 08:18
Hi, guys. Any progress?

**Comment by adamretter** [comment] 2021-01-29 09:48
@jurmous @Yrp you can find the start of my work on Universal Binaries for RocksDB here -
https://github.com/adamretter/rocksdb/tree/macos-multi-arch

Running `make static_lib_ub` will give you a Universal Binary for both
x86_64 arm64.

Building the universal binaries can be done in macOS on either Intel
or Apple Silicon as long as you have macOS bigSur and the latest
XCode.

**Comment by jurmous** [comment] 2021-01-30 15:54
@adamretter Thanks for all the work already! ❤️ 

I have checked out your branch and tried to run `make static_lib_ub` on root.
I get however an error about an unknown CPU target: 
(Big Sur 11.1 & Xcode 12.4 on an M1 machine)
```
$DEBUG_LEVEL is 1
Makefile:203: Warning: Compiling in debug mode. Don't use the resulting binary in production
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LC_ALL = (unset),
        LC_CTYPE = "en_NL.UTF-8",
        LANG = (unset)
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
  GEN      util/build_version.cc
TARGET_ARCHITECTURE=x86_64 STATIC_LIBRARY=librocksdb_debug-x86_64.a /Applications/Xcode.app/Contents/Developer/usr/bin/make static_lib
$DEBUG_LEVEL is 0
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LC_ALL = (unset),
        LC_CTYPE = "en_NL.UTF-8",
        LANG = (unset)
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
  GEN      util/build_version.cc
  CC       table/merging_iterator.o
error: unknown target CPU 'armv8-a+crc+crypto'
note: valid target CPU values are: nocona, core2, penryn, bonnell, atom, silvermont, slm, goldmont, goldmont-plus, tremont, nehalem, corei7, westmere, sandybridge,
      corei7-avx, ivybridge, core-avx-i, haswell, core-avx2, broadwell, skylake, skylake-avx512, skx, cascadelake, cooperlake, cannonlake, icelake-client, icelake-server,
      tigerlake, knl, knm, k8, athlon64, athlon-fx, opteron, k8-sse3, athlon64-sse3, opteron-sse3, amdfam10, barcelona, btver1, btver2, bdver1, bdver2, bdver3, bdver4,
      znver1, znver2, x86-64
make[1]: *** [table/merging_iterator.o] Error 1
make: *** [static_lib_ub] Error 2
```

'make static_lib` runs fine btw.

This work is for the generic static library if I am correct? If this works correctly further work has to be done to build a universal `librocksdbjni-osx.jnilib`?

**Comment by tobiade** [comment] 2021-04-04 19:54
Hey folks - thanks for the work here. I just ran into this issue when trying to run a Kafka Streams app on my M1 machine. The Kafka Stream library is using RocksDB v5.18.4 under the hood.

@jurmous you mentioned you were able to run RocksDB when running in Rosetta mode? Could you please let me know how you did that? I'm just (very) simply trying to run my app from IntelliJ, so curious as to how to modify it to run in Rosetta mode.

**Comment by tobiade** [comment] 2021-04-05 11:53
Actually nvm - I just realised I wasn't running x86 Java.

**Comment by jurmous** [comment] 2021-04-05 14:46
@tobiade Ah great that you got it working with Rosetta!
I worked for now with my custom build RocksDB release locally for the M1 so I can run the app natively. I published it back then in jcenter so it will only be there temporary and I only published the Mac target so it cannot be used in a generic fashion on other architectures.
"io.maryk.rocksdb:rocksdbjni:6.17.0"

**Comment by plusmancn** [comment] 2021-04-16 03:47
> io.maryk.rocksdb:rocksdbjni:6.17.0

@jurmous I found the page shows 403 forbidden on jcenter. 
Link: [https://jcenter.bintray.com/io/maryk/rocksdb/rocksdbjni/6.17.0](https://jcenter.bintray.com/io/maryk/rocksdb/rocksdbjni/6.17.0)

**Comment by jurmous** [comment] 2021-04-16 07:00
That page is indeed forbidden but the files should be accessible without being logged in:
https://bintray.com/maryk/maven/rocksdbjni

**Comment by adamretter** [comment] 2021-04-16 10:23
@jurmous Sorry for the delay, I had to return the Apple DTK to Apple as they only allow you to have it for a short-time. I have a M1 on order, and so will try and pick it up again once that arrives.

**Comment by jurmous** [comment] 2021-04-16 12:30
@adamretter Thanks for the update! As you can read I have for now a temp solution so I can natively do things on my laptop. Thanks for when you can look into it! All your work is greatly appreciated!

**Comment by gmicsa** [comment] 2021-05-22 12:30
Any progress on this? It seems not much left on your side to release M1 compatible version...so looking forward to it :)

**Comment by jurmous** [comment] 2021-06-20 17:14
Hey @adamretter,

I have looked into the compilation issue `error: unknown target CPU 'armv8-a+crc+crypto'` of the universal static library on your branch. I had to dive into how Makefiles work but by trial and error I could nail the issue down. It seems it fails when compiling the x86 static library specifically.

If I comment out the following code in the Makefile the universal static library compiles normally and the lipo command returns both x86_64 and arm64 on the library
```
ifeq (,$(shell $(CXX) -fsyntax-only -march=armv8-a+crc+crypto -xc /dev/null 2>&1))
CXXFLAGS += -march=armv8-a+crc+crypto
CFLAGS += -march=armv8-a+crc+crypto
ARMCRC_SOURCE=1
endif
```

So that piece of code needs an extra if check in case of compiling for macOS.

I guess it only needs an adjustment to wrap this new universal static library inside a jnilib to be bundled for release.

Do you guess you have time for this issue soon? 😄

**Comment by hstaudacher** [comment] 2021-11-04 04:39
Is there any progress here? Right now this blocks developing e.g. using kafka-streams on a M1 using a native JDK.

**Comment by andrashatvani** [comment] 2021-11-04 08:10
Since the performance is 5x worse when using an x86_64 JDK via Rosetta this is a severe issue - please provide at least a time estimate.

**Comment by jurmous** [comment] 2021-11-13 14:31
I took some time to tinker what is exactly needed for Apple Silicon/M1 support in the java compilation. It seems currently the `jnilib` is only compiled for the architecture of the system. It needs to be compiled for both arm64 and x86_64 and then lipo-ed into a new jnilib. 

I did this manually and published the result to maven central so people can try out M1 support: 
`io.maryk.rocksdb:rocksdbjni:6.25.3`
(It is universal for Mac, and contains the jars of the already published rocksdbjni build of 6.25.3 for other OSes and bundles them all together in the all jar.)

For it to be implemented we need to expand the following Makefile target:

```
rocksdbjavastatic_javalib:
	cd java; SHA256_CMD='$(SHA256_CMD)' $(MAKE) javalib
	rm -f java/target/$(ROCKSDBJNILIB)
	$(CXX) $(CXXFLAGS) -I./java/. $(JAVA_INCLUDE) -shared -fPIC \
	  -o ./java/target/$(ROCKSDBJNILIB) $(JNI_NATIVE_SOURCES) \
	  $(LIB_OBJECTS) $(COVERAGEFLAGS) \
	  $(JAVA_COMPRESSIONS) $(JAVA_STATIC_LDFLAGS)
	cd java/target;if [ "$(DEBUG_LEVEL)" == "0" ]; then \
		strip $(STRIPFLAGS) $(ROCKSDBJNILIB); \
	fi
	cd java;jar -cf target/$(ROCKSDB_JAR) HISTORY*.md
	cd java/target;jar -uf $(ROCKSDB_JAR) $(ROCKSDBJNILIB)
	cd java/target/classes;jar -uf ../$(ROCKSDB_JAR) org/rocksdb/*.class org/rocksdb/util/*.class
	cd java/target/apidocs;jar -cf ../$(ROCKSDB_JAVADOCS_JAR) *
	cd java/src/main/java;jar -cf ../../../target/$(ROCKSDB_SOURCES_JAR) org
	openssl sha1 java/target/$(ROCKSDB_JAR) | sed 's/.*= \([0-9a-f]*\)/\1/' > java/target/$(ROCKSDB_JAR).sha1
	openssl sha1 java/target/$(ROCKSDB_JAVADOCS_JAR) | sed 's/.*= \([0-9a-f]*\)/\1/' > java/target/$(ROCKSDB_JAVADOCS_JAR).sha1
	openssl sha1 java/target/$(ROCKSDB_SOURCES_JAR) | sed 's/.*= \([0-9a-f]*\)/\1/' > java/target/$(ROCKSDB_SOURCES_JAR).sha1

```
It needs to build the jnilib on macOS for the architecture which is not the one of the current machine and then both results need to be lipo-ed into one file before continuing. 
`lipo -create librocksdbjni-osx-arm64.jnilib librocksdbjni-osx-x86.jnilib -output librocksdbjni-osx.jnilib`
Is there a Makefile champ out there who wants to look into making this change?

**Comment by etherond** [comment] 2021-12-06 14:28
Hello there! I'm no Makefile champ, but following @jurmous's precious findings I made a few changes so that the JAR produced includes a macOS Universal Binary library, providing support for both Intel and Apple Silicon machines.

The result is here: https://github.com/etherond/rocksdb/tree/osx-universalbinary

The produced JAR seems to work well on my MacBook Air M1.

To build the JAR, clone this repo then:

- Run `make clean rocksdbjavastaticosxub` to build a macOS (only) compatible JAR that will include a Universal Binary native library 

- Run `make jclean clean rocksdbjavastaticreleasedocker` to build a production-friendly JAR that will include native libraries for all supported platforms, as indicated by RocksDB's `RELEASE.MD`. This actually fails on my machine, as an error occurs when compiling the Linux library from the CentOS container. This doesn't seem related to my changes, as I have the same issue with the current RocksDB master branch and I couldn't take the time to investigate it... but as a consequence, I couldn't build a "full" fat JAR and test it properly on other platforms.

If some of you guys want to go ahead and try to build a JAR using one way or another, any feedback would be greatly appreciated :)

**Comment by jurmous** [comment] 2021-12-06 15:12
@etherond I have checked your new `rocksdbjavastaticosxub` target and it works perfectly. It creates a valid universal `librocksdbjni-osx.jnilib` and it is included properly in the jar. 

I would suggest to send in your changes as a PR and have it checked by the maintainers.

And in my world you are now a Makefile champ 👑 ❤️

**Comment by milosivanovic** [comment] 2021-12-29 23:04
Just wanted to chime in and say thanks to @etherond for making it possible to compile this natively, but also wanted to point out that his recent commits changed the Makefile target name. It's now suffixed with `_ub` rather than just `ub`: https://github.com/etherond/rocksdb/commit/7f50fb834abae86ef901fc891e2618db4863fbae#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R2227

So his instructions are now:
```
make clean rocksdbjavastaticosx_ub
```

rather than:
```
make clean rocksdbjavastaticosxub
```

**Comment by milosivanovic** [comment] 2021-12-29 23:09
Having said that, it looks like his PR is very close to getting merged: https://github.com/facebook/rocksdb/pull/9254

Exciting! Thanks again.

**Closed** 2022-01-13 01:21 UTC
Labels: java-api

**Comment by etherond** [comment] 2022-01-13 15:09
Yes, it was merged a few hours ago! You can try it by cloning the official repo's `main` branch and running `make rocksdbjavastatic` to produce a JAR to test on your local machine.

Thanks again to @jurmous for the investigation work that led to the solution :)

**Comment by loop** [comment] 2022-01-14 01:48
@etherond When will this version be pushed to maven?

**Comment by benkeil** [comment] 2022-01-14 04:39
A release or at least a nightly build version would be useful.

**Comment by etherond** [comment] 2022-01-14 11:46
@loop From what I understand of the project's [release methodology](https://github.com/facebook/rocksdb/wiki/RocksDB-Release-Methodology), it should be at least a few more weeks before a new version based on the current `main` is released publicly...
In the meantime, it seems that you could build your own cross-platform JAR by following instructions in `RELEASE.md` (as indicated earlier, I didn't succeed doing so earlier and haven't given it a try again since)

**Comment by jurmous** [comment] 2022-01-14 11:54
I am not aware of any nightly builds that exist. 

It is possible to use a build of 6.25.3 already build manually by me to be universal from Maven Central: io.maryk.rocksdb:rocksdbjni:6.25.3

**Comment by loop** [comment] 2022-01-15 01:02
@etherond Tried building my own. Ran:

`PORTABLE=1 make clean rocksdbjavastaticosx_ub --debug`

It created a `rocksdbjni-6.28.0-osx.jar`

When i try to use it it says:

`Caused by: java.lang.RuntimeException: librocksdbjni-osx-aarch64.jnilib was not found inside JAR.`

I thought `PORTABLE=1` should include the jnilib inside the jar?

**Comment by dtanner** [comment] 2022-01-24 16:38
@jurmous One issue I noticed is that the jar you uploaded targets JDK 15, so isn't compatible with runtimes older than that. In my case I'm trying to retrofit a JDK 11 project. Shouldn't be a big deal to resolve and build locally, just wanted to give a heads-up.
The symptom is:
```
java.lang.UnsupportedClassVersionError: org/rocksdb/ColumnFamilyHandle has been compiled by a more recent version of the Java Runtime (class file version 59.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

**Comment by LuciferYang** [comment] 2022-02-09 05:56
Isn't this feature released in version 6.28.2?

**Comment by yoyo837** [comment] 2022-02-09 06:09
> Isn't this feature released in version 6.28.2?

Obviously, not yet.

**Comment by jurmous** [comment] 2022-02-09 09:06
The feature has landed on the 6.29.fb branch so it will be first released in version 6.29.x.

**Comment by jurmous** [comment] 2022-02-09 09:11
> @jurmous One issue I noticed is that the jar you uploaded targets JDK 15, so isn't compatible with runtimes older than that. In my case I'm trying to retrofit a JDK 11 project. Shouldn't be a big deal to resolve and build locally, just wanted to give a heads-up. The symptom is:
> 
> ```
> java.lang.UnsupportedClassVersionError: org/rocksdb/ColumnFamilyHandle has been compiled by a more recent version of the Java Runtime (class file version 59.0), this version of the Java Runtime only recognizes class file versions up to 55.0
> ```

@dtanner Ah I missed setting up the proper JDK when compiling. I am afraid it is then best to wait for the next proper release.

**Comment by devinbost** [comment] 2022-02-14 17:53
When should we expect the next release to include this fix?

**Comment by jurmous** [comment] 2022-02-15 10:13
As mentioned above we can indeed expect the fix in the 6.29.x release. Past releases suggest a RocksDB java release every 1 or 2 months. So likely March or April. 

https://search.maven.org/artifact/org.rocksdb/rocksdbjni

**Comment by LuciferYang** [comment] 2022-02-22 01:57
@jurmous Has `RockDB 6.29` really been released? I saw the [release notes](https://github.com/facebook/rocksdb/releases/tag/v6.29.3) three days ago, but `rocksdbjni:6.29.3` cannot be downloaded from Maven repository.

**Comment by yoyo837** [comment] 2022-02-22 02:17
I found this:
<img width="1336" alt="image" src="https://user-images.githubusercontent.com/6134547/155050877-a48ce1bf-999c-4b2b-8716-f4594ab08e1e.png">

**Comment by martin-g** [comment] 2022-02-25 08:07
> @jurmous Has `RockDB 6.29` really been released? I saw the [release notes](https://github.com/facebook/rocksdb/releases/tag/v6.29.3) three days ago, but `rocksdbjni:6.29.3` cannot be downloaded from Maven repository.

@anand1976 I see you created the (Github) release. Do you know why there is no [Maven](https://repo1.maven.org/maven2/org/rocksdb/rocksdbjni/6.29.3) release ?

**Comment by anand1976** [comment] 2022-02-25 17:21
> > @jurmous Has `RockDB 6.29` really been released? I saw the [release notes](https://github.com/facebook/rocksdb/releases/tag/v6.29.3) three days ago, but `rocksdbjni:6.29.3` cannot be downloaded from Maven repository.
> 
> @anand1976 I see you created the (Github) release. Do you know why there is no [Maven](https://repo1.maven.org/maven2/org/rocksdb/rocksdbjni/6.29.3) release ?

@adamretter Do you plan to release the Java binary for 6.29.3 soon?

**Comment by adamretter** [comment] 2022-03-04 14:01
@LuciferYang @anand1976 Current status is commented on here - https://github.com/facebook/rocksdb/pull/9254#issuecomment-1054598516

**Comment by LuciferYang** [comment] 2022-03-07 18:08
Thank you for your reply @adamretter

**Comment by jurmous** [comment] 2022-03-26 09:30
RocksDB 6.29.4.1 has been released to Maven Central which should now work on M1 macs.

**Comment by adamretter** [comment] 2022-03-26 21:10
Additionally now so has version 7.0.3
