### ISSUE TITLE
EventListenerTest.OnFileOperationTest fails on MacOS

### ISSUE THREAD

**Issue by mrambacher** [facebook/rocksdb#7133] opened 2020-07-15 17:43 UTC
The recently added OnFileOperationTest fails on MacOS.  I do not know if this is related to simulated sleeps or something else, but it consistently fails.

[ RUN      ] EventListenerTest.OnFileOperationTest
db/listener_test.cc:1057: Failure
Expected: (duration.count()) > (0), actual: 0 vs 0

### Steps to reproduce the behavior

make dbg
./listener_test

**Comment by mrambacher** [comment] 2020-07-20 21:19
I did some further investigation into this test failure.  The OnFileOperationTest fails on MacOS sometimes when checking the result of the Flush operation.  For Posix File Systems, the flush operation is a no-op (does nothing and just returns OK), which will take very little time.

FWIW, When I added debugging, I noticed that if I use "steady_clock" instead of "system_clock", I no longer see duration of 0.

This leads me to a few questions:
- Should we be using system or steady clock for these calculations?
- Should the Listener struct be storing the "duration" or the start/stop time?

**Comment by riversand963** [comment] 2020-07-20 21:44
Thanks @mrambacher for the investigation. It looks like these tests do not really care about what time it is. It is "duration" that is more meaningful.
@roghnin can you follow up on this?

**Comment by mrambacher** [comment] 2020-07-20 22:40
In my testing on MacOS, duration can be zero for the Flush operation when using system_clock.

**Comment by roghnin** [comment] 2020-07-21 01:19
> In my testing on MacOS, duration can be zero for the Flush operation when using system_clock.

This makes sense to me, but I'm having a hard time trying to reproduce this on my machine. Do you happen to have the call stack of the failed assertion?

**Comment by roghnin** [comment] 2020-07-21 01:51
> In my testing on MacOS, duration can be zero for the Flush operation when using system_clock.

If I got it correctly, the root problem is the behavior of the clock itself. Having the listener store "durations" won't fix the problem, as durations are calculated using timepoints.

I think we need to investigate more about `FileOperationInfo::TimePoint`: it's widely used in RocksDB to keep track of time, and the start and end timestamps are got not just for testing purposes. Maybe we should switch to `steady_clock` in all those cases as it fits better in the role of "stopwatch".

**Comment by mrambacher** [comment] 2020-07-21 03:26
> > In my testing on MacOS, duration can be zero for the Flush operation when using system_clock.
> 
> If I got it correctly, the root problem is the behavior of the clock itself. Having the listener store "durations" won't fix the problem, as durations are calculated using timepoints. Are you worried that having the readings of `steady_clock` stored in Listener doesn't make much sense?

My question is what is the use case where the user would care about the time of the operation versus the duration of the operation?  And given the duration, if they cared about the time, could the approximate it enough on their own (Time::now() - duration?).

**Comment by riversand963** [comment] 2020-07-21 05:32
> > > In my testing on MacOS, duration can be zero for the Flush operation when using system_clock.
> > 
> > 
> > If I got it correctly, the root problem is the behavior of the clock itself. Having the listener store "durations" won't fix the problem, as durations are calculated using timepoints. Are you worried that having the readings of `steady_clock` stored in Listener doesn't make much sense?
> 
> My question is what is the use case where the user would care about the time of the operation versus the duration of the operation? And given the duration, if they cared about the time, could the approximate it enough on their own (Time::now() - duration?).

They could do the approximation on their own in the listener, but this is one more call to `now()`. Currently, the `FileOperationInfo` is on the stack and short-lived, thus I am not too concerned about this extra timestamp in it.

**Comment by riversand963** [comment] 2020-07-21 17:58
Chatted offline, to ensure `duration`, we'd better use steady_clock, as fixed in #7153 . Thanks @mrambacher and @roghnin taking a look at this.

**Closed** 2020-09-29 22:55 UTC
