### ISSUE TITLE
Latency increase seen for point lookups for big endian key prefix format

### ISSUE THREAD

**Issue by tulshiba** [facebook/rocksdb#3780] opened 2018-04-27 01:34 UTC
**Background**
Recently, we started using RocksDB 5.9 to store metadata for an application.
The average value size is about ~1300 bytes and key size can span from 8 to 20 bytes.
The key is made up of a prefix which is 8 bytes. 

We convert a 64 bit integer to big-endian representation when creating the key and use it as the key prefix. This ensures that all the keys with the same unique prefix are co-located.

Need for big-endian key prefix representation example:

Consider 1234 and 1235. Their little-endian representations would be 0xD204000000000000 and 0xD304000000000000. If stored in this format, all the keys from 0xD205000000000000 (1490) to 0xD303000000000000 (979) would be sorted in between 1234 and 1235 by a lexicographic
comparator (the default used by RocksDB). With big-endian representation, this problem is avoided. The keys would be stored as 0x00000000000004D2 and 0x00000000000004D3 and the sorting would as expected.

**Perf Issue**
One issue we have seen with this setup is that when we use big endian format key prefix
we see very high single lookup latencies(avg 550-600us). On the contrary, when we use little endian format key prefix we see it to be 3 times lower (avg 190-210us).

Digging more into this, we found that bloom filters did not work well with big endian key prefix format resulting into multiple bloom filter false positives and thus leading to higher read latencies. On the little endian key prefix front , false positive rate was seen to have gone down significantly giving us much lower single lookup latencies.

NOTE that the underlying architecture is still little endian. 

**Reproduce the issue**
To reproduce the issue, we have created a small patch for db_bench tool. It helps load data and perform reads using little endian or big endian key prefix format (uses a gflag).

At a high level, the patch writes 550K records randomly. And in the read benchmark performs 100K single lookups (550K and 100K are hard coded.)

Following are the steps to run db_bench (other gflags are set based on our requirements)

Apply the patch provided ..
```
$ cd rocksdb
$ patch tools/db_bench_tool.cc db_bench.patch
```
Actual db_bench runs ..

Little endian key prefix format
```
Step 1. Load data in little endian format
db_bench --db=/home/db_bench_le --use_existing_db=0 --benchmarks=filluniquerandom --statistics=1 --histogram=1 --threads=1 --key_size=8 --batch_size=1 --value_size=1330 --num=550000 --cache_size=8388608 --cache_numshardbits=10 --disable_wal=1 --bloom_bits=10 --open_files=-1 --verify_checksum=1 --max_write_buffer_number=2 --allow_concurrent_memtable_write=1 --min_write_buffer_number_to_merge=2 --block_size=4096 --target_file_size_base=134217728 --compaction_style=1 --compression_type=none --stats_per_interval=5 --report_bg_io_stats=1 --perf_level=3 --statistics=1 --cache_high_pri_pool_ratio=0 --seek_nexts=0 --use_direct_reads=1 --use_direct_io_for_flush_and_compaction=1 --table_cache_numshardbits=6 --delayed_write_rate=16777216 --hard_pending_compaction_bytes_limit=274877906944 --max_compaction_bytes=1677721600 --target_file_size_base=67108864 --fifo_compaction_allow_compaction=false --fifo_compaction_max_table_files_size_mb=1073 --benchmark_write_rate_limit=20971520 --enable_pipelined_write=false --disable_auto_compactions=1 --level0_slowdown_writes_trigger=20 --level0_stop_writes_trigger=36 --partition_index_and_filters=true --num_levels=1 --cache_high_pri_pool_ratio=1

Step 2. Point lookups using little endian format
db_bench --db=/home/db_bench_le --use_existing_db=1 --benchmarks=multireadrandom --statistics=1 --histogram=1 --threads=1 --key_size=30 --batch_size=1 --value_size=1300 --num=700000 --cache_size=12582912 --cache_numshardbits=2 --disable_wal=1 --bloom_bits=10 --open_files=-1 --verify_checksum=1 --max_write_buffer_number=2 --allow_concurrent_memtable_write=1 --min_write_buffer_number_to_merge=2 --block_size=4096 --target_file_size_base=134217728 --compaction_style=1 --compression_type=none --stats_per_interval=5 --report_bg_io_stats=1 --perf_level=3 --statistics=1 --seek_nexts=0 --use_direct_reads=1 --use_direct_io_for_flush_and_compaction=1 --table_cache_numshardbits=6 --delayed_write_rate=16777216 --hard_pending_compaction_bytes_limit=274877906944 --max_compaction_bytes=1677721600 --target_file_size_base=67108864 --fifo_compaction_allow_compaction=false --fifo_compaction_max_table_files_size_mb=1073 --benchmark_write_rate_limit=20971520 --enable_pipelined_write=false --disable_auto_compactions=1 --level0_slowdown_writes_trigger=20 --level0_stop_writes_trigger=36 --partition_index_and_filters=true --num_levels=1 --cache_high_pri_pool_ratio=1
```

Big endian key prefix format
```
Step 1. Load data big endian format
`which db_bench` --db=/home/db_bench_be --use_existing_db=0 --benchmarks=filluniquerandom --statistics=1 --histogram=1 --threads=1 --key_size=8 --batch_size=1 --value_size=1330 --num=550000 --cache_size=8388608 --cache_numshardbits=10 --disable_wal=1 --bloom_bits=10 --open_files=-1 --verify_checksum=1 --max_write_buffer_number=2 --allow_concurrent_memtable_write=1 --min_write_buffer_number_to_merge=2 --block_size=4096 --target_file_size_base=134217728 --compaction_style=1 --compression_type=none --stats_per_interval=5 --report_bg_io_stats=1 --perf_level=3 --statistics=1 --cache_high_pri_pool_ratio=0 --seek_nexts=0 --use_direct_reads=1 --use_direct_io_for_flush_and_compaction=1 --table_cache_numshardbits=6 --delayed_write_rate=16777216 --hard_pending_compaction_bytes_limit=274877906944 --max_compaction_bytes=1677721600 --target_file_size_base=67108864 --fifo_compaction_allow_compaction=false --fifo_compaction_max_table_files_size_mb=1073 --benchmark_write_rate_limit=20971520 --enable_pipelined_write=false --disable_auto_compactions=1 --level0_slowdown_writes_trigger=20 --level0_stop_writes_trigger=36 --partition_index_and_filters=true --num_levels=1 --cache_high_pri_pool_ratio=1 --use_le_format=false

Step 2. Point lookups big endian format
`which db_bench` --db=/home/db_bench_be --use_existing_db=1 --benchmarks=multireadrandom --statistics=1 --histogram=1 --threads=1 --key_size=30 --batch_size=1 --value_size=1300 --num=700000 --cache_size=12582912 --cache_numshardbits=2 --disable_wal=1 --bloom_bits=10 --open_files=-1 --verify_checksum=1 --max_write_buffer_number=2 --allow_concurrent_memtable_write=1 --min_write_buffer_number_to_merge=2 --block_size=4096 --target_file_size_base=134217728 --compaction_style=1 --compression_type=none --stats_per_interval=5 --report_bg_io_stats=1 --perf_level=3 --statistics=1 --seek_nexts=0 --use_direct_reads=1 --use_direct_io_for_flush_and_compaction=1 --table_cache_numshardbits=6 --delayed_write_rate=16777216 --hard_pending_compaction_bytes_limit=274877906944 --max_compaction_bytes=1677721600 --target_file_size_base=67108864 --fifo_compaction_allow_compaction=false --fifo_compaction_max_table_files_size_mb=1073 --benchmark_write_rate_limit=20971520 --enable_pipelined_write=false --disable_auto_compactions=1 --level0_slowdown_writes_trigger=20 --level0_stop_writes_trigger=36 --partition_index_and_filters=true --num_levels=1 --cache_high_pri_pool_ratio=1 --use_le_format=false
```

**Read op results**
Little Endian key prefix format

```
multireadrandom :     182.005 micros/op 5494 ops/sec; (100000 of 100000 found)
Microseconds per read:
Count: 100000 Average: 182.0049  StdDev: 138.35
Min: 118  Median: 159.3722  Max: 36322
Percentiles: P50: 159.37 P75: 204.44 P99: 458.98 P99.9: 1007.10 P99.99: 2483.33
------------------------------------------------------
(     110,     170 ]    60763  60.763%  60.763% ############
(     170,     250 ]    33074  33.074%  93.837% #######
(     250,     380 ]     4712   4.712%  98.549% #
(     380,     580 ]     1142   1.142%  99.691%
(     580,     870 ]      187   0.187%  99.878%
(     870,    1300 ]       69   0.069%  99.947%
(    1300,    1900 ]       36   0.036%  99.983%
(    1900,    2900 ]       12   0.012%  99.995%
(    2900,    4400 ]        1   0.001%  99.996%
(    4400,    6600 ]        2   0.002%  99.998%
(    6600,    9900 ]        1   0.001%  99.999%
(   33000,   50000 ]        1   0.001% 100.000%
```

Big endian key prefix format

```
multireadrandom :     572.498 micros/op 1746 ops/sec; (100000 of 100000 found)
Microseconds per read:
Count: 100000 Average: 572.4989  StdDev: 409.09
Min: 119  Median: 527.9956  Max: 29025
Percentiles: P50: 528.00 P75: 789.16 P99: 1685.32 P99.9: 3437.74 P99.99: 12360.00
------------------------------------------------------
(     110,     170 ]    12440  12.440%  12.440% ##
(     170,     250 ]     5557   5.557%  17.997% #
(     250,     380 ]    15981  15.981%  33.978% ###
(     380,     580 ]    21652  21.652%  55.630% ####
(     580,     870 ]    26856  26.856%  82.486% #####
(     870,    1300 ]    15342  15.342%  97.828% ###
(    1300,    1900 ]     1825   1.825%  99.653%
(    1900,    2900 ]      228   0.228%  99.881%
(    2900,    4400 ]       53   0.053%  99.934%
(    4400,    6600 ]       22   0.022%  99.956%
(    6600,    9900 ]       25   0.025%  99.981%
(    9900,   14000 ]       15   0.015%  99.996%
(   14000,   22000 ]        2   0.002%  99.998%
(   22000,   33000 ]        2   0.002% 100.000%
```

**Config**
```
RocksDB:    version 5.9
Date:       Thu Apr 26 17:28:59 2018
CPU:        8 * Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
CPUCache:   20480 KB
Keys:       30 bytes each
Values:     1300 bytes each (650 bytes after compression)
Entries:    700000
Prefix:    0 bytes
Keys per prefix:    0
RawSize:    887.9 MB (estimated)
FileSize:   453.9 MB (estimated)
Write rate: 20971520 bytes/second
Read rate: 0 ops/second
Compression: NoCompression
Memtablerep: skip_list
Perf Level: 3
```

We have not looked deeper on why bloom filters in big endian key prefix format case don't work well ? First step is to find out if this is a known issue or setup issue or something very primitive ?

So,
1. Do you see something obvious in our settings that might be causing this issue .?
2. Any suggestions or workarounds .?

**Comment by tulshiba** [comment] 2018-04-27 01:37
I'm attaching the patch in this comment --
[db_bench.txt](https://github.com/facebook/rocksdb/files/1953540/db_bench.txt)

**Comment by tulshiba** [comment] 2018-04-27 01:39
@maysamyabandeh - I saw your updates on the Bloom Filter page. Do you see anything obvious in the above issue .? Thanks!

**Comment by maysamyabandeh** [comment] 2018-05-02 16:19
Thanks for the report. The issue message was a bit too long and I am not sure if I have got the main point. It would a good practice to keep the issue report concise and to-the-point.
If I understood correctly you seem to observe large bloom false positive rate with a specific key format.
1. Is "rocksdb.bloom.filter.useful" different between the two key format?
2. Can you reproduce this by changing the key format in FalsePositiveRate function used by TEST_F(FullBloomTest, FullVaryingLengths)?

**Comment by cdkamat** [comment] 2018-05-02 23:12
@maysamyabandeh some clarifications below, hope these help -

For the DB descried in this issue, we are directly using an int64_t as the key. The two formats are 

Format 1:

```
  const int64_t i; //  This can be any positive int64 number
  const int64_t i_be = htobe64(i); // converts i to big endian representation
  memcpy(buffer, reinterpret_cast<const char *>(&i_be), sizeof(i_be));
  Slice key = Slice(buffer, sizeof(i_be));
```

Format 2: 

```
  const int64_t i; // This can be any positive int64 number.
  memcpy(buffer, reinterpret_cast<const char *>(&i), sizeof(i));
  Slice key = Slice(buffer, sizeof(i));
```

As @tulshiba mentioned, we see that Format 1 has bad Bloom filter performance with significantly higher false positives rates than Format 2. This causes The DB with Format 1 to frequently access multiple on disk data blocks during Get and MultiGet operations. 

Yes, "rocksdb.bloom.filter.useful" is different between the two formats.

**Comment by maysamyabandeh** [comment] 2018-05-03 15:19
Thanks for the succinct summary. I could not reproduce this unfortunately. Can you try reproducing it with FullBloomTest.FullVaryingLengths?
```
$ git diff
diff --git a/util/bloom_test.cc b/util/bloom_test.cc
index bbf1d3a..d2451c7 100644
--- a/util/bloom_test.cc
+++ b/util/bloom_test.cc
@@ -34,10 +34,9 @@ namespace rocksdb {
 static const int kVerbose = 1;

 static Slice Key(int i, char* buffer) {
-  std::string s;
-  PutFixed32(&s, static_cast<uint32_t>(i));
-  memcpy(buffer, s.c_str(), sizeof(i));
-  return Slice(buffer, sizeof(i));
+  const int64_t i_be = htobe64(i);  // converts i to big endian representation
+  memcpy(buffer, reinterpret_cast<const char*>(&i_be), sizeof(i_be));
+  return Slice(buffer, sizeof(i_be));
 }

 static int NextLength(int length) {
```
```
$ ./bloom_test --gtest_filter=FullBloomTest.FullVaryingLengths
[       OK ] FullBloomTest.FullVaryingLengths (15 ms)
```

**Comment by cdkamat** [comment] 2018-05-03 15:33
I tried the same and wasn't able to repro it either. However, we definitely see the issue in our test deployments. I am not sure if the test is able to accurately simulate the distribution of keys we see in our SST files. Let me try to read a few of them and get a better simulation of the pattern of keys where we see this issue. Also, we are using Partitioned BloomFilters in our deployment. Does that have any effect on the hit rate? Are there any tests that target Partitioned BloomFilters?

**Comment by maysamyabandeh** [comment] 2018-05-03 16:07
If the suspect is the partitioned blooms then it should be feasible to try disabling it in your test cluster and see if the problem persists.
TEST_P(DBBloomFilterTestWithParam, BloomFilter) covers all the types of bloom filters.

**Comment by maysamyabandeh** [comment] 2018-07-27 18:56
Closing it since there is no clear path for followup.

**Closed by maysamyabandeh** 2018-07-27 18:56 UTC
