### ISSUE TITLE
Error when building: undefined reference to `malloc_stats_print'

### ISSUE THREAD

**Issue by George3d6** [facebook/rocksdb#3908] opened 2018-05-26 19:32 UTC
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior

Moving into the examples dir and trying to build should build example.

### Actual behavior

Running make in the examples dir outputs the following error:

`
cd .. && make static_lib
make[1]: Entering directory '/home/george/distributed_cache/rocksdb'
  GEN      util/build_version.cc
make[1]: Nothing to be done for 'static_lib'.
make[1]: Leaving directory '/home/george/distributed_cache/rocksdb'
g++ -fno-rtti simple_example.cc -osimple_example ../librocksdb.a -I../include -O2 -std=c++11 -lpthread -lrt -lsnappy -lz -lbz2 -llz4 -lzstd -lnuma -ltbb -std=c++11  -DROCKSDB_PLATFORM_POSIX -DROCKSDB_LIB_IO_POSIX  -DOS_LINUX -fno-builtin-memcmp -DROCKSDB_FALLOCATE_PRESENT -DSNAPPY -DZLIB -DBZIP2 -DLZ4 -DZSTD -DNUMA -DTBB -DROCKSDB_MALLOC_USABLE_SIZE -DROCKSDB_PTHREAD_ADAPTIVE_MUTEX -DROCKSDB_BACKTRACE -DROCKSDB_RANGESYNC_PRESENT -DROCKSDB_SCHED_GETCPU_PRESENT -march=native  -DHAVE_SSE42 -DHAVE_PCLMUL -DROCKSDB_SUPPORT_THREAD_LOCAL -DROCKSDB_JEMALLOC -DJEMALLOC_NO_DEMANGLE    -lpthread
../librocksdb.a(malloc_stats.o): In function `rocksdb::DumpMallocStats(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)':
/home/george/distributed_cache/rocksdb/db/malloc_stats.cc:51: undefined reference to `malloc_stats_print'
collect2: error: ld returned 1 exit status
make: *** [Makefile:20: simple_example] Error 1
`

### Steps to reproduce the behavior

```
cd rocksdb
make static_lib
cd examples
make
```

I have the same issue when linking with my own executable (but I tried it using the examples, since that's pressumably easier to reproduce).

Some more info (please ask for any if needed)

Compiler: g++ (GCC) 7.3.1 20180312
Jemalloc version: 5.0.1-0-g896ed3a8b3f41998d4fb4d625d30ac63ef2d51fb (as provided by mallctl)

**Comment by jmininger** [comment] 2018-05-26 23:49
I am having the same issue on my mac when I try to build the files in rocksdb/examples:
```$ cd rocksdb/examples
$ make all
cd .. && /Applications/Xcode.app/Contents/Developer/usr/bin/make static_lib
  GEN      util/build_version.cc
make[1]: Nothing to be done for `static_lib'.
g++ -fno-rtti simple_example.cc -osimple_example ../librocksdb.a -I../include -O2 -std=c++11 -lsnappy -lgflags -lz -lbz2 -llz4 -ltbb -std=c++11  -DROCKSDB_PLATFORM_POSIX -DROCKSDB_LIB_IO_POSIX  -DOS_MACOSX -DSNAPPY -DGFLAGS=1 -DZLIB -DBZIP2 -DLZ4 -DTBB -DROCKSDB_BACKTRACE -Wshorten-64-to-32 -march=native  -DHAVE_SSE42 -DHAVE_PCLMUL -DROCKSDB_SUPPORT_THREAD_LOCAL -DROCKSDB_JEMALLOC -DJEMALLOC_NO_DEMANGLE    -lpthread
Undefined symbols for architecture x86_64:
  "_malloc_stats_print", referenced from:
      rocksdb::DumpMallocStats(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) in librocksdb.a(malloc_stats.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [simple_example] Error 1```

```$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin```

**Comment by riversand963** [comment] 2018-06-07 06:00
@George3d6 @jmininger Thanks for your posts.
Did you install jemalloc with standard package management system, or is it a locally built one? I cannot reproduce your error on my linux server with jemalloc installed with `yum`. What is your machine's OS version @George3d6 ?
That said, I suspect this is not a bug in RocksDB code. Since we use Github issues exclusively for bug tracking and we have been trying to reduce the number of open issues, I highly recommend that you migrate this post and continue the discussion in our dedicated Facebook group, RocksDB Developers Public. For now, I'm going to close this issue, and thanks for your understanding.

p.s. we can always reopen this issue if it turns out to be a bug. :)

**Closed by riversand963** 2018-06-07 06:00 UTC

**Comment by yunchih** [comment] 2019-02-18 13:20
Add `-ljemalloc` to the `PLATFORM_LDFLAGS` variable in `make_config.mk`
