### ISSUE TITLE
Java byte array max size check before copying long-sized data from jni bridge

### ISSUE THREAD

**Issue by azagrebin** [facebook/rocksdb#3849] opened 2018-05-14 15:09 UTC
This issue partially addresses #2383.

When user merges a lot of data into one value, its size might grow indefinitely.
When user gets the value as byte[] in java client, its actual merged size might exceed the JVM limitation for returned java array size.

Currently size of java array is calculated just by explicit cast of underlying size_t of value:
https://github.com/facebook/rocksdb/blob/66c7aa32fbc591c0c766024ff51aecd3f1a8f3e1/java/rocksjni/portal.h#L4297

The problem is that if `bytes.size()` exceeds java 32b int, it leads to overflow of `jlen` which might be even negative. The result can be an unclear `NegativeArraySizeException`/`ArrayIndexOutOfBoundsException` at the user side.

The suggestion is to check the size overflow and throw more clear RocksDBException with problem description:
```
static jbyteArray createJavaByteArrayWithSizeCheck(JNIEnv* env, const char* bytes, const size_t size) {
      // Limitation for array size is vm specific
      // Current HotSpot VM limitation for array size is Integer.MAX_VALUE - 5 (2^31 - 1 - 5)
      // Integer.MAX_VALUE - 8 should be safe enough
      static const size_t MAX_JARRAY_SIZE = ((static_cast<size_t>(1)) << 31) - 9;
      if (size > MAX_JARRAY_SIZE) {
        rocksdb::RocksDBExceptionJni::ThrowNew(env, "Requested array size exceeds VM limit");
        return nullptr;
      }
      // return normal result
}
```

**Comment by adamretter** [comment] 2018-05-14 19:02
I agree that the error should be as clear as possible, but I wonder if if is not more appropriate to throw a `ArrayIndexOutOfBoundsException` with your error message, rather than a `RocksDBException`? The problem is really a bounds issue IMHO.

**Comment by azagrebin** [comment] 2018-05-15 08:48
thanks @adamretter, I can change PR to use `ArrayIndexOutOfBoundsException`. There are just some thoughts behind current PR I wanted to share.

My thinking was inspired by java `OutOfMemoryError` which could be also an option:
```
public class Foo {
   public static void main(String[] args) {
     byte[] array = new byte[Integer.MAX_VALUE];
   }
 }
$ javac Foo.java ; java Foo
Exception in thread "main" java.lang.OutOfMemoryError: Requested array size exceeds VM limit
	at Foo.main(Foo.java:3)
```

I used `RocksDBException` because the check and error come from RocksDB jni API but not from JVM.

**Comment by azagrebin** [comment] 2018-07-03 10:39
@adamretter 
I think last PR addressed the issue. I guess we can close the issue?

**Comment by adamretter** [comment] 2018-07-06 05:30
Closed by https://github.com/facebook/rocksdb/pull/3850

**Closed by adamretter** 2018-07-06 05:30 UTC
Labels: java-api
