### ISSUE TITLE
Benchmark readrandom shows Zero data being read using benchmark.sh tool.

### ISSUE THREAD

**Issue by hgdesai** [facebook/rocksdb#9536] opened 2022-02-09 21:11 UTC
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
While running readrandom benchmark it should show some throughput
### Actual behavior
While running readrandom benchmark it shows 0.00 throughput.
### Steps to reproduce the behavior
1) Issue command as follows
 NUM_KEYS=900000000 CACHE_SIZE=6442450944 DURATION=5400 /root/rocksdb-6.28.2/tools/./benchmark.sh readrandom --stats_per_interval=1
2) The out will shows all zero as below.
./db_bench --benchmarks=compact --use_existing_db=1 --disable_auto_compactions=1 --sync=0 --level0_file_num_compaction_trigger=4 --level0_stop_writes_trigger=20 --max_background_compactions=16 --max_write_buffer_number=8 --max_background_flushes=7 --db=/mnt/nvme0n/db --wal_dir=/mnt/nvme0n/wal --num=900000000 --num_levels=6 --key_size=20 --value_size=400 --block_size=8192 --cache_size=6442450944 --cache_numshardbits=6 --compression_max_dict_bytes=0 --compression_ratio=0.5 --compression_type=zstd --level_compaction_dynamic_level_bytes=true --bytes_per_sync=8388608 --cache_index_and_filter_blocks=0 --pin_l0_filter_and_index_blocks_in_cache=1 --benchmark_write_rate_limit=0 --hard_rate_limit=3 --rate_limit_delay_max_milliseconds=1000000 --write_buffer_size=134217728 --target_file_size_base=134217728 --max_bytes_for_level_base=1073741824 --verify_checksum=1 --delete_obsolete_files_period_micros=62914560 --max_bytes_for_level_multiplier=8 --statistics=0 --stats_per_interval=1 --stats_interval_seconds=60 --histogram=1 --memtablerep=skip_list --bloom_bits=10 --open_files=-1 --stats_per_interval=1 --duration=5400 --threads=1 2>&1 | tee -a /tmp/benchmark_bulkload_compact.log
RocksDB:    version 6.28
Date:       Wed Feb  9 14:49:32 2022
CPU:        4 * Intel(R) Xeon(R) CPU E5-2407 v2 @ 2.40GHz
CPUCache:   10240 KB
^C
[root@RocksDBNew rocksdb-6.28.2]# NUM_KEYS=900000000 CACHE_SIZE=6442450944 DURATION=5400 /root/rocksdb-6.28.2/tools/./benchmark.sh readrandom --stats_per_interval=1
===== Benchmark =====
Starting readrandom (ID: ) at Wed Feb  9 14:52:28 CST 2022
Reading 900000000 random keys
./db_bench --benchmarks=readrandom --use_existing_db=1 --level0_file_num_compaction_trigger=4 --level0_stop_writes_trigger=20 --max_background_compactions=16 --max_write_buffer_number=8 --max_background_flushes=7 --db=/mnt/nvme0n/db --wal_dir=/mnt/nvme0n/wal --num=900000000 --num_levels=6 --key_size=20 --value_size=400 --block_size=8192 --cache_size=6442450944 --cache_numshardbits=6 --compression_max_dict_bytes=0 --compression_ratio=0.5 --compression_type=zstd --level_compaction_dynamic_level_bytes=true --bytes_per_sync=8388608 --cache_index_and_filter_blocks=0 --pin_l0_filter_and_index_blocks_in_cache=1 --benchmark_write_rate_limit=0 --hard_rate_limit=3 --rate_limit_delay_max_milliseconds=1000000 --write_buffer_size=134217728 --target_file_size_base=134217728 --max_bytes_for_level_base=1073741824 --verify_checksum=1 --delete_obsolete_files_period_micros=62914560 --max_bytes_for_level_multiplier=8 --statistics=0 --stats_per_interval=1 --stats_interval_seconds=60 --histogram=1 --memtablerep=skip_list --bloom_bits=10 --open_files=-1 --stats_per_interval=1 --duration=5400 --threads=64 --seed=1644439948 2>&1 | tee -a /tmp/benchmark_readrandom.t64.log
RocksDB:    version 6.28
Date:       Wed Feb  9 14:52:29 2022
CPU:        4 * Intel(R) Xeon(R) CPU E5-2407 v2 @ 2.40GHz
CPUCache:   10240 KB
2022/02/09-14:53:30  ... thread 18: (4000,4000) ops and (65.8,65.8) ops/second in (60.801993,60.801993) seconds
2022/02/09-14:53:30  ... thread 9: (4000,4000) ops and (65.3,65.3) ops/second in (61.236365,61.236365) seconds
2022/02/09-14:53:30  ... thread 51: (4000,4000) ops and (65.3,65.3) ops/second in (61.240304,61.240304) seconds
2022/02/09-14:53:31  ... thread 55: (4000,4000) ops and (64.3,64.3) ops/second in (62.226478,62.226478) seconds
2022/02/09-14:53:31  ... thread 56: (4000,4000) ops and (64.3,64.3) ops/second in (62.249309,62.249309) seconds
2022/02/09-14:53:31  ... thread 43: (4000,4000) ops and (64.2,64.2) ops/second in (62.295809,62.295809) seconds
2022/02/09-14:53:31  ... thread 36: (4000,4000) ops and (64.1,64.1) ops/second in (62.364853,62.364853) seconds
2022/02/09-14:53:32  ... thread 34: (4000,4000) ops and (64.1,64.1) ops/second in (62.376738,62.376738) seconds
2022/02/09-14:53:32  ... thread 1: (4000,4000) ops and (64.1,64.1) ops/second in (62.442401,62.442401) seconds
2022/02/09-14:53:32  ... thread 38: (4000,4000) ops and (64.0,64.0) ops/second in (62.459260,62.459260) seconds
2022/02/09-14:53:32  ... thread 14: (4000,4000) ops and (64.0,64.0) ops/second in (62.470300,62.470300) seconds
2022/02/09-14:53:32  ... thread 24: (4000,4000) ops and (63.8,63.8) ops/second in (62.742345,62.742345) seconds
2022/02/09-14:53:32  ... thread 39: (4000,4000) ops and (63.7,63.7) ops/second in (62.747539,62.747539) seconds
2022/02/09-14:53:32  ... thread 52: (4000,4000) ops and (63.7,63.7) ops/second in (62.748270,62.748270) seconds
2022/02/09-14:53:32  ... thread 4: (4000,4000) ops and (63.7,63.7) ops/second in (62.769800,62.769800) seconds
2022/02/09-14:53:32  ... thread 27: (4000,4000) ops and (63.6,63.6) ops/second in (62.914239,62.914239) seconds
2022/02/09-14:53:32  ... thread 46: (4000,4000) ops and (63.6,63.6) ops/second in (62.921527,62.921527) seconds
2022/02/09-14:53:32  ... thread 11: (4000,4000) ops and (63.5,63.5) ops/second in (62.956578,62.956578) seconds
2022/02/09-14:53:32  ... thread 33: (4000,4000) ops and (63.5,63.5) ops/second in (62.999484,62.999484) seconds
2022/02/09-14:53:32  ... thread 41: (4000,4000) ops and (63.5,63.5) ops/second in (62.999012,62.999012) seconds
2022/02/09-14:53:32  ... thread 53: (4000,4000) ops and (63.4,63.4) ops/second in (63.100899,63.100899) seconds
2022/02/09-14:53:32  ... thread 15: (4000,4000) ops and (63.3,63.3) ops/second in (63.142766,63.142766) seconds
2022/02/09-14:53:32  ... thread 0: (4000,4000) ops and (63.3,63.3) ops/second in (63.158603,63.158603) seconds

** Compaction Stats [default] **
Level    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) CompMergeCPU(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop Rblob(GB) Wblob(GB)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  L0   1011/1011 54.87 GB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0       0.0       0.0
 Sum   1011/1011 54.87 GB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0       0.0       0.0
 Int      0/0    0.00 KB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0       0.0       0.0

** Compaction Stats [default] **
Priority    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) CompMergeCPU(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop Rblob(GB) Wblob(GB)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Blob file count: 0, total size: 0.0 GB

Uptime(secs): 63.9 total, 63.2 interval
Flush(GB): cumulative 0.000, interval 0.000
AddFile(GB): cumulative 0.000, interval 0.000
AddFile(Total Files): cumulative 0, interval 0
AddFile(L0 Files): cumulative 0, interval 0
AddFile(Keys): cumulative 0, interval 0
Cumulative compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
Interval compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
Stalls(count): 0 level0_slowdown, 0 level0_slowdown_with_compaction, 1 level0_numfiles, 0 level0_numfiles_with_compaction, 0 stop for pending_compaction_bytes, 0 slowdown for pending_compaction_bytes, 0 memtable_compaction, 0 memtable_slowdown, interval 0 total count
Block cache LRUCache@0x28a68e0#11433 capacity: 6.00 GB collections: 1 last_copies: 0 last_secs: 6.2e-05 secs_since: 63
Block cache entry stats(count,size,portion): Misc(1,0.00 KB,0%)

** File Read Latency Histogram By Level [default] **

** DB Stats **
Uptime(secs): 63.9 total, 63.2 interval
Cumulative writes: 0 writes, 0 keys, 0 commit groups, 0.0 writes per commit group, ingest: 0.00 GB, 0.00 MB/s
Cumulative WAL: 0 writes, 0 syncs, 0.00 writes per sync, written: 0.00 GB, 0.00 MB/s
Cumulative stall: 00:00:0.000 H:M:S, 0.0 percent
Interval writes: 0 writes, 0 keys, 0 commit groups, 0.0 writes per commit group, ingest: 0.00 MB, 0.00 MB/s
Interval WAL: 0 writes, 0 syncs, 0.00 writes per sync, written: 0.00 GB, 0.00 MB/s
Interval stall: 00:00:0.000 H:M:S, 0.0 percent

2022/02/09-14:53:32  ... thread 7: (4000,4000) ops and (63.3,63.3) ops/second in (63.173675,63.173675) seconds
2022/02/09-14:53:32  ... thread 32: (4000,4000) ops and (63.3,63.3) ops/second in (63.186924,63.186924) seconds
2022/02/09-14:53:32  ... thread 37: (4000,4000) ops and (63.3,63.3) ops/second in (63.189937,63.189937) seconds
2022/02/09-14:53:32  ... thread 29: (4000,4000) ops and (63.3,63.3) ops/second in (63.193886,63.193886) seconds
2022/02/09-14:53:32  ... thread 47: (4000,4000) ops and (63.3,63.3) ops/second in (63.230659,63.230659) seconds
2022/02/09-14:53:32  ... thread 60: (4000,4000) ops and (63.3,63.3) ops/second in (63.239993,63.239993) seconds
2022/02/09-14:53:32  ... thread 42: (4000,4000) ops and (63.2,63.2) ops/second in (63.245449,63.245449) seconds
2022/02/09-14:53:32  ... thread 12: (4000,4000) ops and (63.2,63.2) ops/second in (63.256196,63.256196) seconds
2022/02/09-14:53:32  ... thread 48: (4000,4000) ops and (63.2,63.2) ops/second in (63.282328,63.282328) seconds
2022/02/09-14:53:32  ... thread 45: (4000,4000) ops and (63.2,63.2) ops/second in (63.304245,63.304245) seconds
2022/02/09-14:53:32  ... thread 44: (4000,4000) ops and (63.2,63.2) ops/second in (63.329122,63.329122) seconds
2022/02/09-14:53:33  ... thread 26: (4000,4000) ops and (63.1,63.1) ops/second in (63.380510,63.380510) seconds
2022/02/09-14:53:33  ... thread 5: (4000,4000) ops and (63.1,63.1) ops/second in (63.400625,63.400625) seconds
2022/02/09-14:53:33  ... thread 31: (4000,4000) ops and (63.1,63.1) ops/second in (63.441102,63.441102) seconds
2022/02/09-14:53:33  ... thread 49: (4000,4000) ops and (63.0,63.0) ops/second in (63.488001,63.488001) seconds
2022/02/09-14:53:33  ... thread 62: (4000,4000) ops and (63.0,63.0) ops/second in (63.496381,63.496381) seconds
2022/02/09-14:53:33  ... thread 2: (4000,4000) ops and (63.0,63.0) ops/second in (63.499017,63.499017) seconds
2022/02/09-14:53:33  ... thread 6: (4000,4000) ops and (63.0,63.0) ops/second in (63.498909,63.498909) seconds
2022/02/09-14:53:33  ... thread 50: (4000,4000) ops and (63.0,63.0) ops/second in (63.521001,63.521001) seconds
2022/02/09-14:53:33  ... thread 21: (4000,4000) ops and (62.9,62.9) ops/second in (63.543680,63.543680) seconds
2022/02/09-14:53:33  ... thread 19: (4000,4000) ops and (62.9,62.9) ops/second in (63.558017,63.558017) seconds
2022/02/09-14:53:33  ... thread 35: (4000,4000) ops and (62.9,62.9) ops/second in (63.569807,63.569807) seconds
2022/02/09-14:53:33  ... thread 22: (4000,4000) ops and (62.8,62.8) ops/second in (63.683277,63.683277) seconds
2022/02/09-14:53:33  ... thread 59: (4000,4000) ops and (62.8,62.8) ops/second in (63.686114,63.686114) seconds
2022/02/09-14:53:33  ... thread 28: (4000,4000) ops and (62.8,62.8) ops/second in (63.690624,63.690624) seconds
2022/02/09-14:53:33  ... thread 16: (4000,4000) ops and (62.8,62.8) ops/second in (63.707281,63.707281) seconds
2022/02/09-14:53:33  ... thread 23: (5000,5000) ops and (78.4,78.4) ops/second in (63.739302,63.739302) seconds
2022/02/09-14:53:33  ... thread 40: (4000,4000) ops and (62.7,62.7) ops/second in (63.762464,63.762464) seconds
2022/02/09-14:53:33  ... thread 58: (4000,4000) ops and (62.7,62.7) ops/second in (63.799706,63.799706) seconds
2022/02/09-14:53:33  ... thread 30: (4000,4000) ops and (62.4,62.4) ops/second in (64.065361,64.065361) seconds
2022/02/09-14:53:33  ... thread 20: (4000,4000) ops and (62.4,62.4) ops/second in (64.089768,64.089768) seconds
2022/02/09-14:53:33  ... thread 63: (4000,4000) ops and (62.4,62.4) ops/second in (64.145001,64.145001) seconds
2022/02/09-14:53:34  ... thread 25: (4000,4000) ops and (62.0,62.0) ops/second in (64.481604,64.481604) seconds
2022/02/09-14:53:34  ... thread 8: (4000,4000) ops and (61.9,61.9) ops/second in (64.592692,64.592692) seconds
2022/02/09-14:53:34  ... thread 3: (4000,4000) ops and (61.9,61.9) ops/second in (64.595097,64.595097) seconds
2022/02/09-14:53:34  ... thread 57: (4000,4000) ops and (61.9,61.9) ops/second in (64.670631,64.670631) seconds
2022/02/09-14:53:34  ... thread 17: (4000,4000) ops and (61.8,61.8) ops/second in (64.764260,64.764260) seconds
2022/02/09-14:53:34  ... thread 61: (4000,4000) ops and (61.6,61.6) ops/second in (64.966914,64.966914) seconds
2022/02/09-14:53:34  ... thread 54: (4000,4000) ops and (61.5,61.5) ops/second in (64.988949,64.988949) seconds
2022/02/09-14:53:35  ... thread 10: (4000,4000) ops and (61.1,61.1) ops/second in (65.474888,65.474888) seconds
2022/02/09-14:53:42  ... thread 13: (5000,5000) ops and (69.0,69.0) ops/second in (72.423090,72.423090) seconds
2022/02/09-14:54:34  ... thread 51: (5000,9000) ops and (79.1,72.3) ops/second in (63.183225,124.423529) seconds
2022/02/09-14:54:34  ... thread 55: (5000,9000) ops and (80.3,72.3) ops/second in (62.293824,124.520302) seconds
2022/02/09-14:54:34  ... thread 9: (5000,9000) ops and (78.7,72.1) ops/second in (63.506265,124.742630) seconds
2022/02/09-14:54:34  ... thread 18: (5000,9000) ops and (78.2,72.1) ops/second in (63.959533,124.761526) seconds
2022/02/09-14:54:34  ... thread 43: (5000,9000) ops and (80.0,72.1) ops/second in (62.504404,124.800213) seconds
2022/02/09-14:54:34  ... thread 36: (5000,9000) ops and (79.9,72.0) ops/second in (62.611060,124.975913) seconds
2022/02/09-14:54:34  ... thread 52: (5000,9000) ops and (80.2,71.9) ops/second in (62.366696,125.114966) seconds
2022/02/09-14:54:34  ... thread 38: (5000,9000) ops and (79.7,71.9) ops/second in (62.705438,125.164698) seconds
2022/02/09-14:54:34  ... thread 53: (5000,9000) ops and (80.4,71.8) ops/second in (62.220023,125.320922) seconds
2022/02/09-14:54:35  ... thread 4: (5000,9000) ops and (79.7,71.7) ops/second in (62.723400,125.493200) seconds
2022/02/09-14:54:35  ... thread 24: (5000,9000) ops and (79.5,71.7) ops/second in (62.858574,125.600919) seconds
2022/02/09-14:54:35  ... thread 1: (5000,9000) ops and (79.1,71.6) ops/second in (63.194630,125.637031) seconds
2022/02/09-14:54:35  ... thread 47: (5000,9000) ops and (79.9,71.6) ops/second in (62.544286,125.774945) seconds
2022/02/09-14:54:35  ... thread 37: (5000,9000) ops and (79.9,71.5) ops/second in (62.604428,125.794365) seconds
2022/02/09-14:54:35  ... thread 34: (5000,9000) ops and (78.8,71.5) ops/second in (63.425449,125.802187) seconds
2022/02/09-14:54:35  ... thread 44: (5000,9000) ops and (80.0,71.5) ops/second in (62.483941,125.813063) seconds
2022/02/09-14:54:35  ... thread 27: (5000,9000) ops and (79.4,71.5) ops/second in (62.933243,125.847482) seconds
2022/02/09-14:54:35  ... thread 35: (5000,9000) ops and (80.2,71.5) ops/second in (62.359990,125.929797) seconds
2022/02/09-14:54:35  ... thread 14: (5000,9000) ops and (78.8,71.5) ops/second in (63.479735,125.950035) seconds
2022/02/09-14:54:35  ... thread 7: (5000,9000) ops and (79.5,71.4) ops/second in (62.861219,126.034894) seconds
2022/02/09-14:54:35  ... thread 12: (5000,9000) ops and (79.6,71.4) ops/second in (62.786784,126.042980) seconds
2022/02/09-14:54:35  ... thread 15: (5000,9000) ops and (79.5,71.4) ops/second in (62.903416,126.046182) seconds
2022/02/09-14:54:35  ... thread 56: (5000,9000) ops and (78.3,71.4) ops/second in (63.843494,126.092803) seconds
2022/02/09-14:54:35  ... thread 46: (5000,9000) ops and (79.1,71.3) ops/second in (63.232230,126.153757) seconds
2022/02/09-14:54:35  ... thread 45: (5000,9000) ops and (79.5,71.3) ops/second in (62.899582,126.203827) seconds
2022/02/09-14:54:35  ... thread 58: (5000,9000) ops and (80.1,71.3) ops/second in (62.438146,126.237852) seconds
2022/02/09-14:54:35  ... thread 39: (5000,9000) ops and (78.7,71.3) ops/second in (63.502366,126.249905) seconds
2022/02/09-14:54:35  ... thread 60: (5000,9000) ops and (79.3,71.3) ops/second in (63.036453,126.276446) seconds
2022/02/09-14:54:35  ... thread 5: (5000,9000) ops and (79.5,71.3) ops/second in (62.882120,126.282745) seconds
2022/02/09-14:54:35  ... thread 33: (5000,9000) ops and (79.0,71.2) ops/second in (63.320380,126.319864) seconds
2022/02/09-14:54:35  ... thread 19: (5000,9000) ops and (79.6,71.2) ops/second in (62.782914,126.340931) seconds
2022/02/09-14:54:36  ... thread 41: (5000,9000) ops and (78.9,71.2) ops/second in (63.379826,126.378838) seconds
2022/02/09-14:54:36  ... thread 31: (5000,9000) ops and (79.3,71.2) ops/second in (63.050871,126.491973) seconds
2022/02/09-14:54:36  ... thread 11: (5000,9000) ops and (78.6,71.1) ops/second in (63.588695,126.545273) seconds
2022/02/09-14:54:36  ... thread 23: (5000,10000) ops and (79.6,79.0) ops/second in (62.835801,126.575103) seconds
2022/02/09-14:54:36  ... thread 26: (5000,9000) ops and (79.0,71.1) ops/second in (63.285254,126.665764) seconds
2022/02/09-14:54:36  ... thread 29: (5000,9000) ops and (78.8,71.0) ops/second in (63.485178,126.679064) seconds
2022/02/09-14:54:36  ... thread 8: (5000,9000) ops and (80.5,71.0) ops/second in (62.131567,126.724259) seconds
2022/02/09-14:54:36  ... thread 6: (5000,9000) ops and (79.0,71.0) ops/second in (63.253754,126.752663) seconds
2022/02/09-14:54:36  ... thread 62: (5000,9000) ops and (78.9,71.0) ops/second in (63.342086,126.838467) seconds
2022/02/09-14:54:36  ... thread 49: (5000,9000) ops and (78.9,70.9) ops/second in (63.402819,126.890820) seconds
2022/02/09-14:54:36  ... thread 42: (5000,9000) ops and (78.5,70.9) ops/second in (63.654206,126.899655) seconds
2022/02/09-14:54:36  ... thread 20: (5000,9000) ops and (79.6,70.9) ops/second in (62.822210,126.911978) seconds
2022/02/09-14:54:36  ... thread 0: (5000,9000) ops and (78.3,70.9) ops/second in (63.827032,126.985635) seconds
2022/02/09-14:54:36  ... thread 30: (5000,9000) ops and (79.4,70.8) ops/second in (62.978095,127.043456) seconds
2022/02/09-14:54:36  ... thread 3: (5000,9000) ops and (80.1,70.8) ops/second in (62.451927,127.047024) seconds
2022/02/09-14:54:36  ... thread 22: (5000,9000) ops and (78.8,70.8) ops/second in (63.412735,127.096012) seconds
2022/02/09-14:54:36  ... thread 40: (5000,9000) ops and (78.9,70.8) ops/second in (63.344195,127.106659) seconds
2022/02/09-14:54:36  ... thread 50: (5000,9000) ops and (78.6,70.8) ops/second in (63.591866,127.112867) seconds

** Compaction Stats [default] **
Level    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) CompMergeCPU(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop Rblob(GB) Wblob(GB)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  L0   1011/1011 54.87 GB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0       0.0       0.0
 Sum   1011/1011 54.87 GB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0       0.0       0.0
 Int      0/0    0.00 KB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0       0.0       0.0

** Compaction Stats [default] **
Priority    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) CompMergeCPU(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop Rblob(GB) Wblob(GB)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Blob file count: 0, total size: 0.0 GB

Uptime(secs): 127.9 total, 63.9 interval
Flush(GB): cumulative 0.000, interval 0.000
AddFile(GB): cumulative 0.000, interval 0.000
AddFile(Total Files): cumulative 0, interval 0
AddFile(L0 Files): cumulative 0, interval 0
AddFile(Keys): cumulative 0, interval 0
Cumulative compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
Interval compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
Stalls(count): 0 level0_slowdown, 0 level0_slowdown_with_compaction, 1 level0_numfiles, 0 level0_numfiles_with_compaction, 0 stop for pending_compaction_bytes, 0 slowdown for pending_compaction_bytes, 0 memtable_compaction, 0 memtable_slowdown, interval 0 total count
Block cache LRUCache@0x28a68e0#11433 capacity: 6.00 GB collections: 1 last_copies: 0 last_secs: 6.2e-05 secs_since: 127
Block cache entry stats(count,size,portion): Misc(1,0.00 KB,0%)

**Comment by ajkr** [comment] 2022-02-10 02:19
Duplicate of #9445. Please add your comments to the original issue, even if it is closed.

**Closed by ajkr** 2022-02-10 02:20 UTC
